ddclient: T3897: Add option for IPv6 Dynamic DNS
vyos/vyos-1x pull request #1022
Opened 2021-10-11 06:45 UTC by sever-sever

## Change Summary

Allow to use IPv6 for service Dynamic DNS

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3897

## Component(s) name

ddclient, ddns
## Proposed changes
Allow using IPv6 option. By default, it expected an IPv4 address.
Add option "v6-only"

## How to test
WIthout this option I get IPv6 address on interface eth2
```
set service dns dynamic interface eth2 service dynv6 host-name 'xxx.dynv6.net'
set service dns dynamic interface eth2 service dynv6 login 'none'
set service dns dynamic interface eth2 service dynv6 password 'xxx'
set service dns dynamic interface eth2 service dynv6 protocol 'dyndns2'
set service dns dynamic interface eth2 service dynv6 server 'dynv6.com'
```
In logs it compare IPv4 address
```
Oct 11 09:09:34 r1-roll ddclient[2246]: WARNING:  malformed IPv4 address (xxxx:xxx:xx:458::126)
Oct 11 09:10:34 r1-roll ddclient[2526]: WARNING:  malformed IPv4 address (xxxx:xxx:xx:458::126)
Oct 11 09:11:34 r1-roll ddclient[2529]: WARNING:  malformed IPv4 address (xxxx:xxx:xx:458::126)
Oct 11 09:12:34 r1-roll ddclient[2532]: WARNING:  malformed IPv4 address ( xxxx:xxx:xx:458::126)

```
With this option, all works as expected:
```
set service dns dynamic interface eth2 service dynv6 host-name 'xxx.dynv6.net'
set service dns dynamic interface eth2 service dynv6 login 'none'
set service dns dynamic interface eth2 service dynv6 password 'xxx'
set service dns dynamic interface eth2 service dynv6 protocol 'dyndns2'
set service dns dynamic interface eth2 service dynv6 server 'dynv6.com'
set service dns dynamic interface eth2 v6-only

```
Logs:
```
Oct 11 09:28:38 r1-roll systemd[1]: ddclient.service: Succeeded.
Oct 11 09:28:39 r1-roll ddclient[4005]: SUCCESS:  updating xxx.dynv6.net: good: IP address set to xxxx:xxx:xx:458::126
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2021-10-11 13:03 UTC, c-po commented
Very interesting, thanks.

A question which came to my mind - if I have a dual stack system I would require two DDNS entries. Any chance to make this work for both IPv4 and IPv6 for the same DDNS record?

2021-10-11 14:29 UTC, sever-sever commented
> Any chance to make this work for both IPv4 and IPv6 for the same DDNS record?

I just test it with dynv6.com + peth interfaces (peth1 dhcp and peth2 dhcpv6)
It seems that they do not allow using both, when you use "use=if | usev6=if"
Maybe it is possible with custom API/hooks/cmd/web. But we don't have it in CLI. 
https://dynv6.com/docs/apis#update

I can't say about other DDNS services.

2021-10-16 17:11 UTC, c-po requested changes

2021-10-16 17:11 UTC, c-po commented on interface-definitions/dns-dynamic.xml.in
> +                  <leafNode name="v6-only">
For CLI consistency please use `ipv6-enable` with a help string telling the user that this explicitly enables IPv6 DDNS on this ddclient instance.

2021-10-16 17:12 UTC, c-po commented
Please also update smoketests in `test_service_dns_dynamic.py` and the documentation.

2021-10-18 12:02 UTC, sever-sever commented on interface-definitions/dns-dynamic.xml.in
> +                  <leafNode name="v6-only">
Done

2021-10-18 12:02 UTC, sever-sever commented
> Please also update smoketests in `test_service_dns_dynamic.py` and the documentation.

Smotekest done
PR for documentation https://github.com/vyos/vyos-documentation/pull/641

2021-10-18 16:14 UTC, merged