containers: T3916: Add capabilities net-raw and sys-admin
vyos/vyos-1x pull request #1031
Opened 2021-10-19 23:00 UTC by sever-sever

## Change Summary

Add/extend container capabilities "net_raw" and "sys_admin"

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3916

## Component(s) name

containers
## Proposed changes
Add container with capabilities:
```
set container name busybox allow-host-networks
set container name busybox cap-add 'net-raw'
set container name busybox cap-add 'sys-admin'
set container name busybox image 'alpine'

```
Inspect container:
```
vyos@r1-roll# sudo podman inspect busybox | grep -i "\-add="
                "--cap-add=NET_RAW",
                "--cap-add=SYS_ADMIN",
[edit]
vyos@r1-roll# 
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2021-10-19 23:50 UTC, dmbaturin requested changes

2021-10-19 23:50 UTC, dmbaturin commented on interface-definitions/containers.xml.in
>                <help>Add capabilities</help>
There's an agreement to avoid verbs when possible and use knowns. Like "Container capabilities".

2021-10-19 23:50 UTC, dmbaturin commented on interface-definitions/containers.xml.in
> +                <description>Net-raw option</description>
People may now know what exactly those capabilities do, so a brief description like "Permission to create raw network sockets" wouldn't harm. I think other capabilities also deserve descriptions.

2021-10-20 18:23 UTC, sever-sever commented on interface-definitions/containers.xml.in
>                <help>Add capabilities</help>
Done

2021-10-20 18:24 UTC, sever-sever commented on interface-definitions/containers.xml.in
> +                <description>Net-raw option</description>
Done

2021-10-25 19:06 UTC, c-po requested changes

2021-10-25 19:06 UTC, c-po commented on interface-definitions/containers.xml.in
> +                <description>Permission for administation oprtaions (quotactl, mount, sethostname, setdomainame)</description>
Typo: `oprtaions`

2021-10-25 19:06 UTC, c-po commented on interface-definitions/containers.xml.in
> +              <help>Container capabilities</help>
Maybe call this `Container capabilities/permissions` to spare the redundant use of `Permission` in every valueHelp.

2021-10-25 19:20 UTC, sever-sever commented on interface-definitions/containers.xml.in
> +                <description>Permission for administation oprtaions (quotactl, mount, sethostname, setdomainame)</description>
Done, thanks

2021-10-25 19:24 UTC, sever-sever commented on interface-definitions/containers.xml.in
> +              <help>Container capabilities</help>
Done

2021-10-25 19:26 UTC, merged