T3796:op-mode: wireguard interface not shown
vyos/vyos-1x pull request #1061
Opened 2021-11-02 17:14 UTC by srividya0208

## Change Summary

When executed the command 'show interfaces wireguard' command, it is not
showing the configured interface in the output. Modified the script to show
the interface results.
Also modified the script to show in detail information when the specific interface is mentioned.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/Txxxx
https://phabricator.vyos.net/T3796

## Component(s) name

wireguard,
## Proposed changes

proper syntax is added to show the configured interfaces
## How to test
 Add the wireguard configuration:
set interfaces wireguard wg01 address 'x.x.x.x/x'
set interfaces wireguard wg01 peer wg01 allowed-ips 'x.x.x.x/x'
set interfaces wireguard wg01 peer wg01 endpoint 'x.x.x.x:51820'
set interfaces wireguard wg01 peer wg01 pubkey 'xO4cT2OkoqjQfY7DG/4Tu55e7koXZFS7mk9VSLoRH04='
set interfaces wireguard wg01 port '51820'

Then run this command:

$ show interfaces wireguard
$ show interface wireguard wg01

Desired O/P:

vyos@labR1:~$ show interfaces wireguard
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface        IP Address                        S/L  Description
---------        ----------                        ---  -----------
wg01             x0.x00.0.x0/xx                    u/u  wg01

vyos@labR1:~$ show interfaces wireguard wg01
wg01: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 10.100.0.10/24 scope global wg01
       valid_lft forever preferred_lft forever
    Description: wg01

    RX:  bytes    packets     errors    dropped    overrun      mcast
             0          0          0          0          0          0
    TX:  bytes    packets     errors    dropped    carrier collisions
             0          0          0          0          0          0

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2021-11-02 18:17 UTC, c-po approved these changes

2021-11-03 08:11 UTC, sever-sever requested changes

2021-11-03 08:11 UTC, sever-sever commented on op-mode-definitions/wireguard.xml
> +	  </node>
Make the correct indentation for the block "node" "properties" and "help".

2021-11-05 15:31 UTC, sever-sever approved these changes

2021-11-11 18:56 UTC, merged