firewall: T4178: Use lowercase for TCP flags and add an validator
vyos/vyos-1x pull request #1167
Opened 2022-01-13 20:29 UTC by sarthurdev

## Change Summary

* Fix for case sensitivity in nftables config
* Add tcp flags validator

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4178

## Component(s) name

firewall, policy

## Proposed changes

## How to test

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-01-13 20:37 UTC, c-po commented
I wonder if we can not use the new firewall systems migration script whichvisbin place to also migrate the flags from upper to lowercase in the CLI?

2022-01-13 20:38 UTC, c-po requested changes

2022-01-13 20:38 UTC, c-po commented on interface-definitions/include/firewall/common-rule.xml.i
>          </valueHelp>
Please also add valueHelp for each individual flag and also a completionHelper list so tab complete will work :)

2022-01-14 13:06 UTC, sarthurdev commented
Don't think migration is necessary for text case, I think we should handle both and just output to lowercase for nftables.

2022-01-14 17:35 UTC, c-po commented
It might work but would be bad practice if CLI accepts both upper and loser case versions ;) - prone to error

2022-01-14 19:30 UTC, c-po commented
this needs to be refactored in a later sped, as multiple flags on a comma separated line just feels wrong

2022-01-14 19:30 UTC, merged