T4186
vyos/vyos-1x pull request #1173
Opened 2022-01-16 15:39 UTC by nicolas-fort

## Change Summary

In firewall, there were options for icmp type-name that are not supported in nft. Those options were removed, and helpers for options that remains were also changed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4186

## Component(s) name

Firewall
## Proposed changes

Reduce options for icmp type-name to the ones that are supported in nft. this options are available [here](https://wiki.nftables.org/wiki-nftables/index.php/Matching_packet_headers#Matching_ICMP_traffic)
Also description for this options where modified, giving a clearer information of what type of icmp message is being matched.

## How to test

```
vyos@vyos# set firewall name FOO rule 10 icmp type-name 
Possible completions:
   echo-reply   ICMP type 0: echo-reply
   destination-unreachable
                ICMP type 3: destination-unreachable
   source-quench
                ICMP type 4: source-quench
   redirect     ICMP type 5: redirect
   echo-request ICMP type 8: echo-request
   router-advertisement
                ICMP type 9: router-advertisement
   router-solicitation
                ICMP type 10: router-solicitation
   time-exceeded
                ICMP type 11: time-exceeded
   parameter-problem
                ICMP type 12: parameter-problem
   timestamp-request
                ICMP type 13: timestamp-request
   timestamp-reply
                ICMP type 14: timestamp-reply
   info-request ICMP type 15: info-request
   info-reply   ICMP type 16: info-reply
   address-mask-request
                ICMP type 17: address-mask-request
   address-mask-reply
                ICMP type 18: address-mask-reply
                
[edit]

```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-01-16 16:35 UTC, c-po commented
You have dropped the `any` type option without a migration script or alternative. This will break existing configurations.

Hence the type explanations are nice - thank you for this. Maybe split this PR in two parts - lave the any option intact and fix the valueHelps, and another commit that does the `any` cleanup with a migrator.

2022-01-16 16:36 UTC, c-po requested changes
You have dropped the `any` type option without a migration script or alternative - this will break existing configurations.

The type explanations are nice - thank you for this. Maybe split this PR in two parts - lave the `any` option intact and fix the `valueHelp`, and another commit that does the `any` cleanup with a migrator.

2022-01-17 11:30 UTC, nicolas-fort commented
Now that you pointed out, I can see that without migration script, not only "any" options will break existing configuration. Also all  other options that were removed will break existing config.
So, without migration script, this PR makes no sense.

2022-01-21 17:08 UTC, nicolas-fort commented
@sarthurdev Think it's ready for adding migration scripts.

2022-01-22 07:55 UTC, c-po commented
Superseeded by #1184

2022-01-22 07:55 UTC, closed without merging