T4193
vyos/vyos-1x pull request #1202
Opened 2022-02-03 12:54 UTC by dmbaturin

## Change Summary

Initial implementation of the bridge firewal (conf mode)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4193

## Component(s) name

Firwewall.

## Proposed changes

## How to test

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-02-03 13:24 UTC, sever-sever requested changes

2022-02-03 13:24 UTC, sever-sever commented on src/conf_mode/firewall-bridge.py
> +from pprint import pprint
It can be removed

2022-02-03 13:24 UTC, sever-sever commented on src/conf_mode/firewall-bridge.py
> +    pprint(firewall)
Remove this `pprint`

2022-02-03 13:46 UTC, sever-sever requested changes

2022-02-03 13:46 UTC, sever-sever commented on interface-definitions/firewall-bridge.xml.in
> +          <node name="bridge" owner="${vyos_conf_scripts_dir}/firewall-bridge.py"">
.py"">
Delete extra quote

2022-02-03 23:11 UTC, sarthurdev commented
firewall.py should be updated from current to include a few new bugfixes in `parse_rule()`

2022-02-08 09:19 UTC, sever-sever approved these changes

2022-05-21 10:46 UTC, andamasov commented
@c-po @jestabro can you check this one, please

2022-08-22 16:44 UTC, jestabro approved these changes

2022-08-22 16:54 UTC, dmbaturin commented
We shouldn't merge it until 1.3.2 is tagged off.

2023-08-30 11:37 UTC, sever-sever commented
@dmbaturin Could you solve conflicts?
Will we merge it?

2023-08-31 14:51 UTC, dmbaturin commented
The new firewall implementation is much more conductive to this change, and with 1.4 nearing the LTS phase, this is likely irrelevant.

2023-08-31 14:51 UTC, closed without merging