T4319: bugfixes for disabled IPv6 (equuleus)
vyos/vyos-1x pull request #1261
Opened 2022-03-31 19:14 UTC by c-po

## Change Summary

Commit c82db71f started this discussion as disabling an entire address family in the Kernel has huge side effects.

This PR extends the implementation with a new helper `is_ipv6_disabled()` to detect the current state. Also IPv6 addresses should not be added (and can not be added) to an interface if IPv6 is disabled on the kernel - we simply ignore the addresses when configuring the Kernel.

VRF instances also should no longer receive a ::/128 localhost IPv6 address once IPv6 is disabled on the system.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4319

## Component(s) name

* VRF
* IPv6
* Interfaces

## Proposed changes

## How to test

VyOS smoketests

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-04-05 12:14 UTC, sever-sever commented
The question is more complex
As it should also check if IPv6 exists in other services (snmp, ssh, nameservers, pppoe, etc) as listen-address/configs
Maybe it should be some global checks/finds
By the way, I approve it

2022-04-05 12:15 UTC, sever-sever approved these changes

2022-04-06 11:15 UTC, dmbaturin requested changes

2022-04-06 11:15 UTC, dmbaturin commented on python/vyos/ifconfig/interface.py
>              tmp = dict_search('ipv6.disable_forwarding', config)
Please note that there are two different commands with different intended effects.

`set system ipv6 disable-forwarding` is supposed to _only_ disable IPv6 packet routing. It isn't for disabling IPv6 completely, the system may still act as an IPv6 web proxy, DNS resolver, or perform some other network service that doesn't involve forwarding unprocessed packets between interfaces.

It's `set system ipv6 disable` that is meant to make the system IPv4-only: not just no forwarding, but also no IPv6 loopback, no link-locals, no other traces of IPv6.

Well, that's the uncontroversial part of my comment, just a correction.

**However!** One reason I put a sysctl read there was that IPv6 may potentially be disabled by something else: some cloud-init stuff, kernel command line, or a user who loves messing up with sysctl... I'm not sure if that idea has unfortunate implications that just reading from the config would avoid, but I think this issue does deserve more discussion.

2022-04-07 14:18 UTC, dmbaturin approved these changes

2022-04-07 14:19 UTC, merged