monitoring: T4418: Add output plugin azure-data-explorer
vyos/vyos-1x pull request #1317
Opened 2022-05-06 16:42 UTC by sever-sever

## Change Summary

Add output telegraf Plugin Azure Data Explorer

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4418

## Component(s) name

monitoring, telegraf
## Proposed changes

## How to test
```
set service monitoring telegraf azure-data-explorer authentication client-id 'some-clientID'
set service monitoring telegraf azure-data-explorer authentication client-secret 'SecRtetsdf'
set service monitoring telegraf azure-data-explorer authentication tenant-id 'some-tanantID'
set service monitoring telegraf azure-data-explorer database 'foo_data'
set service monitoring telegraf azure-data-explorer group-metrics 'table-per-metric'
set service monitoring telegraf azure-data-explorer url 'http://localhost.loc'
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-05-19 18:22 UTC, c-po requested changes

2022-05-19 18:22 UTC, c-po commented on interface-definitions/service_monitoring_telegraf.xml.in
> +                          <help>Application client id</help>
Should we add a validator here?

2022-05-19 18:22 UTC, c-po commented on interface-definitions/service_monitoring_telegraf.xml.in
> +                          <help>Application client secret</help>
Should we add a validator here?

2022-05-19 18:22 UTC, c-po commented on interface-definitions/service_monitoring_telegraf.xml.in
> +                          <help>Set tenant id</help>
Should we add a validator here?

2022-05-19 18:22 UTC, c-po commented on interface-definitions/service_monitoring_telegraf.xml.in
> +                        <description>Remote database name</description>
Should we add a validator here?

2022-05-19 18:22 UTC, c-po commented on interface-definitions/service_monitoring_telegraf.xml.in
> +                        <description>Remote database name</description>
Should we add a validator here?

2022-05-19 22:09 UTC, sever-sever commented
To be honest, I'm not familiar with Azure and required formats
I tried to find format `client-id, client secret, tenant-id` but it was unsuccessful
https://github.com/MicrosoftDocs/dataexplorer-docs/tree/main/data-explorer

It takes time to find at least some format data

2022-05-20 05:17 UTC, c-po commented
> To be honest, I'm not familiar with Azure and required formats I tried to find format `client-id, client secret, tenant-id` but it was unsuccessful https://github.com/MicrosoftDocs/dataexplorer-docs/tree/main/data-explorer
> 
> It takes time to find at least some format data

I guess alphanumeric is always a good idea to be as open as possible bit deny gancy german umlauts, what you think?

2022-05-20 14:00 UTC, sever-sever commented
> I guess alphanumeric is always a good idea to be as open as possible bit deny gancy german umlauts, what you think?

Done

2022-05-20 15:19 UTC, merged