validators: T4472: Add validator ipv4-range-go in golang
vyos/vyos-1x pull request #1365
Opened 2022-06-19 11:15 UTC by sever-sever

## Change Summary

Go validators decrease the validation time to compares with
bash + ipaddrcheck --something or python3
As PoC we decrease the validation time for `ipv4-range` (10K checks)
from 48 seconds to 27 seconds

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4472

## Component(s) name

## Proposed changes

## How to test
Check validations:
Standard `ipv4-range`
```
vyos@r14# time sudo sh -c ' for ((n=0;n<10000;n++)); do  /usr/libexec/vyos/validate-value  --exec /usr/libexec/vyos/validators/ipv4-range --value "192.0.2.1-192.0.2.100"; done'

real	0m48.825s
user	0m26.534s
sys	0m23.904s
[edit]
vyos@r14#
```
The same validator in `go` 
```
vyos@r14# time sudo sh -c ' for ((n=0;n<10000;n++)); do  /usr/libexec/vyos/validate-value  --exec /usr/libexec/vyos/validators/ipv4-range-go --value "192.0.2.1-192.0.2.100"; done'

real	0m27.069s
user	0m12.814s
sys	0m14.784s
[edit]
vyos@r14#
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-06-25 09:14 UTC, c-po approved these changes

2022-06-25 12:13 UTC, dmbaturin requested changes
I'm strongly against merging this PR.

I agree the problem exists. However, Viacheslav, did you forget that we are the maintainers of ipaddrcheck? ;)

Simon created a quick hack to support that, and it's indeed time to replace it with a proper solution, but I don't think your solution is optimal. It's exactly what we wanted to _avoid_, and why I made ipaddrcheck to begin with—to have that logic in one place.

Your approach requires adding a golang dependency _just_ for a single file and it will also required a separate test suite. By adding that feature to ipaddrcheck we can keep vyos-1x free of extra build deps and _just_ add tests to the existing ipaddrcheck test harness (which is rather extensive—I spent a lot of time to make sure it is).

Here's a draft PR, without IPv6 support or tests yet: vyos/ipaddrcheck/pull/6

2022-06-25 17:48 UTC, sever-sever commented
> Your approach requires adding a golang dependency

We already have golang in vyos-build
So it doesn’t require any additional package

2022-09-01 14:56 UTC, closed without merging

2022-09-01 15:10 UTC, sever-sever commented
Close it, the original issue was solved, but we agree that it could be a good experience for the next validators