router-advert: Add deprecate-prefix & decrement-lifetimes options
vyos/vyos-1x pull request #1421
Opened 2022-07-21 07:54 UTC by vfreex

- deprecate-prefix: Upon shutdown, deprecate the prefix. This is useful
  in a DHCPv6 PD environment: When ISP re-assigns a new prefix,
deprecate the old prefix that was advertised.
- decrement-lifetimes: Decrement the values of the preferred and valid
  lifetimes for the prefix over time. This is also useful in a DHCPv6
  PD environment to keep the advertised prefix's lifetimes in sync with
  the prefix from delegating router.

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/Txxxx

## Component(s) name

## Proposed changes

## How to test

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-07-21 09:14 UTC, dmbaturin requested changes
Looks good to me! Please add the task number to the commit description (not only to the PR title). Without a task number, Phabricator will not associate the commit with the task.

2022-07-21 10:01 UTC, vfreex commented
@dmbaturin Thanks for the review. I've amended my commit description.

2022-07-21 10:33 UTC, dmbaturin approved these changes

2022-07-21 10:47 UTC, sever-sever commented
As we have `preferred-lifetime` maybe it should be `decrement-lifetime` not `decrement-lifetimes`?

2022-07-21 16:03 UTC, vfreex commented
> As we have `preferred-lifetime` maybe it should be `decrement-lifetime` not `decrement-lifetimes`?
It is called `DecrementLifetimes` in radvd config. It decreases both preferred lifetime and valid lifetime.

> Should we avoid comas in the description?
I've updated the description.

2022-07-21 16:51 UTC, c-po requested changes

2022-07-21 16:51 UTC, c-po commented on interface-definitions/service-router-advert.xml.in
> +                      <help>Deprecate the prefix on shutdown</help>
Please update the help to: `Upon shutdown, this option will deprecate the prefix by announcing it in the shutdown RA`

2022-07-21 16:51 UTC, c-po commented on interface-definitions/service-router-advert.xml.in
> +                      <help>Decrement the values of the preferred and valid lifetimes for the prefix over time</help>
Please update the help string to: `Lifetime is decremented by the number of seconds since the last RA - use in conjunction with a DHCPv6-PD prefix.`

2022-07-21 16:53 UTC, c-po commented
> It is called `DecrementLifetimes` in radvd config. It decreases both preferred lifetime and valid lifetime.

Please use only singular in the VyOS CLI. Please change this to `decrement-lifetime` despite the fact that radvd calls it in plural under the hood, but VyOS is the layer in between and we do all the user translations.

2022-07-21 17:13 UTC, vfreex commented
@c-po Thanks for the review. Updated.

2022-07-22 01:10 UTC, sever-sever approved these changes

2022-07-22 06:26 UTC, merged