Openconnect: T4656: Add listen-host field to specific the address to …
vyos/vyos-1x pull request #1510
Opened 2022-08-30 18:36 UTC by xbugio

…listen on.

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4656

## Component(s) name

Openconnect VPN
## Proposed changes

Add support to specific which address for the service to listen on
## How to test

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-08-30 19:11 UTC, sever-sever requested changes

2022-08-30 19:11 UTC, sever-sever commented on interface-definitions/vpn-openconnect.xml.in
> +          <leafNode name="listen-host">
Could you change it to `listen-address`?

2022-08-31 05:31 UTC, sever-sever commented
Could we set several “listen-addresses”?
Should it listen by default and IPv6?

2022-08-31 05:35 UTC, xbugio commented
> 

That might be unable to set  several “listen-addresses” 'cause the ocserv only supports one address to listen.

2022-08-31 10:11 UTC, sever-sever commented
> > 
> 
> That might be unable to set several “listen-addresses” 'cause the ocserv only supports one address to listen.

The thing is, by default `ocserv` listen both IPv4 and IPv6 addresses
```
vyos@r14# sudo netstat -tulpn | grep 443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      3407/ocserv-main    
tcp6       0      0 :::443                  :::*                    LISTEN      3407/ocserv-main    
udp        0      0 0.0.0.0:443             0.0.0.0:*                           3407/ocserv-main    
udp6       0      0 :::443                  :::*                                3407/ocserv-main  
```

2022-08-31 10:50 UTC, xbugio commented
@sever-sever 
I manually edited the ocserv config file "/var/run/ocserv.conf" and added two lines of 'listen-host' trying to listen on two address. 
But finally i only got the last address listened.


![01](https://user-images.githubusercontent.com/20812285/187659032-b2bbee24-fee6-4516-9913-59f0b707e541.jpg)
![02](https://user-images.githubusercontent.com/20812285/187659053-c5d0ef6b-b079-4096-8188-1f634cd0f78e.jpg)

And I seeked through the source code of ocserv, it turned out that the type of listen_host in config struct is "char *" which means it only stores one address.


![03](https://user-images.githubusercontent.com/20812285/187659515-0664ffba-e009-4dd3-a409-ef3d241e61c7.jpg)


As for the default behavior when no listen_host is configured, the ocserv uses "getaddrinfo" func to resolv the listen_host, the function may returns both ipv4 and ipv6 address (0.0.0.0 and ::)，so it listens on both ipv4 and ipv6 address.


![06](https://user-images.githubusercontent.com/20812285/187662001-b4ec8031-f9b5-4a42-9b0c-215172003e12.jpg)

![07](https://user-images.githubusercontent.com/20812285/187662009-b5bf7306-2b52-49eb-afb5-fac265bb33f0.jpg)

2022-08-31 10:54 UTC, sever-sever approved these changes

2022-09-01 17:34 UTC, c-po requested changes

2022-09-01 17:34 UTC, c-po commented on interface-definitions/vpn-openconnect.xml.in
> +          <leafNode name="listen-address">
Please use our generic building block instead: `#include <include/listen-address.xml.i>`

We also do not listen on FQDNs ... we like IP addresses :)

2022-09-16 07:23 UTC, merged