T2408: dhcp-relay: Add listen-interface and upstream-interface feature
vyos/vyos-1x pull request #1603
Opened 2022-10-18 11:54 UTC by nicolas-fort

## Change Summary

Add support for defining listen-interface and upstream-interface in dhcp-relay. Also keep <interface> option for backward s compatibility.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T2408

## Component(s) name

dhcp-relay
## Proposed changes

Add support for defining listen-interface and upstream-interface in dhcp-relay (same names as used in dhcpv6-relay). Also keep <interface> option for backwards compatibility (print warning message when this legacy option is used).

## How to test

cli:
```
vyos@VyOS-130-2# set service dhcp-relay 
Possible completions:
+  interface            Interface Name to use [To be deprecated]. Only for backward
                        compatibility. Use listen-interface and upstream-interface
                        instead of this option
+  listen-interface     Interface for DHCP Relay Agent to listen for requests
 > relay-options        Relay options
+  server               DHCP server address
+  upstream-interface   Interface for DHCP Relay Agent forward requests out
```
Legacy config:
```
vyos@VyOS-130-2# set serv dhcp-relay interface eth3.10 
[edit]
vyos@VyOS-130-2# set serv dhcp-relay interface eth1
[edit]
vyos@VyOS-130-2# set serv dhcp-relay server 203.0.113.2
[edit]
vyos@VyOS-130-2# commit

WARNING: <interface> is going to be deprecated. Please use <listen-interface> and
<upstream-interface>
[edit]
vyos@VyOS-130-2# cat /run/dhcp-relay/dhcrelay.conf 
### Autogenerated by dhcp_relay.py ###

OPTIONS="-c 10 -a -m forward -A 576 -i eth3.10 -i eth1 203.0.113.2"
[edit]
```

And new config:
```
vyos@VyOS-130-2# set service dhcp-relay listen-interface eth3.10
[edit]
vyos@VyOS-130-2# set service dhcp-relay upstream-interface eth1
[edit]
vyos@VyOS-130-2# set service dhcp-relay server 203.0.113.2
[edit]
vyos@VyOS-130-2# commit
[edit]
vyos@VyOS-130-2# cat /run/dhcp-relay/dhcrelay.conf 
### Autogenerated by dhcp_relay.py ###

OPTIONS="-c 10 -a -m forward -A 576 -id eth3.10 -iu eth1 203.0.113.2"
[edit]

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-10-19 12:22 UTC, zdc approved these changes

2022-10-21 13:51 UTC, sever-sever commented
in my opinion, it should just extend the `interface` with 2 options
```
set service dhcp-relay interface eth1 
set service dhcp-relay interface <tag> upstream | downstream
```

2022-11-03 19:47 UTC, c-po requested changes
The current state of this PR requires a migration script as already pointed out by @sever-sever.

Question remains if it should be implemented as `tagNode` (which would still require a migrator as neither upstream nor downstream is specified) or as a `leafNode`. I also wonder if it is time for a CLI decission how to name such interfaces.
- `upstream-interface` vs `egress-interface` vs `outbound-interface`
- `downstream-interface` vs `ingress-interface` vs `inbound-interface`

2023-02-04 15:06 UTC, c-po requested changes

2023-02-04 15:06 UTC, c-po commented on interface-definitions/dhcp-relay.xml.in
> +          <leafNode name="interface">
Please keep `#include <include/generic-interface-multi-broadcast.xml.i>` and add a `vyos.base.Warning()` message inside the Python script when the old command is used.

2023-02-04 15:11 UTC, merged