T4780: Firewall: add firewall groups in firewall. Extend matching cri…
vyos/vyos-1x pull request #1626
Opened 2022-10-28 18:43 UTC by nicolas-fort

…teria so this new group can be used in inbound and outbound matcher

## Change Summary

New feature: firewall interface group.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4780

## Component(s) name

firewall
## Proposed changes

Extend firewall capabilities and add interface-group option
Extend cli so matcher for inbound-interface and outbound-interface can use these new groups

## How to test

Config
```
vyos@vyos# run show config comm | grep fire
set firewall group interface-group IFACEX interface 'eth3'
set firewall group interface-group IFACEX interface 'eth2'
set firewall group interface-group IFACEX interface 'dum0'
set firewall group interface-group IFACEX interface 'vti2'
set firewall group interface-group IFACEX interface 'vtun4'
set firewall group interface-group IFACEX interface 'pp*'
set firewall group interface-group IFACEX interface 'eth0'
set firewall group interface-group IFACEX interface 'eth99'
set firewall interface eth0 local name 'FOO'
set firewall ipv6-name FOO6 rule 66 action 'drop'
set firewall ipv6-name FOO6 rule 66 inbound-interface interface-group 'IFACEX'
set firewall name FOO default-action 'accept'
set firewall name FOO rule 9 action 'accept'
set firewall name FOO rule 9 inbound-interface interface-group 'IFACEX'
set firewall name FOO rule 10 action 'accept'
set firewall name FOO rule 10 outbound-interface interface-group 'IFACEX'
set firewall name FOO rule 15 action 'drop'
```
nftables
```
vyos@vyos# sudo nft -s list table ip vyos_filter
table ip vyos_filter {
        set I_IFACEX {
                type ifname
                flags interval
                auto-merge
                elements = { "dum0",
                             "eth0",
                             "eth2",
                             "eth3",
                             "eth99",
                             "pp*",
                             "vti2",
                             "vtun4" }
        }
...
        chain NAME_FOO {
                iifname @I_IFACEX counter return comment "FOO-9"
                oifname @I_IFACEX counter return comment "FOO-10"
                counter drop comment "FOO-15"
                counter return comment "FOO default-action accept"
        }
}

vyos@vyos# sudo nft -s list table ip6 vyos_filter
table ip6 vyos_filter {
        set I_IFACEX {
                type ifname
                flags interval
                auto-merge
                elements = { "dum0",
                             "eth0",
                             "eth2",
                             "eth3",
                             "eth99",
                             "pp*",
                             "vti2",
                             "vtun4" }
        }  

        chain NAME6_FOO6 {
                iifname @I_IFACEX counter drop comment "FOO6-66"
                counter drop comment "FOO6 default-action drop"
        }
}

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-10-31 14:21 UTC, sever-sever approved these changes

2022-11-03 19:53 UTC, c-po requested changes
I actually wonder about the CLI definition. We have:

- `set firewall name foo rule 1 source | destination `
- `set firewall name foo rule 1 inbound-interface interface-name | interface-group`
- `set firewall name foo rule 1 outbound-interface interface-name | interface-group`

Why not stick to the CLI design and use:

- `set firewall name foo rule 1 source interface eth0`
- `set firewall name foo rule 1 source group interface-group <bar>`
- `set firewall name foo rule 1 destination interface eth0`
- `set firewall name foo rule 1 destination group interface-group <bar>`

Another idea could be:

- `set firewall name foo rule 1 inbound-interface eth0 `
- `set firewall name foo rule 1 inbound-interface-group <foo>`
- `set firewall name foo rule 1 outbound-interface eth1`
- `set firewall name foo rule 1 outbound-interface-group <bar>`

2022-11-03 22:40 UTC, nicolas-fort commented
> I actually wonder about the CLI definition. We have:
> 
> * `set firewall name foo rule 1 source | destination `
> * `set firewall name foo rule 1 inbound-interface interface-name | interface-group`
> * `set firewall name foo rule 1 outbound-interface interface-name | interface-group`
> 
> Why not stick to the CLI design and use:
> 
> * `set firewall name foo rule 1 source interface eth0`
> * `set firewall name foo rule 1 source group interface-group <bar>`
> * `set firewall name foo rule 1 destination interface eth0`
> * `set firewall name foo rule 1 destination group interface-group <bar>`
> 
> Another idea to de-nest the CLI could be (maybe also for future de-nesting of port groups and address groups`:
> 
> * `set firewall name foo rule 1 inbound-interface eth0 `
> * `set firewall name foo rule 1 inbound-interface-group <foo>`
> * `set firewall name foo rule 1 outbound-interface eth1`
> * `set firewall name foo rule 1 outbound-interface-group <bar>`

I decided not to use **_interface|interface-group_** as **_source|destination_** parameters, since those definitions may lead to more confusion: for example "**_source interface eth4_**". This could be interpreted as packet originated from interface eth4 of the router, rather than a packet that was received on such interface.

2022-11-22 14:57 UTC, zdc approved these changes

2022-12-14 19:24 UTC, sarthurdev approved these changes

2022-12-17 07:30 UTC, merged