T4807: Fixed traceroute help completion
vyos/vyos-1x pull request #1647
Opened 2022-11-08 14:31 UTC by aapostoliuk

## Change Summary

Changes in traceroute command:
Added list of possible VRFs in the help.
Added list of possible interfaces in the help.
Changed, if an option was selected before,
it does not appear in possible completion.
Added error message when an unexpected option was selected

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4807

## Component(s) name

op-mode

## Proposed changes

Added list of possible VRFs in the help.
If a vrf exists
Before:

```
vyos@vyos:~$ traceroute 10.10.10.10 vrf
Possible completions:
  <Enter>               Execute the current command
  <vrf>                 Traceroute options

```
After:
```
vyos@vyos:~$ traceroute 10.10.10.10 vrf
Possible completions:
  <Enter>               Execute the current command
  TEST                  Traceroute options
```
Added list of possible interfaces in the help of the ping command.
Before:
```
vyos@vyos:~$ traceroute 10.10.10.10 interface
Possible completions:
  <Enter>               Execute the current command
  <interface>           Traceroute options
```
After:
```
vyos@vyos:~$ traceroute 10.10.10.10 interface
Possible completions:
  <Enter>               Execute the current command
  eth0                  Traceroute options
  eth1
  eth2
  eth3
  lo

```

Changed, if an option was selected before in the ping command, it does not appear in possible completion.
Before:
```
vyos@vyos:~$ traceroute 10.10.10.10 vrf TEST
Possible completions:
  <Enter>               Execute the current command
  backward-hops         Traceroute options
  bypass
  do-not-fragment
  first-ttl
  icmp
  interface
  lookup-as
  mark
  no-resolve
  port
  source-address
  tcp
  tos
  ttl
  udp
  vrf
```
After:
```
vyos@vyos:~$ traceroute 10.10.10.10 vrf TEST
Possible completions:
  <Enter>               Execute the current command
  backward-hops         Traceroute options
  bypass
  do-not-fragment
  first-ttl
  icmp
  interface
  lookup-as
  mark
  no-resolve
  port
  source-address
  tcp
  tos
  ttl
  udp

```
Added error message when an unexpected option was selected.
Before:
```
vyos@vyos:~$ traceroute 10.10.10.10 dfdf Traceback (most recent call last):
  File "/usr/libexec/vyos/op_mode/traceroute.py", line 177, in <module>
    if options[matched[0]]['type'] == 'noarg':
IndexError: list index out of range

Possible completions:
  <Enter>               Execute the current command
  <text>                Traceroute options
```
After:
```
vyos@vyos:~$ traceroute 10.10.10.10 fdfdf

 Invalid option: fdfdf

Possible completions:
  <Enter>               Execute the current command
  <nocomps>             Traceroute options

```

## How to test

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-11-08 19:04 UTC, dmbaturin requested changes

2022-11-08 19:04 UTC, dmbaturin commented on src/op_mode/traceroute.py
> +def vrf_list() -> list:
I think we should make the VRF listing function reusable and put it in `vyos.util` (or maybe a separate module?) so that other scripts can use it later.

2022-11-09 09:31 UTC, aapostoliuk commented on src/op_mode/traceroute.py
> +def vrf_list() -> list:
I found another way. I used the function get_all_vrfs() from vyos.util

2022-11-09 18:59 UTC, c-po commented on src/op_mode/traceroute.py
> +def vrf_list() -> list:
Good!

2022-11-09 19:00 UTC, c-po approved these changes

2022-11-09 19:00 UTC, merged