L3VPN : T4813: add l3vpn over gre option from route-map
vyos/vyos-1x pull request #1655
Opened 2022-11-13 17:14 UTC by fett0

the idea this PR , is to give the ability to transport labels over a next-hop learned in a GRE tunnel, the path chosen by the next-hop uses a GRE interface, and there is a route-map configured at inbound side of ipv4-vpn or ipv6-vpn address

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

 https://phabricator.vyos.net/T4813

## Component(s) name

route-map
## Proposed changes

## How to test

VyOS - CLI : 
set policy route-map l3vpn description 'l3vpn-gre'
set policy route-map l3vpn rule 10 action 'permit'
set policy route-map l3vpn rule 10 set l3vpn-nexthop encapsulation gre

FRR: 

route-map l3vpn permit 10
 set l3vpn next-hop encapsulation gre
exit
!

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-11-13 20:18 UTC, c-po requested changes
Nice addition - please drop the whitespaces and then we're good to go!

2022-11-13 20:18 UTC, c-po commented on interface-definitions/policy.xml.in
> +                      </leafNode>
Please drop the additional whitespaces.

2022-11-13 23:17 UTC, fett0 commented on interface-definitions/policy.xml.in
> +                      </leafNode>
Thanks, Cris!  for gotcha it,  done!

2022-11-14 06:01 UTC, c-po approved these changes

2022-11-14 06:01 UTC, merged