T4809: radvd: Allow the use of AdvRASrcAddress
vyos/vyos-1x pull request #1717
Opened 2022-12-17 17:09 UTC by roedie

## Change Summary

This add the AdvRASrcAddress configuration option to configure a source address for the router advertisements. The source address still must be configured on the system. This is useful for VRRP setups where you want fe80::1 on the VRRP interface for cleaner VRRP failovers.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4809

## Component(s) name

radvd

## Proposed changes

Add: set service router-advert interface eth3 source-address 

## How to test

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-12-20 17:20 UTC, c-po commented
Please also cherry-pick the following commits to this PR:

* 2dc1cbc8
* b9310f57

2022-12-20 17:20 UTC, c-po requested changes

2022-12-20 17:20 UTC, c-po commented on data/templates/router-advert/radvd.conf.tmpl
> +        {{ source_address }}
Missing semicolon, see 4e61fb1f

2022-12-24 17:26 UTC, dmbaturin approved these changes

2022-12-26 18:31 UTC, c-po approved these changes

2022-12-26 18:31 UTC, merged