T4897: vxlan: Fix setting 'source-address' and `source-interface`
vyos/vyos-1x pull request #1726
Opened 2022-12-29 07:49 UTC by vfreex

Steps to reproduce:

- Add a vxlan interface without `source-address` or `source-interface` options set:

```
set interfaces vxlan vxlan999 vni 999
set interfaces vxlan vxlan999 remote 192.168.100.100
commit
```

- Then set `source-address` or `source-interface`:

```
set interfaces vxlan vxlan999 source-interface eth0
commit
```

Actual result:

Source address or source-interface are not set:
```
ip -d link show dev vxlan999
76: vxlan999: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 56:08:ba:4d:4e:a8 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535
    vxlan id 999 remote 192.168.100.100 srcport 0 0 dstport 8472 tos inherit ttl 16 ageing 300 udpcsum noudp6zerocsumtx noudp6zerocsumrx addrgenmode none numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
```

Expected result:

```
77: vxlan999: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 9e:05:d9:58:1a:af brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535
    vxlan id 999 remote 192.168.100.100 dev eth0 srcport 0 0 dstport 8472 tos inherit ttl 16 ageing 300 udpcsum noudp6zerocsumtx noudp6zerocsumrx addrgenmode none numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
```

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4897

## Component(s) name

## Proposed changes

## How to test

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-12-29 07:53 UTC, vfreex commented
I think the return value of this function is error-prone. In https://phabricator.vyos.net/T4897, I would like to recommend the community to review all uses of `leaf_node_changed`.

2022-12-29 20:06 UTC, jestabro commented
This fix works; alternatively, on may use configdict.is_node_changed applied to each of the 'cli_option' in the list. I agree that we may want to review uses of configdict.leaf_node_changed for its return value on non-valueless leaf nodes ([] vs. None).

2022-12-29 20:06 UTC, jestabro approved these changes

2022-12-30 05:21 UTC, c-po commented
> I think the return value of this function is error-prone. In https://phabricator.vyos.net/T4897, I would like to recommend the community to review all uses of `leaf_node_changed`.

As mentioned by John already, if possible all invocations of leaf_node_changed() should be migrated to is_node_changes() if you are only interested in if something changed and don‘t care what exactly changed (content). Can you please adjust this PR?

2022-12-30 08:42 UTC, c-po requested changes
Please replace `leaf_node_changed()` with `is_node_changed()` in this file.

2022-12-30 11:39 UTC, vfreex commented
@jestabro @c-po Thanks for the review. PR is updated.

2022-12-30 18:14 UTC, c-po approved these changes

2022-12-30 18:14 UTC, merged

2024-01-09 17:47 UTC, dmbaturin commented
@mergifyio backport equuleus