container: T4959: Add container registry authentication config for containers
vyos/vyos-1x pull request #1790
Opened 2023-01-30 09:24 UTC by Zen3515

## Change Summary

Add container registry authentication config for containers

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4959

## Component(s) name

- containers

## Proposed changes

- Add `disable`, `username`, and, `password` to `container > registry` for authentication
- Add `default-registry` to container configuration to store default registry for using alongside registry config  

The way this works is by using the provided username and password to login with command `podman login` and save it to a json file `/etc/containers/auth.json`, and when command `add container image` is execute, make it load auth file from that location.

## How to test

To test the new registry generation, I've add and test a smoke test.  
To test the new auth.json file generation

Without any configuration, expect an empty json.
```shell
$ cat auth.json
{}
```

Add registry example.com without username and password.
```bash
$ set container registry example.com
$ commit
$ cat /etc/containers/registries.conf | grep 'unqualified-search-registries = \["docker.io", "quay.io", "example.com"\]'
unqualified-search-registries = ["docker.io", "quay.io", "example.com"]
$ set container registry docker.io username alice
$ set container registry docker.io password alices_password
$ cat /etc/containers/registries.conf | grep 'unqualified-search-registries = \["docker.io", "quay.io", "example.com"\]'
unqualified-search-registries = ["docker.io", "quay.io", "example.com"]
$ sudo cat /etc/containers/auth.json 
{
	"auths": {
		"docker.io": {
			"auth": "YWxpY2U6YWxpY2VzX3Bhc3N3b3Jk"
		}
	}
}
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-02-09 06:29 UTC, c-po requested changes

2023-02-09 06:29 UTC, c-po commented on src/conf_mode/container.py
> +                raise ConfigError(f'Must either not defined username and password, or defined both for registry {registry}')
`If username or password is defined, so must be the other - check "{registry}" registry configuration!`

2023-02-09 06:29 UTC, c-po commented on interface-definitions/container.xml.in
> +              <help>User name for authentication</help>
Please add a regex for matching the username: `[[:alnum:]][-_#@[:alnum:]]{0,127}` - I guess a username with up to 128 characters should be sufficient.


```
<constraint>
  <regex>[[:alnum:]][-_#@[:alnum:]]{0,127}</regex>
</constraint>
```

2023-02-09 06:29 UTC, c-po commented on interface-definitions/container.xml.in
> +              <help>Password for authentication</help>
Please add a regex for matching passwords, `<regex>[[:ascii:]]{1,128}</regex>` 1-128 characters should probably be sufficient.

2023-02-09 06:29 UTC, c-po commented on op-mode-definitions/container.xml.in
> +            <command>if cli-shell-api existsActive container name "$4"; then sudo podman pull --authfile /etc/containers/auth.json $(cli-shell-api returnActiveValue container name "$4" image); else e
Please store the authfile in a volatile location like `/run/podman` so it's cleaned on reboot

2023-02-09 06:29 UTC, c-po commented on src/conf_mode/container.py
> +config_containers_auth = '/etc/containers/auth.json'
Please store the authfile in a volatile location like /run/podman so it's cleaned on reboot. Both other files are cleaned in a hook: https://github.com/vyos/vyatta-cfg/blob/current/scripts/init/vyos-router#L233 or add that file to the hook.

2023-02-09 06:29 UTC, c-po commented on src/conf_mode/container.py
> +    with open(config_containers_auth, "w") as f:
Isn't removing the authfile enough? Won't it be recreated on `podman login`?

2023-02-09 06:29 UTC, c-po commented
Please also extend the container smoketest to verify the authfile is properly generated on the system.

2023-02-09 06:30 UTC, merged

2023-02-09 06:32 UTC, c-po commented
I am very sorry - I accidently merged this (wrong button) and I reverted is. We can keep discussing here or re-publish on a new PR. I am very sorry again.

2023-02-09 06:43 UTC, Zen3515 commented
It's okay, I'll create a new PR for this.
As for the question
> why we need the authfile in the container CLI config as container images must be added manually using: add container image?

When running command `add container image` for private registry or self hosted registry with authentication, it will not be able to pull the image. We could use `sudo podman login` ourself, but it will not persist after vyos version upgrade. Especially when the password is a token generated from docker hub, we could not view that token anymore once generated, thus, needing to generate new token every time.

2023-02-09 09:00 UTC, sever-sever commented
Why do we need a new node `default-registry` if we have a `registry`?

2023-02-09 12:57 UTC, Zen3515 commented
> Why do we need a new node `default-registry` if we have a `registry`?

@sever-sever 
By default we expect two default value which are `docker.io` and `quay.io`.
If we could set default configuration node to be

```json
"container": {
  "registry": {
    "docker.io": {},
    "quay.io": {}
  }
}
```

Then we won't need `default-registry`.

But, we can't define tree node as default value, can we?
The schema only allow `defaultValue` to be defined inside `leafNode` only, isn't it?

2023-02-10 06:30 UTC, Zen3515 commented
@c-po 
I've changed it according to your comment, but I have not created a PR yet.
I'd like to know first if I still need to create a smoke test for the authfile or not since I have switch to use only `podman login` command without `authfile`.

Since we didn't handle the file ourself, we need to deal with user `delete container registry`.
We could
1. Run `podman logout` when configuration changes/delete
2. Delete the file at default location everytime the configuration changes
3. Add the file to the hook

Which actions should we take?

2023-02-10 06:30 UTC, Zen3515 commented
@c-po 
I've changed it according to your comment, but I have not created a PR yet.
I'd like to know first if I still need to create a smoke test for the authfile or not since I have switch to use only `podman login` command without `authfile`.

Since we didn't handle the file ourself, we need to deal with user `delete container registry`.
We could
1. Run `podman logout` when configuration changes/delete
2. Delete the file at default location everytime the configuration changes
3. Add the file to the hook

Which action should we take?