T5013: Extend accelppp op-mode script to get statistic
vyos/vyos-1x pull request #1829
Opened 2023-02-18 09:43 UTC by sever-sever

## Change Summary

Extend accelppp.py op-mode script to get
subnet/start/stop/gateway/client_ip_pool/ etc
info from the configuration

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): Extend accelppp raw data

## Related Task(s)

* https://vyos.dev/T5013

## Component(s) name

## Proposed changes

## How to test
```
vyos@r14:~$ /usr/libexec/vyos/op_mode/accelppp.py show_statistics --protocol l2tp --raw
{
    "sessions": {
        "active": "0",
        "starting": "0"
    },
    "cpu": "0%",
    "config_option": {
        "authentication": {
            "mode": "local"
        },
        "client_ip_pool": {
            "subnet": [
                "100.64.45.0/24"
            ]
        }
    }
}
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-02-18 12:44 UTC, dmbaturin requested changes
>`"cpu": "0%",`

I believe we should reflect units in the field name, not in the value. With `10%`, if a client wants to display a progress bar, it needs to remove the percent sign from the string and convert the string to integer.

Something like `cpu_load_percentage: 10` is both descriptive and directly usable.

2023-02-18 12:48 UTC, sever-sever commented
> > `"cpu": "0%",`
> 
> I believe we should reflect units in the field name, not in the value. With `10%`, if a client wants to display a progress bar, it needs to remove the percent sign from the string and convert the string to integer.
> 
> Something like `cpu_load_percentage: 10` is both descriptive and directly usable.

It was there before, I just extended the dict with `config_option`
```
    "config_option": {
        "authentication": {
            "mode": "local"
        },
        "client_ip_pool": {
            "subnet": [
                "100.64.45.0/24"
            ]
        }
    }
```
I'll take a look

2023-02-18 13:40 UTC, sever-sever commented
> Something like `cpu_load_percentage: 10` is both descriptive and directly usable.

@dmbaturin Done!
```
vyos@r14# /usr/libexec/vyos/op_mode/accelppp.py show_statistics --protocol l2tp --raw
{
    "sessions": {
        "starting": "0",
        "active": "0"
    },
    "cpu_load_percentage": 0,
    "config_option": {
        "authentication": {
            "mode": "local"
        },
        "client_ip_pool": {
            "subnet": [
                "100.64.45.0/24"
            ]
        }
   
```

2023-02-18 18:43 UTC, c-po approved these changes

2023-02-23 14:47 UTC, dmbaturin approved these changes

2023-02-23 14:47 UTC, merged