T5055: Firewall: add packet-type matcher in firewall and route policy
vyos/vyos-1x pull request #1871
Opened 2023-03-06 18:40 UTC by nicolas-fort

## Change Summary

Add pkttype matcher in firewall and route policy

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5055

## Component(s) name

firewall
## Proposed changes

## How to test

Firewall
```
vyos@vyos# run show config comm | grep fire
set firewall interface eth0 in name 'FOO'
set firewall interface eth0 local name 'FOO'
set firewall name FOO default-action 'accept'
set firewall name FOO rule 10 action 'drop'
set firewall name FOO rule 10 source address '7.7.7.7'
set firewall name FOO rule 20 action 'accept'
set firewall name FOO rule 20 packet-type 'host'
set firewall name FOO rule 20 source address '8.8.8.8'
set firewall name FOO rule 40 action 'drop'
set firewall name FOO rule 40 packet-type 'multicast'
set firewall name FOO rule 40 source address '192.168.88.0/24'
set firewall name FOO rule 50 action 'accept'
set firewall name FOO rule 50 packet-type 'broadcast'
set firewall name FOO rule 50 protocol 'icmp'
[edit]
vyos@vyos# sudo nft -S list chain ip vyos_filter NAME_FOO
table ip vyos_filter {
        chain NAME_FOO {
                ip saddr 7.7.7.7 counter packets 0 bytes 0 drop comment "FOO-10"
                ip saddr 8.8.8.8 meta pkttype host counter packets 0 bytes 0 return comment "FOO-20"
                ip saddr 192.168.88.0/24 meta pkttype multicast counter packets 0 bytes 0 drop comment "FOO-40"
                meta l4proto icmp meta pkttype broadcast counter packets 0 bytes 0 return comment "FOO-50"
                counter packets 913 bytes 175118 return comment "FOO default-action accept"
        }
}
[edit]
```
Policy:
```
vyos@vyos# run show config comm | grep route6
set policy route6 FOO6 rule 10 action 'drop'
set policy route6 FOO6 rule 10 packet-type 'multicast'
set policy route6 FOO6 rule 20 action 'accept'
set policy route6 FOO6 rule 20 packet-type 'host'
set policy route6 FOO6 rule 30 action 'accept'
set policy route6 FOO6 rule 30 packet-type 'other'
[edit]
vyos@vyos# sudo nft -S list table ip6 vyos_mangle
table ip6 vyos_mangle {
        chain VYOS_PBR6_PREROUTING {
                type filter hook prerouting priority mangle; policy accept;
        }

        chain VYOS_PBR6_POSTROUTING {
                type filter hook postrouting priority mangle; policy accept;
        }

        chain VYOS_PBR6_FOO6 {
                meta pkttype multicast counter packets 0 bytes 0 drop comment "FOO6-10"
                meta pkttype host counter packets 0 bytes 0 return comment "FOO6-20"
                meta pkttype other counter packets 0 bytes 0 return comment "FOO6-30"
        }
}
[edit]

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-03-06 18:55 UTC, sever-sever requested changes

2023-03-06 18:55 UTC, sever-sever commented on interface-definitions/include/firewall/packet-options.xml.i
> +      <description>Match broadcast packet type </description>
Extra whitespace after `type`

2023-03-06 18:55 UTC, sever-sever commented on interface-definitions/include/firewall/packet-options.xml.i
> +      <description>Match multicast packet type </description>
Extra whitespace after `type`

2023-03-06 18:55 UTC, sever-sever commented on interface-definitions/include/firewall/packet-options.xml.i
> +      <description>Match host/unicast packet type, which are addressed to local host </description>
Extra whitespace after `host`
I suggest exclude slash "**/**" from description

2023-03-06 19:11 UTC, sarthurdev approved these changes

2023-03-06 19:16 UTC, sever-sever approved these changes

2023-03-10 20:22 UTC, c-po approved these changes

2023-03-10 20:22 UTC, merged