T5050: Firewall: Add log options
vyos/vyos-1x pull request #1889
Opened 2023-03-14 16:49 UTC by nicolas-fort

## Change Summary

Add log options for firewall

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5050

## Component(s) name

firewall

## Proposed changes

## How to test

```
vyos@LATEST# compare
[]
+ firewall {
+     name FOO {
+         rule 10 {
+             action "accept"
+             log "enable"
+             log-options {
+                 level "emerg"
+             }
+             protocol "icmp"
+         }
+         rule 20 {
+             action "reject"
+             log "enable"
+             log-options {
+                 group "12"
+                 queue-threshold "64000"
+                 snaplen "44"
+             }
+             source {
+                 address "195.51.100.1"
+             }
+         }
+     }
+ }

[edit]
vyos@LATEST# commit
[edit]
vyos@LATEST# sudo nft list chain ip vyos_filter NAME_FOO
table ip vyos_filter {
        chain NAME_FOO {
                meta l4proto icmp log prefix "[FOO-10-A]" log level emerg counter packets 0 bytes 0 return comment "FOO-10"
                ip saddr 195.51.100.1 log prefix "[FOO-20-R]" log group 12 snaplen 44 queue-threshold 64000 counter packets 0 bytes 0 reject comment "FOO-20"
                counter packets 0 bytes 0 drop comment "FOO default-action drop"
        }
}
[edit]
vyos@LATEST# 

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-03-16 07:05 UTC, c-po requested changes

2023-03-16 07:05 UTC, c-po commented on interface-definitions/include/firewall/rule-log-options.xml.i
> +        <help>Set log group. Log must be enable.</help>
I think we can skip this redundant string "Log must be enable", it dhould be displayed during `commit` if log was not configured.

2023-03-16 07:05 UTC, c-po commented on interface-definitions/include/firewall/rule-log-options.xml.i
> +          <format>u32:0-4294967295</format>
Having a packaged with length 4294967295 logged might cause a lot of trouble. I think we should limit this to 9000.

2023-03-16 07:05 UTC, c-po commented on interface-definitions/include/firewall/rule-log-options.xml.i
> +      </properties>
Please add a `<constraintErrorMessage>` indicating only `emerg alert crit err warn notice info debug` is supported

2023-03-16 20:18 UTC, c-po approved these changes

2023-03-16 20:30 UTC, sarthurdev approved these changes

2023-03-17 01:21 UTC, sever-sever commented on interface-definitions/include/firewall/rule-log-options.xml.i
> +    <leafNode name="snaplen">
Should it be “snapshot-length? Instead of “snaplen”?

2023-03-21 12:07 UTC, sever-sever approved these changes

2023-03-21 12:09 UTC, merged