T5158: Refactoring the commad sh interfaces counters
vyos/vyos-1x pull request #1956
Opened 2023-04-14 05:23 UTC by mkorobeinikov

## Change Summary
refactoring the sh interfaces counters command
## Types of changes
* [ ]  Bug fix (non-breaking change which fixes an issue)
* [x]  New feature (non-breaking change which adds functionality)
* [x]  Code style update (formatting, renaming)
* [ ]  Refactoring (no functional changes)
* [ ]  Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
* [ ]  Other (please describe):

## Related Task(s)
*https://phabricator.vyos.net/T5158

## Component(s) name
        src/op_mode/interfaces.py

## Proposed changes
## How to test
To check, needs to execute the command.
sh interfaces counters  and check drops and errors

## Checklist:
* [x]  I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
* [x]  I have linked this PR to one or more Phabricator Task(s)
* [ ]  I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
* [ ]  My commit headlines contain a valid Task id
* [ ]  My change requires a change to the documentation
* [ ]  I have updated the documentation accordingly

2023-04-14 06:18 UTC, c-po requested changes

2023-04-14 06:18 UTC, c-po commented on src/op_mode/interfaces.py
> +    print(formatting % ('Interface', 'Rx Packets', 'Rx Bytes', 'Tx Packets', 'Tx Bytes', 'Rx Dropped', 'Tx Dropped', 'Rx Errors', 'Tx Errors'))
This is python2 syntax - please use tabulate which is the preferred output method in the new op-mode scripts.

2023-05-01 22:57 UTC, dmbaturin requested changes
It looks all good other than that Python2 syntax that is unwieldy and harder to read compared to tabulate. Once you make that change, I'll be happy to merge it.

If you need any help with the tabulate library, let me know.

2023-05-08 04:15 UTC, mkorobeinikov commented
I've changed the syntax from python 2 to python 3 using "tabulate".

2023-05-08 06:24 UTC, sever-sever requested changes

2023-05-08 06:24 UTC, sever-sever commented on src/op_mode/interfaces.py
> +            Rx_Packets = entry.get('rx_bytes')
Variable names should be in lowercase
Also `Rx_packets` are defined 2 times

2023-05-08 06:24 UTC, sever-sever commented on src/op_mode/interfaces.py
> +            data_entries.append([Interface, Rx_Packets, Rx_Packets, Tx_Packets, Tx_Bytes, Rx_Dropped, Tx_Dropped, Rx_Errors, Tx_Errors])
`Rx_Packets` used two times
`Interface, Rx_Packets, Rx_Packets,`

2023-05-11 05:01 UTC, mkorobeinikov commented on src/op_mode/interfaces.py
> +            data_entries.append([Interface, Rx_Packets, Rx_Packets, Tx_Packets, Tx_Bytes, Rx_Dropped, Tx_Dropped, Rx_Errors, Tx_Errors])
Done

2023-05-11 06:01 UTC, c-po approved these changes

2023-05-11 06:14 UTC, sever-sever approved these changes

2023-05-11 07:23 UTC, merged