dns: T5144: Improve dynamic DNS validations and completions
vyos/vyos-1x pull request #1964
Opened 2023-04-21 06:15 UTC by indrajitr

Apply validations and completions to dynamic DNS protocols supported. This also opens up additional protocols supported by ddclient 3.10.

Additional details:
- Validation and constraint have been added for interface names as well.
- While at it, the help texts got some copyedit and rewording.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5144
* https://vyos.dev/T4428

## Component(s) name

dns dynamic

## Proposed changes

## How to test

This round of changes are internal only.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-04-21 12:19 UTC, sarthurdev approved these changes

2023-04-29 18:00 UTC, dmbaturin requested changes

2023-04-29 18:00 UTC, dmbaturin commented on interface-definitions/dns-dynamic.xml.in
> +                          <help>Login for Dynamic DNS service (not used by all protocols, or referred as api-token in some cases)</help>
I don't think we should use very long help strings. These strings don't really explain much — for example, if my service uses API tokens instead of login/password pairs, should I enter it as `login` or `password`? People should read the docs for those things.

2023-04-29 18:00 UTC, dmbaturin commented on interface-definitions/dns-dynamic.xml.in
> +                      <help>Use http(s) web request to obtain the external IP address instead of the IP address associated with the interface</help>
Protocol names, like HTTP, should be in all capitals.

2023-05-08 06:34 UTC, merged