BFD : T5161: add feature bfd static monitoring
vyos/vyos-1x pull request #1967
Opened 2023-04-21 18:20 UTC by fett0

FRR has introduced the ability to monitor a static route and remove it from RIB , When the BFD session is down it is removed from RIB and propagated , if it's is up the routes are installed :

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5161

## Component(s) name

bfd , static 

## Proposed changes

## How to test

BFD static monitoring works with profile  and  next-hop or multi-hop more profile : 
```
vyos-cli 

set protocols bfd profile static interval multiplier '3'
set protocols bfd profile static interval receive '300'
set protocols bfd profile static interval transmit '300'

set protocols bfd profile static_m interval multiplier '5'
set protocols bfd profile static_m interval receive '800'
set protocols bfd profile static_m interval transmit '800'

set protocols static route 10.10.13.3/32 next-hop 192.168.2.3 bfd profile 'static'

#multi-hop
set protocols static route 172.16.10.3/32 next-hop 192.168.10.1 bfd multi-hop source 192.168.2.1 profile 'static_m'

```

verifications : 

```

vyos@rt-1# run show bfd static routes
Showing BFD monitored static routes:

  Next hops:
    VRF default IPv4 Unicast:
        10.10.13.3/32 peer 192.168.2.3 (status: installed)
        172.16.10.3/32 peer 192.168.10.1 (status: installed)

    VRF default IPv4 Multicast:

vyos@rt-1# run show ip route
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
       f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup
       t - trapped, o - offload failure

S>* 10.10.13.3/32 [1/0] via 192.168.2.3, eth1, weight 1, 01:15:14
C>* 172.16.2.2/32 is directly connected, dum10, 01w0d04h
S>  172.16.10.3/32 [1/0] via 192.168.10.1 (recursive), weight 1, 00:15:05
  *                        via 192.168.2.3, eth1, weight 1, 00:15:05
C>* 192.168.2.0/24 is directly connected, eth1, 01w0d04h
S>* 192.168.10.0/24 [1/0] via 192.168.2.3, eth1, weight 1, 01w0d03h

```

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

2023-04-21 20:12 UTC, c-po requested changes
Thanks for the PR - this one only implements BFD for static IPv4 routes. Can you please extend this for IPv6, too?

2023-04-21 20:55 UTC, fett0 commented
Yes, of course. I will extend it.

2023-04-24 14:47 UTC, fett0 commented
done 
```
vyos@rt-vyo3:~$ show configuration commands  | match route6
set protocols static route6 2001:db8:150::1/128 next-hop 2001:db8:100::21 bfd profile 'static'
set protocols static route6 2001:db8:250::1/128 next-hop 2001:db8:100::21 bfd multi-hop source 2001:db8:100::250 profile 'static'

vyos@rt-vyo3:~$ sudo vtysh -c "show run"

frr version 8.5
frr defaults traditional
hostname rt-vyo3

!
ip route 0.0.0.0/0 172.16.50.1 eth0 tag 210 210
ip route 172.16.2.2/32 192.168.2.1 bfd profile static
ipv6 route 2001:db8:150::1/128 2001:db8:100::21 bfd profile static
ipv6 route 2001:db8:250::1/128 2001:db8:100::21 bfd multi-hop source 2001:db8:100::250 profile static

```

2023-04-27 16:17 UTC, c-po commented
I plan to do a local build/review of this this week

2023-04-29 06:19 UTC, c-po commented
`AssertionError: 'ip route 10.0.0.0/8 192.0.2.140 bfd multi-hop source 192.0.2.10profilevyos-test`

Your smoketests contain an error in writing. I will add a fix for this to the PR and also add the IPv6 testcase

2023-04-29 06:21 UTC, c-po approved these changes

2023-04-29 06:21 UTC, merged

2023-04-29 13:44 UTC, fett0 commented
thanks cris!! I will add this in our documenation