vrrp: T5215: fix the commit error when health check is not configured
vyos/vyos-1x pull request #1999
Opened 2023-05-11 16:18 UTC by dmbaturin

## Change Summary

The original version of this feature caused commit errors complaining about missing health-check ping/script option when health check wasn't configured at all.

The reason was that the `health_check` field is always present in the config dict because it has options with default values. Since we don't have a way to see if something is there only because of defaults, I made it a warning and allowed useless health-check configurations for now.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5215

## Component(s) name

VRRP

## How to test

Commit a VRRP configuration without health-check configured.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-05-11 16:40 UTC, sever-sever requested changes

2023-05-11 16:40 UTC, sever-sever commented on src/conf_mode/high-availability.py
> +                            f'until it has one of the following options: {health_check_options}')
`health_check_options` is not defined

2023-05-12 00:45 UTC, dmbaturin commented on src/conf_mode/high-availability.py
> +                            f'until it has one of the following options: {health_check_options}')
Wow, yes. Thanks for catching it. I made an edit on the test router but copied a chunk wrong into the repo, sorry.

2023-05-12 01:22 UTC, jestabro approved these changes

2023-05-12 01:34 UTC, merged