T775: Add service config-sync between 2 routers
vyos/vyos-1x pull request #2042
Opened 2023-06-14 13:50 UTC by sever-sever

set service config-sync primary address 192.0.2.14 set service config-sync primary key xxx
set service config-sync secondary address 192.0.2.11 set service config-sync secondary key xxx
set service config-sync section nat
set service config-sync section nat66
set service config-sync section firewall
set service config-sync mode load

## Change Summary

Service config-sync allows synchronizing a section of the configuration.
As PoC allows only nat, nat66, and firewall sections

The synchronization requires API and keys configuration
Retrieve the configuration for a section from the `primary` node and send this configuration to the section of the `secondary` node.

This feature adds a symlink from helper `vyos_config_sync.py` to `/config/scripts/commit/post-hooks.d` and config that is located in `/run/config_sync_conf.conf`
It will synchronize the config per any commit.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T775

## Component(s) name

config-sync
## Proposed changes

## How to test
1. Add HTTPS API configuration,
```
set service https api graphql authentication expiration '31536000'
set service https api graphql authentication type 'token'
set service https api graphql introspection
set service https api keys id KID key 'foo'
set service https api socket
set service https virtual-host vsrv listen-address '192.168.122.14'
```
2. Configure config-sync
```
set service config-sync mode 'load'
set service config-sync primary address '192.168.122.14'
set service config-sync primary key 'foo'
set service config-sync secondary address '192.168.122.11'
set service config-sync secondary key 'foo'
set service config-sync section 'nat'
```
3. Configure nat on the primary node
```
set nat source rule 100 description 'My-NAT-Rule'
set nat source rule 100 outbound-interface 'eth1'
set nat source rule 100 translation address 'masquerade'
set service config-sync section 'nat'

vyos@r14# commit
[ nat ]

INFO:vyos_config_sync:Config synchronization: Mode=load, Primary=192.168.122.14, Secondary=192.168.122.11
[edit]
vyos@r14# 
```
4. Check the configuration on the secondary node, expected the same for section "NAT"
```
vyos@r11# show nat
 source {
     rule 100 {
         description My-NAT-Rule
         outbound-interface eth1
         translation {
             address masquerade
         }
     }
 }
[edit]
vyos@r11# 

```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-06-15 17:29 UTC, jestabro commented
@sever-sever I added a check to load_section (PR https://github.com/vyos/vyos-1x/pull/2043) so that on sync after deleting a section, an empty path will not remain in the secondary config. On one hand, cosmetic, but on the other hand, not a true 'sync'. Fixed in PR.

2023-06-15 17:31 UTC, sever-sever commented
> @sever-sever I added a check to load_section (PR #2043) so that on sync after deleting a section, an empty path will not remain in the secondary config. On one hand, cosmetic, but on the other hand, not a true 'sync'. Fixed in PR.

Thanks @jestabro

2023-06-20 19:47 UTC, jestabro commented
Note (as discussed with @sever-sever), configuring the primary server via the http-api from a 3rd server would timeout when sync'ing, due to the bug here (https://vyos.dev/T5305), now fixed.

More generally, (also discussed), since the config-sync post-commit hook is always run on the primary server, there is no need to retrieve the config via an api request to itself; one could just get the config dict of the section. I'll leave it up to @sever-sever to decide what he thinks best, and approve.

2023-06-20 19:47 UTC, jestabro approved these changes

2023-06-20 20:00 UTC, dmbaturin requested changes
I've noticed a few minor things. The essence looks good to me. I only wonder how we should design the CLI to enable more granular sync path lists in the future.

2023-06-20 20:00 UTC, dmbaturin commented on interface-definitions/service-config-sync.xml.in
> +              <leafNode name="address">
I think we should add support for IPv6 and FQDN addresses — shouldn't be hard, or I'm missing anything?

2023-06-20 20:00 UTC, dmbaturin commented on interface-definitions/service-config-sync.xml.in
> +                <description>Load and replace configuartion setction</description>
Typo in "section" (if I'm nitpicking anyway ;)

2023-06-20 20:00 UTC, dmbaturin commented on interface-definitions/service-config-sync.xml.in
> +                <description>Load and replace configuartion setction</description>
And in "configuration", too.

2023-06-20 20:00 UTC, dmbaturin commented on interface-definitions/service-config-sync.xml.in
> +              <help>section_help</help>
Missing section help message.

2023-06-20 20:00 UTC, dmbaturin commented on src/helpers/vyos_config_sync.py
> +API_TIMEOUT = 60
I think this may be configurable. Maybe we should also add retries in the next iteration.

2023-06-29 12:52 UTC, sarthurdev commented
I wonder if the symlink should be created in a new hook directory under /run? So as not to alter the /config folder and ensure the symlink is transient.

Added here: https://github.com/vyos/vyatta-cfg/blob/current/scripts/vyos-user-postcommit-hooks.sh

2023-06-29 13:06 UTC, sever-sever commented on interface-definitions/service-config-sync.xml.in
> +              <leafNode name="address">
Done!

2023-06-29 13:07 UTC, sever-sever commented on interface-definitions/service-config-sync.xml.in
> +                <description>Load and replace configuartion setction</description>
Fixed! 
thanks

2023-06-29 13:07 UTC, sever-sever commented on interface-definitions/service-config-sync.xml.in
> +              <help>section_help</help>
Fixed!

2023-06-30 11:02 UTC, sever-sever commented on src/helpers/vyos_config_sync.py
> +API_TIMEOUT = 60
Timeout done!

2023-06-30 12:00 UTC, sever-sever commented
> I wonder if the symlink should be created in a new hook directory under /run? So as not to alter the /config folder and ensure the symlink is transient.
> 
> Added here: https://github.com/vyos/vyatta-cfg/blob/current/scripts/vyos-user-postcommit-hooks.sh

@sarthurdev Thanks for the idea! Done!

2023-07-03 19:08 UTC, c-po approved these changes

2023-07-06 07:48 UTC, sever-sever commented
It still depends on https://github.com/vyos/vyatta-cfg/pull/66

2023-07-07 00:44 UTC, merged