T5450: allow inverted matcher for interface and interface-group
vyos/vyos-1x pull request #2142
Opened 2023-08-09 14:32 UTC by nicolas-fort

## Change Summary

Allow inverted matcher for interface and interface-group

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5450

## Component(s) name

firewall

## Proposed changes

Allow inverted matcher for interface and interface-group
## How to test

```
vyos@HASH:~$ show config comm | grep firewall
set firewall group interface-group TEST-GROUP interface 'eth1'
set firewall group interface-group TEST-GROUP interface 'vtun*'
set firewall group interface-group TEST-GROUP interface 'bond0.55'
set firewall name FOO rule 10 action 'accept'
set firewall name FOO rule 10 inbound-interface interface-name 'l2tp*'
set firewall name FOO rule 10 outbound-interface interface-group 'TEST-GROUP'
set firewall name FOO rule 20 action 'drop'
set firewall name FOO rule 20 inbound-interface interface-name 'br13'
set firewall name FOO rule 20 outbound-interface interface-group '!TEST-GROUP'
vyos@HASH:~$ sudo nft list chain ip vyos_filter NAME_FOO
table ip vyos_filter {
        chain NAME_FOO {
                iifname "l2tp*" oifname @I_TEST-GROUP counter packets 0 bytes 0 return comment "FOO-10"
                iifname "br13" oifname != @I_TEST-GROUP counter packets 0 bytes 0 drop comment "FOO-20"
                counter packets 0 bytes 0 drop comment "FOO default-action drop"
        }
}

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-08-10 18:41 UTC, nicolas-fort commented
I'll add this fix to PR https://github.com/vyos/vyos-1x/pull/2016 ans close it once it's merged

2023-08-13 06:29 UTC, c-po commented
Can this be closed?

2023-08-14 10:13 UTC, nicolas-fort commented
> Can this be closed?

Not, need to work in it and resolve conflicts:
 I wasn't able to add this fix in other PR.

2023-08-23 05:42 UTC, c-po requested changes

2023-08-23 05:42 UTC, c-po commented on interface-definitions/include/firewall/match-interface.xml.i
> +    </valueHelp>
Any reason to not use something like:

```xml
    <valueHelp>
      <format>txt</format>
      <description>Interface-group name to match</description>
    </valueHelp>
    <valueHelp>
      <format>!txt</format>
      <description>Inverted interface-group name to not match/description>
    </valueHelp>
```

2023-08-23 05:42 UTC, c-po commented on interface-definitions/include/firewall/match-interface.xml.i
> -      #include <include/constraint/interface-name-with-wildcard.xml.i>
No constraint is a bad thing

2023-08-23 05:42 UTC, c-po commented on interface-definitions/include/firewall/match-interface.xml.i
>      <valueHelp>
Why not state the obvious explicitly?
```xml
    <valueHelp>
      <format>txt</format>
      <description>Interface name,</description>
    </valueHelp>
    <valueHelp>
      <format>txt*</format>
      <description>Interface name with wildcard</description>
    </valueHelp>
    <valueHelp>
      <format>!txt</format>
      <description>Interface name inverted (not match)</description>
    </valueHelp>
```

2023-08-23 15:29 UTC, c-po approved these changes

2023-08-23 16:19 UTC, merged