T5447: Initial support for MACsec static keys
vyos/vyos-1x pull request #2156
Opened 2023-08-18 00:59 UTC by giga1699

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5447

## Component(s) name

MACsec interfaces

## Proposed changes

This allows for defining static a static MACsec key, and associated MAC address, for environments where EAPOL doesn't work. Error checking that at least one peer is defined, and that each peer that isn't disabled have both a MAC and rx-key set.

## How to test

vyos-1x fork was compiled using the docker container for sagitta. The .deb file was copied over to a VM running 1.4 rolling (202308060317) [TEST VM]. A second un-patched VM was deployed on the same VLAN [CONTROL VM]. Testing old configuration using MKA was successful with patch between both VMs. Testing on new changes was then conducted as follows.

Configuration of [TEST VM]:
```
generate macsec mka cak gcm-aes-128 [NOTE: <key_00>]
generate macsec mka mak gcm-aes-128 [NOTE: Used for CONTROL VM <key_01>]
configure
set interfaces ethernet eth0
set interfaces ethernet eth1 address dhcp
set service ssh
commit
sudo su
dpkg -i --ignore-depends=zabbix-agent2 ./vyos-1x_0.0-no.git.tag_amd64.deb
exit
set interfaces macsec macsec0 address 192.168.1.1/30
set interfaces macsec macsec0 source-interface eth0
set interfaces macsec macsec0 security encrypt
set interfaces macsec macsec0 security cipher gcm-aes-128
set interfaces macsec macsec0 security static tx-key <key_00>
set interfaces macsec macsec0 security static peer MACSEC-02 mac <CONTROL VM MAC>
set interfaces macsec macsec0 security static peer MACSEC-02 rx-key <key_01>
commit
ping 192.168.1.2
```

Manual configuration of [CONTROL VM]
```
sudo su
ip link set up dev eth0
ip link add link eth0 macsec0 type macsec encrypt on
ip macsec add macsec0 tx sa 0 pn 1 on key 00 <key_01>
ip macsec add macsec0 rx port 1 address <TEST VM MAC>
ip macsec add macsec0 rx port 1 address <TEST VM MAC> sa 0 pn 1 on key 01 <key_00>
ip addr add 192.168.1.2/30 dev macsec0
ip link set up dev macsec0
ping 192.168.1.1
```

Pings were only successful after keys had been installed on both sides.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-08-18 08:36 UTC, sarthurdev commented
Does it correctly handle if keys/peers are changed/removed from an interface?

2023-08-18 08:46 UTC, giga1699 commented
> Does it correctly handle if keys/peers are changed/removed from an interface?

Yes, the interface seems to get rebuilt on every commit. Therefore, the interface would only contain the latest configuration settings.

```
vyos@vyos# ip macsec show
5: macsec0: protect on validate strict sc off sa off encrypt off send_sci on end_station off scb off replay off 
    cipher suite: GCM-AES-128, using ICV length 16
    TXSC: 82fbeec3c1c20001 on SA 0
        0: PN 10, state on, key 00000000000000000000000000000000
    RXSC: 0111223344550001, state on
        0: PN 1, state on, key 01000000000000000000000000000000
    RXSC: 0011223344550001, state on
        0: PN 1, state on, key 01000000000000000000000000000000
    offload: off 
[edit interfaces macsec macsec0 security static]
vyos@vyos# delete peer MAC
MACSEC-02  MACSEC-03  
[edit interfaces macsec macsec0 security static]
vyos@vyos# delete peer MACSEC-02 
[edit interfaces macsec macsec0 security static]
vyos@vyos# commit
[edit interfaces macsec macsec0 security static]
vyos@vyos# ip macsec show
6: macsec0: protect on validate strict sc off sa off encrypt off send_sci on end_station off scb off replay off 
    cipher suite: GCM-AES-128, using ICV length 16
    TXSC: 82fbeec3c1c20001 on SA 0
        0: PN 10, state on, key 00000000000000000000000000000000
    RXSC: 0111223344550001, state on
        0: PN 1, state on, key 01000000000000000000000000000000
    offload: off 
[edit interfaces macsec macsec0 security static]
vyos@vyos#
```

2023-08-18 09:06 UTC, giga1699 commented
With updated smoketest function, test_macsec_static_keys, output is as follows:

```
vyos@vyos:~$ /usr/libexec/vyos/tests/smoke/cli/test_interfaces_macsec.py
test_add_multiple_ip_addresses (__main__.MACsecInterfaceTest.test_add_multiple_ip_addresses) ... ok
test_add_single_ip_address (__main__.MACsecInterfaceTest.test_add_single_ip_address) ... ok
test_dhcp_disable_interface (__main__.MACsecInterfaceTest.test_dhcp_disable_interface) ... ok
test_dhcpv6_client_options (__main__.MACsecInterfaceTest.test_dhcpv6_client_options) ... ok
test_dhcpv6pd_auto_sla_id (__main__.MACsecInterfaceTest.test_dhcpv6pd_auto_sla_id) ... ok
test_dhcpv6pd_manual_sla_id (__main__.MACsecInterfaceTest.test_dhcpv6pd_manual_sla_id) ... ok
test_interface_description (__main__.MACsecInterfaceTest.test_interface_description) ... ok
test_interface_disable (__main__.MACsecInterfaceTest.test_interface_disable) ... ok
test_interface_ip_options (__main__.MACsecInterfaceTest.test_interface_ip_options) ... ok
test_interface_ipv6_options (__main__.MACsecInterfaceTest.test_interface_ipv6_options) ... ok
test_interface_mtu (__main__.MACsecInterfaceTest.test_interface_mtu) ... ok
test_ipv6_link_local_address (__main__.MACsecInterfaceTest.test_ipv6_link_local_address) ... ok
test_macsec_encryption (__main__.MACsecInterfaceTest.test_macsec_encryption) ... 
Missing mandatory MACsec security keys as encryption is enabled!


Missing mandatory MACsec security keys as encryption is enabled!


Missing mandatory MACsec security keys as encryption is enabled!


Missing mandatory MACsec security keys as encryption is enabled!


Missing mandatory MACsec security keys as encryption is enabled!


Missing mandatory MACsec security keys as encryption is enabled!

ok
test_macsec_gcm_aes_128 (__main__.MACsecInterfaceTest.test_macsec_gcm_aes_128) ... 
Physical source-interface required for interface "macsec1"


Cipher suite must be set for MACsec "macsec1"

ok
test_macsec_gcm_aes_256 (__main__.MACsecInterfaceTest.test_macsec_gcm_aes_256) ... 
Physical source-interface required for interface "macsec4"


Cipher suite must be set for MACsec "macsec4"

ok
test_macsec_source_interface (__main__.MACsecInterfaceTest.test_macsec_source_interface) ... 
Can not add interface "eth0" to bridge, it is the source-interface of
"macsec0"!


Invalid source-interface "eth0". Interface is already a member of bridge
"br200"!


Can not add interface "eth0" to bond, it is the source-interface of
"macsec0"!


Invalid source-interface "eth0". Interface is already a member of bond
"bond200"!


Can not add interface "eth1" to bridge, it is the source-interface of
"macsec1"!


Invalid source-interface "eth1". Interface is already a member of bridge
"br200"!


Can not add interface "eth1" to bond, it is the source-interface of
"macsec1"!


Invalid source-interface "eth1". Interface is already a member of bond
"bond200"!

ok
test_macsec_static_keys (__main__.MACsecInterfaceTest.test_macsec_static_keys) ... 
Physical source-interface required for interface "macsec5"


Cipher suite must be set for MACsec "macsec5"

ok
test_mtu_1200_no_ipv6_interface (__main__.MACsecInterfaceTest.test_mtu_1200_no_ipv6_interface) ... 
link-local IPv6 address will be configured on interface "macsec0", the
required minimum MTU is 1280!


link-local IPv6 address will be configured on interface "macsec1", the
required minimum MTU is 1280!

ok
test_span_mirror (__main__.MACsecInterfaceTest.test_span_mirror) ... skipped 'not supported'
test_vif_8021q_interfaces (__main__.MACsecInterfaceTest.test_vif_8021q_interfaces) ... skipped 'not supported'
test_vif_8021q_lower_up_down (__main__.MACsecInterfaceTest.test_vif_8021q_lower_up_down) ... skipped 'not supported'
test_vif_8021q_mtu_limits (__main__.MACsecInterfaceTest.test_vif_8021q_mtu_limits) ... skipped 'not supported'
test_vif_8021q_qos_change (__main__.MACsecInterfaceTest.test_vif_8021q_qos_change) ... skipped 'not supported'
test_vif_s_8021ad_vlan_interfaces (__main__.MACsecInterfaceTest.test_vif_s_8021ad_vlan_interfaces) ... skipped 'not supported'
test_vif_s_protocol_change (__main__.MACsecInterfaceTest.test_vif_s_protocol_change) ... skipped 'not supported'

----------------------------------------------------------------------
Ran 25 tests in 50.222s

OK (skipped=7)
```

2023-08-18 09:15 UTC, c-po commented
Thanks for this PR - it's a nice extension not not rely on rotating keys with wpa_supplicant. Review might take some time.

2023-08-20 13:59 UTC, c-po requested changes

2023-08-20 13:59 UTC, c-po commented on interface-definitions/interfaces-macsec.xml.in
> +                  <help>Assign static MACSec keys instead of using MKA</help>
I'd not reference MKA here. Just say: `Use static keys for MACsec`

2023-08-20 13:59 UTC, c-po commented on interface-definitions/interfaces-macsec.xml.in
> +                  <leafNode name="tx-key">
Please combine `rx-key` and `tx-key` to a common `key` node that can be reused:

Example:


```xml
<!-- include start from interface/macsec-key.xml.i -->
<leafNode name="key">
  <properties>
    <help>MACsec static key</help>
    <valueHelp>
      <format>txt</format>
      <description>16-byte (128-bit) hex-string (32 hex-digits) for gcm-aes-128 or 32-byte (256-bit) hex-string (64 hex-digits) for gcm-aes-256</description>
    </valueHelp>
    <constraint>
      <regex>[A-Fa-f0-9]{32}</regex>
      <regex>[A-Fa-f0-9]{64}</regex>
    </constraint>
  </properties>
</leafNode>
<!-- include end -->
```

2023-08-20 13:59 UTC, c-po commented on interface-definitions/interfaces-macsec.xml.in
> +                      <help>peer alias</help>
Please write: `MACsec peer name`

2023-08-20 13:59 UTC, c-po commented on interface-definitions/interfaces-macsec.xml.in
> +                      <constraintErrorMessage>peer alias too long (limit 100 characters)</constraintErrorMessage>
`MACsec peer name exceeds limit of 100 characters`

2023-08-20 13:59 UTC, c-po commented on python/vyos/ifconfig/macsec.py
> +            # Set admin state to up
The administrative state is set for all interfaces at this generic location: https://github.com/vyos/vyos-1x/blob/current/python/vyos/ifconfig/interface.py#L1641-L1649

Please keep this A/D as when using MKA

2023-08-20 13:59 UTC, c-po commented on src/conf_mode/interfaces-macsec.py
> +            if dict_search('security.cipher', macsec) == 'gcm-aes-128' and tx_len != 32:
Can we introduce a constant? 

```python
GCM_AES_128_LEN: int = 32
GCM_AES_256_LEN: int = 64
```

as this value is used several times.

2023-08-20 13:59 UTC, c-po commented on src/conf_mode/interfaces-macsec.py
> +    if dict_search('security.static', macsec) == None:
Please use positive logic:

```
if dict_search('security.mka.cak', macsec):
```

2023-08-20 13:59 UTC, c-po commented
Other then my minor change requests it looks good to me. Also tested this on 2 VyOS routers connected via a VMware vSwitch and worked (encrpted) as expected.

2023-08-20 14:51 UTC, giga1699 commented on interface-definitions/interfaces-macsec.xml.in
> +                  <leafNode name="tx-key">
I don't disagree with the ability for reuse, but does it make configuration potentially confusing to read? TX and RX keys need not match, and just reading config lines one may overlook where "key" is and place it in the wrong spot.

Admittedly, there's some opening here as well for multiple keys with time-based expiration that I would like to explore that I believe some of the cloud providers are doing. Reuse of the config syntax makes that much easier.

Not stuck on this change, just wanted to confirm with you all that you don't think it would lead to confusion when TX and RX keys aren't explicitly stated in the config lines.

2023-08-20 15:05 UTC, giga1699 commented
Thank you for taking the time to review, and the great feedback! I will implement, test, and push.

2023-08-20 15:48 UTC, giga1699 commented
Updates implemented. Tested using 3 VyOS routers on Proxmox 8.0.4 using VLAN aware Linux Bridge.

2023-08-20 19:06 UTC, c-po commented
> Does it correctly handle if keys/peers are changed/removed from an interface?

Yes, if anything under the `security` node changes, the interface is recreated.

https://github.com/vyos/vyos-1x/blob/ffb798b4678f3b1bd0a40cc42b1f0477470346dc/src/conf_mode/interfaces-macsec.py#L63-L64

2023-08-20 19:07 UTC, c-po commented on python/vyos/ifconfig/macsec.py
> +            # interface is always A/D down. It needs to be enabled explicitly
No need for the double `down` code path. Can you please change this to only one code path, so `down` is simply always executed?

2023-08-21 05:14 UTC, c-po approved these changes

2023-08-23 05:35 UTC, merged