T2958: Ability to start DHCP-server from LiveCD
vyos/vyos-1x pull request #2184
Opened 2023-08-29 10:06 UTC by sever-sever

## Change Summary

Ability to start DHCP-server from LiveCD
As we don't have `/config` directory in the LiveCD where leases are saved, use `/run` directory fo them.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T2958

## Component(s) name

dhcp-server
## Proposed changes

## How to test
Boot via LiveCD
```
set service dhcp-server shared-network-name NET authoritative
set service dhcp-server shared-network-name NET subnet 192.0.2.0/24 range RANG01 start 192.0.2.10
set service dhcp-server shared-network-name NET subnet 192.0.2.0/24 range RANG01 stop 192.0.2.130
set service dhcp-server shared-network-name NET subnet 192.0.2.0/24 default-router 192.0.2.1

```
Check leases in `/run` directory
```
vyos@vyos:~$ cat /run/dhcp-server/dhcpd.leases
# The format of this file is documented in the dhcpd.leases(5) manual page.
# This lease file was written by isc-dhcp-4.4.3-P1

# authoring-byte-order entry is generated, DO NOT DELETE
authoring-byte-order little-endian;

server-duid "\000\001\000\001,\200{6RT\000\311\275\205";

lease 192.0.2.10 {
  starts 2 2023/08/29 09:49:01;
  ends 3 2023/08/30 09:49:01;
  cltt 2 2023/08/29 09:49:01;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet 52:54:00:92:35:5d;
  set shared-networkname = "NET";
  client-hostname "r1";
}
lease 192.0.2.11 {
  starts 2 2023/08/29 09:55:09;
  ends 3 2023/08/30 09:55:09;
  cltt 2 2023/08/29 09:55:09;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet 52:54:00:04:33:2b;
  set shared-networkname = "NET";
  client-hostname "r14";
}

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-08-29 10:23 UTC, sever-sever commented
Or we can just create the “/config” directory

2023-08-29 11:03 UTC, sarthurdev approved these changes

2023-08-29 11:45 UTC, sarthurdev commented
> Or we can just create the “/config” directory

I suppose this would be best. No further proceessing needed in conf script. Though a warning might be needed to state the contents is not retained.

2023-08-29 16:51 UTC, dmbaturin requested changes
I like the dehardcoding of the file name, but I also disagree with adding a fixup. The live CD environment should not be different from the installed environment, we need to find out why /config is not created and create it.

2023-08-29 19:36 UTC, jestabro commented
I am looking into some related matters, regarding /config and live-boot; I'll add an update should it reveal anything useful ...

2023-08-30 09:40 UTC, sever-sever commented
Another solution https://github.com/vyos/vyos-build/pull/383

2023-08-31 15:45 UTC, c-po commented
I'm in favour of https://github.com/vyos/vyos-build/pull/383

2023-08-31 19:45 UTC, sarthurdev commented
With https://github.com/vyos/vyos-build/pull/383 merged, suppose this can be closed?

2023-08-31 20:14 UTC, sever-sever commented
> With [vyos/vyos-build#383](https://github.com/vyos/vyos-build/pull/383) merged, suppose this can be closed?

We agree to rewrite part of this and delete lease related configuration, other looks good.
Will do soon.

2023-09-05 05:23 UTC, c-po approved these changes

2023-09-05 05:23 UTC, merged

2023-09-05 08:41 UTC, sarthurdev commented
Will this cause any problems with the lease file no longer being persistent across reboots?

2023-09-05 08:49 UTC, sever-sever commented
> Will this cause any problems with the lease file no longer being persistent across reboots?

Sure, there should be `/config/dhcpd.leases`
It seems I deleted the wrong path variable for leases :)