smoketest: T5558: Extend configtest to allow checking of migration script results
vyos/vyos-1x pull request #2221
Opened 2023-09-07 19:36 UTC by sarthurdev

## Change Summary

- Extends config smoketest to check resulting migrated CLI nodes against a file of expected nodes
- Includes list of expected CLI nodes for tests `basic-vyos` and `dialup-router-medium-vpn`

Will add further configs/expected CLI for major migrated components (e.g. firewall/zone-policy) over time.

Note: As future migrations are added that change syntax, tests may need to be updated.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5558

## Component(s) name

smoketest

## Proposed changes

## How to test

Run `make testc`, after migration is loaded and committed, it will check config commands in the `config-tests` file (if present) against the effective config.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-09-07 19:55 UTC, dmbaturin requested changes

2023-09-07 19:55 UTC, dmbaturin commented on smoketest/bin/vyos-configtest
> +                    if not line or not line.startswith("set "): # Treat as comment
Maybe use explicit comment syntax with `#`?

2023-09-07 20:11 UTC, sarthurdev commented on smoketest/bin/vyos-configtest
> +                    if not line or not line.startswith("set "): # Treat as comment
Changed

2023-09-08 05:32 UTC, c-po approved these changes

2023-09-08 05:32 UTC, merged