openvpn: T4974: Fixes for OpenVPN DCO functionality
vyos/vyos-1x pull request #2248
Opened 2023-09-12 14:24 UTC by sarthurdev

## Change Summary

- Remove interface creation/deletion logic, OpenVPN service handles it (DCO does not work if interface is already created)
- Fix `enable-dco` typo
- Remove interface check in client smoketests - Interface is not created until connection established
- Update smoketest to verify DCO

Known issue: An instance running in client mode that fails to establish connection (most likely to occur on boot) will not create an interface. As result, any processing inside `VTunIf.update()` (description/VRF/etc.) will not be applied.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T4974

## Component(s) name

openvpn

## Proposed changes

## How to test

```
DEBUG - Running Testcase: /usr/libexec/vyos/tests/smoke/cli/test_interfaces_openvpn.py
DEBUG - test_openvpn_client_interfaces (__main__.TestInterfacesOpenVPN.test_openvpn_client_interfaces) ... ok
DEBUG - test_openvpn_client_verify (__main__.TestInterfacesOpenVPN.test_openvpn_client_verify) ... ok
DEBUG - test_openvpn_options (__main__.TestInterfacesOpenVPN.test_openvpn_options) ... ok
DEBUG - test_openvpn_server_net30_topology (__main__.TestInterfacesOpenVPN.test_openvpn_server_net30_topology) ... ok
DEBUG - test_openvpn_server_subnet_topology (__main__.TestInterfacesOpenVPN.test_openvpn_server_subnet_topology) ... ok
DEBUG - test_openvpn_server_verify (__main__.TestInterfacesOpenVPN.test_openvpn_server_verify) ... ok
DEBUG - test_openvpn_site2site_interfaces_tun (__main__.TestInterfacesOpenVPN.test_openvpn_site2site_interfaces_tun) ... ok
DEBUG - test_openvpn_site2site_verify (__main__.TestInterfacesOpenVPN.test_openvpn_site2site_verify) ... ok
DEBUG -
DEBUG - ----------------------------------------------------------------------
DEBUG - Ran 8 tests in 170.206s
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-09-12 18:13 UTC, c-po commented
Creating the interface in advance was a requirement to e.g. bind that interface to a bridge or a VRF. I think removing this locig will cause more harm then good.

2023-09-12 18:20 UTC, dmbaturin requested changes
I agree with @c-po . Scripts should never succeed if interfaces aren't actually created, since that will cause failures down the line in VRF, bridge, etc.

If there is no way to get OpenVPN to create an interface before the connection is established, we must do two things: 1) report that to OpenVPN maintainers 2) disallow adding OpenVPN interfaces to bridges and VRFs if DCO is enabled, until that issue is fixed.

2023-09-12 18:21 UTC, sarthurdev commented
I might have found a workaround to create the interface ahead of time when offloading, testing it now.

2023-09-13 09:16 UTC, sarthurdev commented
Going to close this until we can find a proper solution for creating/updating interface at commit.

2023-09-13 09:16 UTC, closed without merging