bonding: T5254: Fixed changing ethernet when it is a bond member
vyos/vyos-1x pull request #2277
Opened 2023-09-18 08:52 UTC by aapostoliuk

## Change Summary

If ethernet interface is a bond memeber:
  1. Allow for changing only specific parameters which are specified in EthernetIf.get_bond_member_allowed_options function.
  2. Added inheritable parameters from bond interface to ethernet interface which are scpecified in 
      BondIf.get_inherit_bond_options. 
      Users can change inheritable options under ethernet interface but in commit it will be copied from bond interface.
  4. All other parameters are denied for changing.

Added migration script. It deletes all denied parameters under ethernet interface if it is a bond member.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5254

## Component(s) name

bonding

## Proposed changes

If ethernet interface is a bond memeber:
  1. Allow for changing only specific parameters which are specified in EthernetIf.get_bond_member_allowed_options function.
  2. Added inheritable parameters from bond interface to ethernet interface which are scpecified in 
      BondIf.get_inherit_bond_options. 
      Users can change inheritable options under ethernet interface but in commit it will be copied from bond interface.
  4. All other parameters are denied for changing.

Added migration script. It deletes all denied parameters under ethernet interface if it is a bond member.

1. Adding interface with denied parameters to the bond interface
  Configuration:
  set interfaces ethernet eth1 vif 10
  Commands
vyos@vyos# set interfaces bonding bond1 member interface eth1
[edit]
vyos@vyos# commit

Can not add interface "eth1" to bond, it has a "vif 10" assigned!

[[interfaces bonding bond1]] failed
Commit failed
2. Adding interface with inheritable parameters to the bond interface
Configuration:
```
set interfaces bonding bond1 mtu '5000'
set interfaces ethernet eth1 mtu '2000'
```
Commands
```
vyos@vyos# set interfaces bonding bond1 member interface eth1
[edit]
vyos@vyos# commit
[edit]
vyos@vyos# sudo ip link
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 5000 qdisc fq master bond1 state DOWN mode DEFAULT group default qlen 1000
    link/ether 0c:ba:0b:5b:00:01 brd ff:ff:ff:ff:ff:ff
8: bond1: <NO-CARRIER,BROADCAST,MULTICAST,MASTER,UP> mtu 5000 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 0c:ba:0b:5b:00:01 brd ff:ff:ff:ff:ff:ff
[edit]
```
3. Changing denied parameters under ethernet interface
Configuration
`set interfaces bonding bond1 member interface 'eth1'`
Commands
```
vyos@vyos# set interfaces ethernet eth1 vif 10
[edit]
vyos@vyos# commit

Cannot configure "vif 10" on interface "eth1". Interface is a bond
member

[[interfaces ethernet eth1]] failed
Commit failed
[edit]
```
4.Changing inheritable parameters under ethernet interface
Configuration:
```
set interfaces bonding bond1 member interface 'eth1'
set interfaces bonding bond1 mtu '5000'
set interfaces ethernet eth1 mtu '2000'
```
Commands:
```
vyos@vyos# set interfaces ethernet eth1 mtu 9000
[edit]
vyos@vyos# commit

WARNING: Cannot apply "mtu" to "9000". Interface "eth1" is a bond
member. Option is inherited from bond "bond1"

[edit]
vyos@vyos# ip link
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 5000 qdisc fq master bond1 state DOWN mode DEFAULT group default qlen 1000
    link/ether 0c:ba:0b:5b:00:01 brd ff:ff:ff:ff:ff:ff
8: bond1: <NO-CARRIER,BROADCAST,MULTICAST,MASTER,UP> mtu 5000 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 0c:ba:0b:5b:00:01 brd ff:ff:ff:ff:ff:ff
```

5. Removing the interface ethernet from the bond interface
Configuration:
```
set interfaces bonding bond1 member interface 'eth1'
set interfaces bonding bond1 mtu '5000'
set interfaces ethernet eth1 mtu '9000'
```
Commands
```
vyos@vyos# delete interfaces bonding bond1 member interface eth1
[edit]
vyos@vyos# commit
[edit]
vyos@vyos# ip link
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9000 qdisc fq state DOWN mode DEFAULT group default qlen 1000
    link/ether 0c:ba:0b:5b:00:01 brd ff:ff:ff:ff:ff:ff
8: bond1: <NO-CARRIER,BROADCAST,MULTICAST,MASTER,UP> mtu 5000 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether da:02:ee:d4:35:1d brd ff:ff:ff:ff:ff:ff
[edit]
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-09-22 15:25 UTC, jestabro commented
Note one minor issue that shows up as I'm testing this:
https://github.com/aapostoliuk/vyos-1x/blob/T5254-1-sagitta/src/migration-scripts/interfaces/30-to-31#L38
will fail on an initial boot, since the low-level ConfigTree.list_nodes fails on non-existence of path. This is avoided in migration scripts by existing early if bas path doesn't exist, for example:
https://github.com/aapostoliuk/vyos-1x/blob/T5254-1-sagitta/src/migration-scripts/interfaces/29-to-30#L34-L36

2023-09-24 23:54 UTC, jestabro requested changes
Cf. comment above.

2023-09-25 12:35 UTC, aapostoliuk commented
> Cf. comment above.

Done

2023-10-02 14:28 UTC, jestabro commented on src/conf_mode/interfaces-bonding.py
> +    os.environ['vyos_validators_dir'] = '/usr/libexec/vyos/validators'
Why is this needed ?

2023-10-02 14:29 UTC, jestabro commented on src/migration-scripts/interfaces/30-to-31
> +ethernet_commands_config = []
Unused.

2023-10-02 14:30 UTC, jestabro approved these changes

2023-10-03 06:58 UTC, aapostoliuk commented on src/conf_mode/interfaces-bonding.py
> +    os.environ['vyos_validators_dir'] = '/usr/libexec/vyos/validators'
These lines are unused. I deleted them.

2023-10-03 06:59 UTC, aapostoliuk commented on src/migration-scripts/interfaces/30-to-31
> +ethernet_commands_config = []
Done

2023-10-09 07:56 UTC, sever-sever approved these changes

2023-10-12 14:34 UTC, dmbaturin approved these changes

2023-10-12 14:35 UTC, merged

2023-10-22 16:46 UTC, c-po commented
@MergifyIo backport sagitta