ddclient: T5612: Miscellaneous improvements and fixes for dynamic DNS
vyos/vyos-1x pull request #2303
Opened 2023-09-22 21:37 UTC by indrajitr

## Change Summary

- Fix VRF support for ddclient service
- Improve dual stack support for dyndns2 protocol
- Generate more reliable ddclient config
- Refactor zone configuration
- Enable TTL support for web-service based protocols
- Adjust validator and completion for ddclient
- Additional cleanup and refactoring for ddclient scripts

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5612

## Related PR(s)

## Component(s) name

dns dynamic

## Proposed changes

## How to test

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-09-23 09:13 UTC, c-po requested changes
VRF support is a very nice addition, but it will only work with one VRF due to the current design (only one global ddclient process) - still better then nothing.

Can you please extend the smoketests to also verify the VRF case and check if ddclient process runs in the VRF it was assigned too?

2023-09-24 01:26 UTC, indrajitr commented
@c-po Thank you for the review!
> VRF support is a very nice addition, but it will only work with one VRF due to the current design (only one global ddclient process) - still better then nothing.

Yes, maybe we can consider templated service at some point.

> Can you please extend the smoketests to also verify the VRF case and check if ddclient process runs in the VRF it was assigned too?

Have updated and expanded smoketests. They cover VRF now.

2023-09-24 05:48 UTC, c-po approved these changes

2023-09-30 06:33 UTC, merged

2023-11-23 07:20 UTC, sever-sever commented
@MergifyIo backport sagitta