conntrack: T5376: T5598: Restore kernel conntrack helpers
vyos/vyos-1x pull request #2304
Opened 2023-09-24 11:42 UTC by sarthurdev

## Change Summary

- Fixes kernel helpers, `nf_conntrack_helper` sysctl used to enable conntrack helpers automatically. This was removed in the kernel and rules now need to be created.
- Update conntrack script to use `vyos.configdep` to update conntrack-sync
- Remove obsolete firewall zone-policy op-mode

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5376
* https://vyos.dev/T5598
* https://vyos.dev/T5160

## Related PR(s)

## Component(s) name

conntrack, firewall

## Proposed changes

- Creates rules for enabled helpers on default protocol/ports of each module
- Use helper template macro for ipv4/ipv6 conntrack tables
- Update smoketests to validate modules and nftables rules are present
- Speed up conf script execution by loading/unloading modules in a single call to modprobe/rmmod
- Call conntrack-sync conf script only when node is defined, and using `vyos.configdep`
- Remove obsolete firewall zone-policy op-mode script

## How to test

Tested FTP helper with passive FTP server and traffic was correctly marked as related.

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-09-24 15:51 UTC, c-po approved these changes

2023-09-24 15:53 UTC, dmbaturin requested changes
Why is removal of zone policy op mode mixed with changes unrelated to it?

2023-09-24 15:58 UTC, sarthurdev commented
Christian has always suggested to bundle commits into a single PR. 

I figured it was minor enough change not to warrant its own PR.

2023-09-24 16:00 UTC, dmbaturin commented
I'm categorically against bundling completely unrelated changes in one PR.

2023-09-28 14:51 UTC, jestabro approved these changes

2023-09-28 14:54 UTC, merged