openvpn: T5634: Remove support for insecure DES and Blowfish ciphers
vyos/vyos-1x pull request #2353
Opened 2023-10-09 16:54 UTC by dmbaturin

## Change Summary

Remove DES and Blowfish ciphers from OpenVPN configs if they are set explicitly to allow removal of the legacy crypto provider. Configs with those options unset allow clients to negotiate any of the support ciphers.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): Legacy functionality removal

## Related Task(s)

* https://vyos.dev/T5634

## Component(s) name

OpenVPN.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-10-09 17:24 UTC, sever-sever requested changes

2023-10-09 17:24 UTC, sever-sever commented on src/migration-scripts/openvpn/0-to-1
> +            print(ncp_ciphers)
Print is not required

2023-10-09 17:28 UTC, dmbaturin commented on src/migration-scripts/openvpn/0-to-1
> +            print(ncp_ciphers)
Good point, that's a stray debug print. Removed.

2023-10-09 18:08 UTC, sever-sever approved these changes

2023-10-09 22:19 UTC, sarthurdev approved these changes

2023-10-10 04:15 UTC, c-po requested changes
Please also create a mew component version file for OpenVPN here: https://github.com/vyos/vyos-1x/tree/current/interface-definitions/include/version

2023-10-10 18:09 UTC, dmbaturin commented
> Please also create a mew component version file for OpenVPN here: https://github.com/vyos/vyos-1x/tree/current/interface-definitions/include/version

Damn, the file didn't get included in the commit. I've fixed it now.

2023-10-12 00:43 UTC, jestabro approved these changes

2023-10-12 00:43 UTC, merged