T5714: op-cmd: Fix for "show log vpn ipsec/all"
vyos/vyos-1x pull request #2442
Opened 2023-11-06 16:07 UTC by srividya0208

## Change Summary

No results shown for this command "show log vpn ipsec" . Now changed to journalctl to view logs

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5714

## Related PR(s)

## Component(s) name

ipsec
## Proposed changes

change the command from this:
`cat $(printf "%s\n" /var/log/messages* | sort -nr) | grep -e charon`
to
`journalctl --no-hostname -b /usr/lib/ipsec/charon | tee`
## How to test

Run this command to check the logs:
`show log vpn ipsec`

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-11-06 20:34 UTC, c-po requested changes

2023-11-06 20:34 UTC, c-po commented on op-mode-definitions/show-log.xml.in
> +                <command>journalctl --no-hostname  -b | sort -nr | grep -e charon -e accel -e pptpd -e ppp</command>
Stray whitespace after hostname

2023-11-08 10:04 UTC, srividya0208 commented on op-mode-definitions/show-log.xml.in
> +                <command>journalctl --no-hostname  -b | sort -nr | grep -e charon -e accel -e pptpd -e ppp</command>
removed

2023-11-08 18:53 UTC, c-po approved these changes

2023-11-16 15:25 UTC, c-po commented on op-mode-definitions/show-log.xml.in
> +                <command>journalctl --no-hostname -b /usr/lib/ipsec/charon | tee</command>
Why do we need `tee` here if we do not write to a file?

2023-12-02 22:54 UTC, dmbaturin approved these changes

2023-12-02 22:54 UTC, merged