T5778: dhcp server: fix op-mode command
vyos/vyos-1x pull request #2551
Opened 2023-11-28 16:50 UTC by nicolas-fort

## Change Summary

Fix op-mode command `show ip dhcp server leases`
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5778

## Related PR(s)

## Component(s) name

dhcp server
## Proposed changes

Before this change:

- `show dhcp server leases state all`: did not work
- `show dhcp server leases pool <pool_name>`: did not apply filter based by pool.
- No leases printed when fail-over is used and IP was granted by remote dhcp-server.

Note: If an active lease is found while parsing dhcp lease file, and pool=='', then it means is an active lease granted by remote Server. Adding such information in "Pool" column so it's visible for the user.

## How to test

One server, multiple pools:
```
# Config:
vyos@SECONDARY:~$ show config comm | grep dhcp
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 default-router '192.168.11.1'
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 domain-name 'vyos.net'
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 name-server '192.168.11.1'
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 range 0 start '192.168.11.20'
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 range 0 stop '192.168.11.250'
set service dhcp-server shared-network-name VIF-1001 subnet 10.11.11.0/24 default-router '10.11.11.1'
set service dhcp-server shared-network-name VIF-1001 subnet 10.11.11.0/24 name-server '1.1.1.1'
set service dhcp-server shared-network-name VIF-1001 subnet 10.11.11.0/24 range 0 start '10.11.11.101'
set service dhcp-server shared-network-name VIF-1001 subnet 10.11.11.0/24 range 0 stop '10.11.11.120'
vyos@SECONDARY:~$ 
vyos@SECONDARY:~$ show dhcp server leases 
Single pool:  LAN
Single pool:  VIF-1001
IP Address     MAC address        State    Lease start          Lease expiration     Remaining    Pool      Hostname
-------------  -----------------  -------  -------------------  -------------------  -----------  --------  ----------
192.168.11.20  00:50:79:66:68:09  active   2023/11/28 14:35:52  2023/11/29 14:35:52  22:09:18     LAN       VPCS1
192.168.11.21  50:00:00:05:00:00  active   2023/11/28 14:36:19  2023/11/29 14:36:19  22:09:45     LAN       VYOS5
192.168.11.22  50:00:00:06:00:00  active   2023/11/28 16:26:17  2023/11/29 16:26:17  23:59:43     LAN       VYOS-6
10.11.11.101   50:00:00:05:00:00  active   2023/11/28 14:36:19  2023/11/29 14:36:19  22:09:45     VIF-1001  VYOS5
10.11.11.102   50:00:00:06:00:00  active   2023/11/28 16:26:17  2023/11/29 16:26:17  23:59:43     VIF-1001  VYOS-6

vyos@SECONDARY:~$ show dhcp server leases pool LAN 
IP Address     MAC address        State    Lease start          Lease expiration     Remaining    Pool    Hostname
-------------  -----------------  -------  -------------------  -------------------  -----------  ------  ----------
192.168.11.20  00:50:79:66:68:09  active   2023/11/28 14:35:52  2023/11/29 14:35:52  22:07:31     LAN     VPCS1
192.168.11.21  50:00:00:05:00:00  active   2023/11/28 14:36:19  2023/11/29 14:36:19  22:07:58     LAN     VYOS5
192.168.11.22  50:00:00:06:00:00  active   2023/11/28 16:26:17  2023/11/29 16:26:17  23:57:56     LAN     VYOS-6
vyos@SECONDARY:~$ show dhcp server leases pool VIF-1001 
IP Address    MAC address        State    Lease start          Lease expiration     Remaining    Pool      Hostname
------------  -----------------  -------  -------------------  -------------------  -----------  --------  ----------
10.11.11.101  50:00:00:05:00:00  active   2023/11/28 14:36:19  2023/11/29 14:36:19  22:07:55     VIF-1001  VYOS5
10.11.11.102  50:00:00:06:00:00  active   2023/11/28 16:26:17  2023/11/29 16:26:17  23:57:53     VIF-1001  VYOS-6
vyos@SECONDARY:~$ 
```

Two servers, with fail-over configuration:
```
vyos@SECONDARY:~$ show config comm | grep dhcp
set service dhcp-server failover name 'FOOBAR'
set service dhcp-server failover remote '192.168.11.11'
set service dhcp-server failover source-address '192.168.11.12'
set service dhcp-server failover status 'secondary'
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 default-router '192.168.11.1'
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 domain-name 'vyos.net'
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 enable-failover
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 name-server '192.168.11.1'
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 range 0 start '192.168.11.20'
set service dhcp-server shared-network-name LAN subnet 192.168.11.0/24 range 0 stop '192.168.11.250'
set service dhcp-server shared-network-name VIF-1001 subnet 10.11.11.0/24 default-router '10.11.11.1'
set service dhcp-server shared-network-name VIF-1001 subnet 10.11.11.0/24 enable-failover
set service dhcp-server shared-network-name VIF-1001 subnet 10.11.11.0/24 name-server '1.1.1.1'
set service dhcp-server shared-network-name VIF-1001 subnet 10.11.11.0/24 range 0 start '10.11.11.101'
set service dhcp-server shared-network-name VIF-1001 subnet 10.11.11.0/24 range 0 stop '10.11.11.120'

vyos@SECONDARY:~$ show dhcp server leases 
IP Address      MAC address        State    Lease start          Lease expiration     Remaining    Pool              Hostname
--------------  -----------------  -------  -------------------  -------------------  -----------  ----------------  ----------
192.168.11.134  00:50:79:66:68:09  active   2023/11/28 16:36:01  2023/11/28 17:06:01  0:27:00      LAN               VPCS1
192.168.11.133  50:00:00:06:00:00  active   2023/11/28 16:36:30  2023/11/28 17:06:30  0:27:29      LAN               VYOS-6
192.168.11.132  50:00:00:05:00:00  active   2023/11/28 16:36:32  2023/11/28 17:06:32  0:27:31      LAN               VYOS5
10.11.11.110    50:00:00:06:00:00  active   2023/11/28 16:36:31  2023/11/28 17:06:31  0:27:30      VIF-1001          VYOS-6
10.11.11.109    50:00:00:05:00:00  active   2023/11/28 16:36:33  2023/11/28 17:06:33  0:27:32      VIF-1001          VYOS5
10.11.11.108    00:50:79:66:68:08  active   2023/11/28 16:36:40  2023/11/28 17:06:40  0:27:39      VIF-1001          VPCS1
192.168.11.135  00:50:79:66:68:07  active   2023/11/28 16:38:29  2023/11/28 16:42:29  0:03:28      Fail-Over Server
vyos@SECONDARY:~$ 

vyos@PRIMARY:~$ show dhcp server leases
IP Address      MAC address        State    Lease start          Lease expiration     Remaining    Pool              Hostname
--------------  -----------------  -------  -------------------  -------------------  -----------  ----------------  ----------
192.168.11.135  00:50:79:66:68:07  active   2023/11/28 16:36:24  2023/11/28 16:40:24  0:02:40      LAN               VPCS1
192.168.11.134  00:50:79:66:68:09  active   2023/11/28 16:36:01  2023/11/28 17:06:01  0:28:17      Fail-Over Server
192.168.11.133  50:00:00:06:00:00  active   2023/11/28 16:36:30  2023/11/28 17:06:30  0:28:46      Fail-Over Server
10.11.11.110    50:00:00:06:00:00  active   2023/11/28 16:36:31  2023/11/28 17:06:31  0:28:47      Fail-Over Server
192.168.11.132  50:00:00:05:00:00  active   2023/11/28 16:36:32  2023/11/28 17:06:32  0:28:48      Fail-Over Server
10.11.11.109    50:00:00:05:00:00  active   2023/11/28 16:36:33  2023/11/28 17:06:33  0:28:49      Fail-Over Server
10.11.11.108    00:50:79:66:68:08  active   2023/11/28 16:36:40  2023/11/28 17:06:40  0:28:56      Fail-Over Server
vyos@PRIMARY:~$ 
```

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
-  [...]

2023-11-28 17:13 UTC, sever-sever commented
You don't really have a pool name `Fail-Over Server` it can confuse the users, especially those who get info about pools  via API 
On the other hand, it is helpful information where you get the lease (master/backup).

2023-11-29 19:27 UTC, sever-sever requested changes

2023-11-29 19:27 UTC, sever-sever commented on op-mode-definitions/dhcp.xml.in
> +                      <help>Show DHCP server leases granted by local or remote dhcp server</help>
DHCP should be in uppercase

2023-11-29 20:06 UTC, sever-sever commented on src/op_mode/dhcp.py
> +                                data.append(data_lease)
Could be simplified to
```
            if not aux or (aux and data_lease['pool'] == pool_name):
                data.append(data_lease)
```

2023-12-07 15:53 UTC, dmbaturin approved these changes

2023-12-07 15:53 UTC, merged

2023-12-07 15:54 UTC, dmbaturin commented
@mergifyio backport sagitta