https: T5772: Move API key check to http-api.py
vyos/vyos-1x pull request #2571
Opened 2023-12-04 15:54 UTC by dmbaturin

## Change Summary

Move the check to http-api.py because https.py is attached to the top level node and the current commit algorithm doesn't run `end:` of the parent when child nodes change.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5772
* 
## Component(s) name

HTTPS API

## How to test

Commit a valid HTTPS API config, then delete all keys — commit should fail.

## Smoketest result

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-12-04 18:34 UTC, sever-sever requested changes
```
vyos@r12# set service https api keys id KID
[edit]
vyos@r12# commit
[ service https api ]
Traceback (most recent call last):
  File "/usr/libexec/vyos/conf_mode/http-api.py", line 106, in <module>
    c = get_config()
  File "/usr/libexec/vyos/conf_mode/http-api.py", line 63, in get_config
    raise ConfigError('Missing HTTPS API key string for key id "}"'.format(name))
ValueError: Single '}' encountered in format string

[[service https api]] failed
Commit failed
[edit]
vyos@r12# 

```

2023-12-04 18:48 UTC, dmbaturin commented
@sever-sever Sorry, careless copying on my side, I've just pushed a fix.

2023-12-04 20:33 UTC, jestabro approved these changes

2023-12-05 07:21 UTC, c-po approved these changes

2023-12-05 07:22 UTC, c-po commented
```
cpo@LR3.wue3# curl -k -Fkey="qwerty" -Fdata='{"op": "showConfig", "path": ["interfaces"]}' https://localhost/retrieve
{"error": "Start service in configuration mode: set service https api"}[edit]
```
```
cpo@LR3.wue3# set service https api
cpo@LR3.wue3# commit
[ service https api ]
At least one HTTPS API key is required

[[service https api]] failed
Commit failed
```
```
cpo@LR3.wue3# set service https api keys first

  Configuration path: service https api keys [first] is not valid
  Set failed

cpo@LR3.wue3# set service https api keys id first
cpo@LR3.wue3# commit
[ service https api ]
Missing HTTPS API key string for key id "first"

[[service https api]] failed
Commit failed
```
```
cpo@LR3.wue3# set service https api keys id first key second
cpo@LR3.wue3# commit
cpo@LR3.wue3# curl -k -Fkey="second" -Fdata='{"op": "showConfig", "path": ["interfaces"]}' https://localhost/retrieve
{"success": true, "error": null, "data": {"dummy": {"dum0": {"address": "172.18.254.203/32"}}, "ethernet": {"eth0": {"vif": {"203": {"ip": {"ospf": {"transmit-delay": "1", "authentication": {"md5": {"key-id": {"10": {"md5-key": "ospfmybllnet"}}}}, "hello-interval": "10", "dead-interval": "40", "retransmit-interval": "5", "priority": "1"}}, "address": "172.18.203.10/24"}}, "duplex": "auto", "speed": "auto", "hw-id": "00:50:56:9d:a6:11", "smp-affinity": "auto"}, "eth1": {"smp-affinity": "auto", "disable": {}, "speed": "auto", "duplex": "auto", "hw-id": "00:50:56:b3:09:07"}}}}[edit]
```
```
cpo@LR3.wue3# delete service https api keys
cpo@LR3.wue3# commit
[ service https api ]
At least one HTTPS API key is required

[[service https api]] failed
Commit failed
[edit]
```
```
cpo@LR3.wue3# delete service https api
cpo@LR3.wue3# commit
```

2023-12-05 10:35 UTC, sever-sever approved these changes

2023-12-05 10:35 UTC, merged