T5870: ipsec remote access VPN: add x509 ("pubkey") authentication.
vyos/vyos-1x pull request #2707
Opened 2023-12-29 06:40 UTC by lucasec

## Change Summary

Currently we support several variants of EAP for ipsec remote access client authentication, but we should also support standard ipsec mutual x509 authentication. This is authentication mode "pubkey" in the strongswan config and functions in practice similarly to EAP-TLS, just without the extra EAP exchange.

This PR adds an `x509` option to `authentication client-mode` that configures strongswan to use standard mutual x509 authentication.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5870

## Related PR(s)

N/A

## Component(s) name

ipsec remote-access

## Proposed changes

Adds an `x509` option to `authentication client-mode` that configures strongswan to use standard mutual x509 authentication (`pubkey` mode).

## How to test

## Smoketest result

Example configuration:
```
[edit vpn ipsec remote-access connection ClientVPN]
lucas@lcn-router# show
 authentication {
     client-mode x509
     local-id <local id>
     server-mode x509
     x509 {
         ca-certificate <ca certificate name>
         certificate <server certificate name>
     }
 }
 local-address <router IP address>
 esp-group ClientVPN-Client
 ike-group ClientVPN-Client
 pool Client-Pool-v4
 pool Client-Pool-v6
```

Validate that `/etc/swanctl/swanctl.conf` specifies `auth = pubkey` under `remote`.
End-to-end behavior was tested using a properly configured iOS client (using `ExtendedAuthEnabled = 0` and `AuthenticationMode = Certificate`).

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2023-12-29 06:44 UTC, c-po commented
Thank you for the contribution.
Please extend the smoketests for IPsec to also cover for this new feature. In addition plaes add smoketest result to this PR

2023-12-29 06:57 UTC, lucasec commented
@c-po Will do. I have a few more PRs on the back-burner so may open a few more before I go back and add smoke tests in. Also will need to follow up with documentation PR I believe.

2023-12-29 22:37 UTC, lucasec commented
As far as I can tell, there is currently no smoketests at all for ipsec remote access, so this could be an involved effort. Should I try to create a new test suite from scratch as part of this PR or better to file another ticket to build out tests for this branch of functionality?

2023-12-30 09:57 UTC, sever-sever commented
> As far as I can tell, there is currently no smoketests at all for ipsec remote access, so this could be an involved effort. Should I try to create a new test suite from scratch as part of this PR or better to file another ticket to build out tests for this branch of functionality?

You can add a smoketest as part of this PR

2023-12-30 11:02 UTC, c-po commented
Initial remote-access VPN smoketests will be added in 

* https://github.com/vyos/vyos-1x/pull/2722

Please extend them with your new features after they got merged

2023-12-30 20:00 UTC, lucasec commented
Added two new smoketest scenarios for `eap-tls` auth and the new `x509` auth introduced by this PR.
I opted to add these as separate test cases as that seemed more convenient to extend in future PRs, but could re-factor if it would be preferable to have these just as another config commit at the end of `test_07_ikev2_road_warrior` and a few delta checks on the rendered config file.

2023-12-30 20:41 UTC, sever-sever requested changes
Could you use the world “ IPsec” as it used in the other places of this XML

2023-12-30 20:44 UTC, lucasec commented
@sever-sever Updated to address

2023-12-30 20:53 UTC, sever-sever approved these changes

2023-12-30 21:57 UTC, c-po approved these changes

2023-12-30 21:57 UTC, merged

2023-12-30 21:57 UTC, c-po commented
@MergifyIo backport sagitta