op-mode: T5884: Correction of description for generate-wireguard.xml.in
vyos/vyos-1x pull request #2735
Opened 2024-01-01 19:33 UTC by hwlnx

## Change Summary

Correct the 'generate wireguard' command help string

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): Wrong description (probably from copy-paste)

## Related Task(s)

* https://vyos.dev/T5884

## Related PR(s)

## Component(s) name

OP-Mode-Description of generate-wireguard.xml.in 

## Proposed changes

The description "Generate WireGuard keys" doesn't belong to this command. It should be updated to something fitting like "Generate WireGuard client config QR code"

## How to test

Running "generate ?" in op-mode:
```
user@VyOS:~$ generate ?
Possible completions:
  container             Generate Container Image
  firewall              Firewall
  interfaces            Interface specific commands
  ipsec                 Generate IPsec related configurations and archives
  macsec                Generate MACsec Key
  openconnect           Generate OpenConnect client parameters
  openvpn               Generate OpenVPN client configuration ovpn file
  pki                   Generate PKI certificates and keys
  public-key-command    Generate configuration mode command to add OpenSSH public key
                        from file
  ssh                   Generate SSH related keypairs
  system                Generate system related parameters
  tech-support          Generate tech support info
  wireguard             Generate WireGuard keys
```

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-01-01 20:45 UTC, c-po requested changes

2024-01-01 20:45 UTC, c-po commented on op-mode-definitions/generate-wireguard.xml.in
> +          <help>Generate WireGuard Client config QR code</help>
Should be improved to: `Generate WireGuard client configuration and QR code`

2024-01-01 23:18 UTC, sever-sever commented
Check commit message. Expected format with task number

2024-01-02 00:19 UTC, dmbaturin requested changes
Please come up with an informative commit message, too, like "correct the 'generate wireguard' command help string" at least.

2024-01-02 00:19 UTC, dmbaturin commented on op-mode-definitions/generate-wireguard.xml.in
> +          <help>Generate WireGuard Client config QR code</help>
Why capitalize "Client"? It's not a proper noun.

2024-01-02 18:18 UTC, aga1314 commented on op-mode-definitions/generate-wireguard.xml.in
> +          <help>Generate WireGuard Client config QR code</help>
Sorry, I just accepted the requested change..

2024-01-02 20:34 UTC, merged

2024-01-02 20:36 UTC, c-po commented
Squashed and updated commit message