ifconfig: T2057: explicity name state functions
vyos/vyos-1x pull request #275
Opened 2020-03-27 20:00 UTC by thomas-mangin

The Interface get_state/set_state were not clear about
if they edited the admin or operational state.

functions are now using admin_state and oper_state
for clarity.

2020-03-27 20:17 UTC, dmbaturin approved these changes
Sensible,  I think.

2020-03-28 09:38 UTC, c-po commented
Reading operstate is definately required when the `show interfaces` commands get migrated. But it makes no sense to "write" into the `operstate` as it can not be written at all (it would make no sense, too).


The values according to the Kernel ABI are:

2020-03-28 09:44 UTC, c-po requested changes
Reading operstate is definately required when the `show interfaces` commands get migrated. But it makes no sense to "write" into the `operstate` as it can not be written at all (it would make no sense, too).


The values according to the Kernel ABI are:
```
What:           /sys/class/net/<iface>/operstate
Date:           March 2006
KernelVersion:  2.6.17
Contact:        netdev@vger.kernel.org
Description:
                Indicates the interface RFC2863 operational state as a string.
                Possible values are:
                "unknown", "notpresent", "down", "lowerlayerdown", "testing",
                "dormant", "up".
```

Also the sysfs node is clearly marked as RO in the Kernel Source code `static DEVICE_ATTR_RO(operstate);` (see commit 6be8aeef348a7a4a1 ("net: core: convert class code to use dev_groups")), thus `_sysfs_set['oper_state']` must be droped from the implementation.

2020-03-28 10:15 UTC, thomas-mangin commented
LOL - ok make sense .. removing the useless code.

2020-03-28 10:23 UTC, thomas-mangin commented
set_oper_state removed.

2020-03-28 10:25 UTC, merged