vrrp: T6020: vrrp health-check script not applied correctly
vyos/vyos-1x pull request #2966
Opened 2024-02-08 09:02 UTC by HollyGurza

T6020: vrrp health-check script not applied correctly in keepalived.conf

Added health check to sync-group in CLI
Don't use instance health-check when instance in sync group member
Warning notify for health-check config problem
New smoke test

## Change Summary

Added health check to sync-group in CLI
Don't use instance health-check when instance in sync group member
Warning notify for health-check config problem
New smoke test
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6020

## Related PR(s)

## Component(s) name

## Proposed changes

high-availability vrrp

## How to test

## Smoketest result

```
vyos@vyos# python3 /usr/libexec/vyos/tests/smoke/cli/test_high-availability_vrrp.py 
test_01_default_values (__main__.TestVRRP.test_01_default_values) ... ok
test_02_simple_options (__main__.TestVRRP.test_02_simple_options) ... ok
test_03_sync_group (__main__.TestVRRP.test_03_sync_group) ... ok
test_04_exclude_vrrp_interface (__main__.TestVRRP.test_04_exclude_vrrp_interface) ... ok
test_check_health_script (__main__.TestVRRP.test_check_health_script) ... ok

----------------------------------------------------------------------
Ran 5 tests in 43.278s

OK

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

2024-02-08 16:29 UTC, zdc requested changes
In the history of this template, I see that this logic was changed several times, many of them with mistakes.

Would it not be better to finally add health-check to sync-group in CLI and disallow configurations with health-check inside the vrrp group if it is a group member?

2024-02-08 22:04 UTC, c-po commented on data/templates/high-availability/keepalived.conf.j2
> +{%         if group_config.health_check is vyos_defined and group_config.health_check.script is not vyos_defined %}
`{%         if group_config.health_check.script is not vyos_defined %}` would be sufficient in this case

2024-02-12 09:39 UTC, faekz0r commented
> In the history of this template, I see that this logic was changed several times, many of them with mistakes.
> 
> Would it not be better to finally add health-check to sync-group in CLI and disallow configurations with health-check inside the vrrp group if it is a group member?

That sounds like a great idea. In fact when I ran into the current bug, I was astounded that you can't actually configure the health-check for the vrrp group from the VyOS CLI.
Otherwise I could have also worked around the bug by configuring it correctly from CLI.

2024-02-12 10:57 UTC, HollyGurza commented
> In the history of this template, I see that this logic was changed several times, many of them with mistakes.
> 
> Would it not be better to finally add health-check to sync-group in CLI and disallow configurations with health-check inside the vrrp group if it is a group member?

Done

2024-02-16 07:34 UTC, sever-sever commented
@zdc Could you check the proposed changes?

2024-02-25 09:30 UTC, dmbaturin approved these changes
I don't see any issues with the implementation.
@zdc could you check if everything you wanted to address is done?

2024-03-07 16:20 UTC, merged

2024-03-07 16:22 UTC, dmbaturin commented
@mergify backport sagitta

2024-03-07 16:24 UTC, dmbaturin commented
@mergifyio backport sagitta

2024-03-09 09:42 UTC, sever-sever commented
@MergifyIo backport sagitta

2024-03-09 09:43 UTC, sever-sever commented
@HollyGurza Could you create PR for 1.4? 
For some reason, mergify does not work

2024-03-12 06:37 UTC, HollyGurza commented
> @HollyGurza Could you create PR for 1.4? For some reason, mergify does not work

https://github.com/vyos/vyos-1x/pull/3122