T5703: Fix reaply QoS for connection-oriented interfaces
vyos/vyos-1x pull request #2967
Opened 2024-02-08 11:09 UTC by sever-sever

## Change Summary

After `disconnect` and `connect` connection-oriented interfaces like PPPoE, QoS policy has to be reaplied
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5703

## Related PR(s)

## Component(s) name

qos
## Proposed changes

## How to test
Disconnect and connect PPP interface which has QoS policy configuration
```
set qos policy cake LIMIT bandwidth '95mbit'
set qos policy cake LIMIT flow-isolation
set qos policy cake LIMIT rtt '100'
set qos interface pppoe1 egress 'LIMIT'
```
Before the fix it sets default qdisc (expected `cake 95Mbit`)
```
disconnect interface pppoe1
connect interface pppoe1

vyos@r4# tc qdisc show dev pppoe1
qdisc fq_codel 0: root refcnt 2 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 32Mb ecn drop_batch 64 
[edit]
vyos@r4# 

```
After the fix:
```
disconnect interface pppoe1
connect interface pppoe1

vyos@r4# run connect interface pppoe1 
Interface pppoe1: connecting...

DEBUG/QoS: tc qdisc add dev pppoe1 root handle 1: cake egress bandwidth 95000000 rtt 100ms
{'bandwidth': '95mbit', 'flow_isolation': {}, 'rtt': '100'}
[edit]
vyos@r4# 
[edit]
vyos@r4# tc qdisc show dev pppoe1
qdisc cake 1: root refcnt 2 bandwidth 95Mbit diffserv3 triple-isolate nonat nowash no-ack-filter split-gso rtt 100ms raw overhead 0 
[edit]
vyos@r4# 

```

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-02-08 16:25 UTC, dmbaturin requested changes
We need to make sure that the script isn't called when there's a commit in progress to avoid possibly applying outdated QoS config or, worse, having it fail because the user tries to commit a config with errors.

2024-02-09 08:33 UTC, sever-sever commented
> We need to make sure that the script isn't called when there's a commit in progress to avoid possibly applying outdated QoS config or, worse, having it fail because the user tries to commit a config with errors.

Done!

2024-02-09 08:45 UTC, c-po approved these changes

2024-02-09 10:12 UTC, dmbaturin approved these changes

2024-02-09 10:12 UTC, merged

2024-02-09 10:12 UTC, dmbaturin commented
@mergifyio backport sagitta