conntrack-sync: T1244: Support for StartupResync in conntrackd
vyos/vyos-1x pull request #3254
Opened 2024-04-05 12:03 UTC by natali-rs1985

## Change Summary

Added option fo enabling startup resync

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

 * https://vyos.dev/T1244

## Related PR(s)

## Component(s) name

conntrack-sync

## Proposed changes

## How to test

```
set high-availability vrrp group internal interface 'eth0'
set high-availability vrrp group internal virtual-address 10.0.0.10/24 interface 'eth0'
set high-availability vrrp group internal vrid '36'
set high-availability vrrp sync-group syncgrp member 'internal'
set service conntrack-sync failover-mechanism vrrp sync-group 'syncgrp'
set service conntrack-sync interface eth0
set service conntrack-sync enable-startup-resync
commit

vyos@vyos# cat /run/conntrackd/conntrackd.conf | grep StartupResync
        StartupResync on
```

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

2024-04-05 14:44 UTC, sever-sever commented on interface-definitions/service_conntrack-sync.xml.in
> +          <leafNode name="enable-startup-resync">
Еhe word `enable` seems superfluous here

2024-04-05 17:01 UTC, sever-sever requested changes
The word `enable` seems superfluous here
Change it also and for 1.3

2024-04-05 19:18 UTC, natali-rs1985 commented on interface-definitions/service_conntrack-sync.xml.in
> +          <leafNode name="enable-startup-resync">
Fixed

2024-04-06 02:24 UTC, sever-sever approved these changes

2024-04-06 09:08 UTC, c-po approved these changes

2024-04-06 09:08 UTC, merged

2024-04-06 09:09 UTC, c-po commented
@MergifyIo backport sagitta