T6214: T6213: change constraint <alpha-numeric-hyphen-underscore-dot.xml.i>
vyos/vyos-1x pull request #3281
Opened 2024-04-09 11:12 UTC by nicolas-fort

## Change Summary

Change constraint [alpha-numeric-hyphen-underscore-dot.xml.i](https://github.com/vyos/vyos-1x/blob/current/interface-definitions/include/constraint/alpha-numeric-hyphen-underscore-dot.xml.i) in order to not allow string starting with dot character; use such constraint in firewall group definitions.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6214
* https://vyos.dev/T6213

## Related PR(s)

## Component(s) name

firewall
## Proposed changes

## How to test

```
vyos@Latest# compare commands 

set firewall group address-group -X_.Y address '198.51.100.3'
set firewall group address-group A.B_C-D address '198.51.100.1'
set firewall group address-group _aB-C. address '198.51.100.2'

[edit]
vyos@Latest# commit
[edit]
vyos@Latest# sudo nft list table ip vyos_filter | grep "set A"
        set A_-X_.Y {
        set A_A.B_C-D {
        set A__aB-C. {
[edit]
vyos@Latest# set firewall group port-group .PG01 port 22

  
  
  Name of firewall group con only contain alpha-numeric letters, hyphen, underscores and dot
  Value validation failed
  Set failed

[edit]
vyos@Latest# 
```

## Smoketest result

Smoketest run during this change:
* test_firewall.py
* test_interfaces_pppoe.py
* test_service_pppoe-server.py
* test_protocols_bgp.py 
* test_service_dhcp-server.py
* test_service_dhcpv6-server.py
* test_pki.py

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-04-09 14:58 UTC, dmbaturin requested changes

2024-04-09 14:58 UTC, dmbaturin commented on interface-definitions/firewall.xml.in
> +              <constraintErrorMessage>Name of firewall group con only contain alpha-numeric letters, hyphen, underscores and dot</constraintErrorMessage>
There's a recurring typo in the help message: s/con/can/

2024-04-09 14:59 UTC, dmbaturin commented on interface-definitions/firewall.xml.in
> +                  <constraintErrorMessage>Name of firewall group con only contain alpha-numeric letters, hyphen, underscores and dot</constraintErrorMessage>
Also, "alphanumeric" doesn't need a hyphen I think.

2024-04-11 14:51 UTC, merged

2024-04-11 14:51 UTC, c-po commented
@MergifyIo backport sagitta