T6100: Added NAT migration from IP/Netmask to Network/Netmask
vyos/vyos-1x pull request #3291
Opened 2024-04-11 08:58 UTC by aapostoliuk

## Change Summary

Added NAT migration from IP/Netmask to Network/Netmask.
In 1.3 allowed using IP/Netmask in Nat rules.
In 1.4 and 1.5 it is prohibited. Allowed Network/Netmask.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6100

## Related PR(s)

## Component(s) name

nat

## Proposed changes

Added NAT migration from IP/Netmask to Network/Netmask.
In 1.3 allowed using IP/Netmask in Nat rules.
In 1.4 and 1.5 it is prohibited. Allowed Network/Netmask.

## How to test

For example:
VyOS 1.3.6 configuration:
```
set nat destination rule 2060 destination port '5060,10000-20000'
set nat destination rule 2060 inbound-interface 'eth4'
set nat destination rule 2060 protocol 'udp'
set nat destination rule 2060 source address '!192.0.2.226/27'
set nat destination rule 2060 translation address '10.250.1.3'
```

Netfilter config in 1.3.6
```
table ip nat {
        chain PREROUTING {
                type nat hook prerouting priority dstnat; policy accept;
                counter packets 411 bytes 72404 jump VYATTA_PRE_DNAT_HOOK
                iifname "eth4" meta l4proto udp ip saddr != 192.0.2.224/27 udp dport { 5060,10000-20000} counter packets 0 bytes 0 dnat to 10.250.1.3 comment "DST-NAT-2060"
        }
```
Migration to 1.4 or 1.5 fails, because
```
vyos@vyos# set nat destination rule 2060 source address '!192.0.2.226/27'

  Error: 192.0.2.226/27 is not a valid IPv4 address range

  Error: 192.0.2.226/27 is not a valid IPv4 prefix

  Error: 192.0.2.226/27 is not a valid IPv4 address

  Error: !192.0.2.226/27 is not a valid IPv4 address range

  Error: !192.0.2.226/27 is not a valid IPv4 prefix

  Error: !192.0.2.226/27 is not a valid IPv4 address

  Invalid value
  Value validation failed
  Set failed

[edit]
```
After changes:
After migration from 1.3 to 1.4 or 1.5. VyOS config looks
```
set nat destination rule 2060 destination port '5060,10000-20000'
set nat destination rule 2060 inbound-interface name 'eth4'
set nat destination rule 2060 protocol 'udp'
set nat destination rule 2060 source address '!192.0.2.224/27'
set nat destination rule 2060 translation address '10.250.1.3'
```
## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-04-11 15:44 UTC, dmbaturin requested changes
Please add it to the existing migration script, since no new syntax is added here — version increase is not warranted.

2024-04-12 06:44 UTC, aapostoliuk commented
@dmbaturin 
>Please add it to the existing migration script, since no new syntax is added here — version increase is not warranted.
Done

2024-04-12 18:31 UTC, c-po approved these changes

2024-04-12 18:31 UTC, merged

2024-04-12 18:31 UTC, c-po commented
@MergifyIo backport sagitta