T6255: static-routing: Block whitespace from routing table descriptions
vyos/vyos-1x pull request #3340
Opened 2024-04-21 22:52 UTC by Embezzle

## Change Summary

Fixed [T6255](https://vyos.dev/T6255) by replacing use of generic description node with specific description node containing appropriate regex constraints to block whitespace.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

[https://vyos.dev/T6255](https://vyos.dev/T6255)

## Related PR(s)

## Component(s) name
protocol -> static-routing

## Proposed changes

## How to test

1. Set table description containing whitespace - check validation fails.
2. Set table description without whitespace - check validation passes.
```
[edit]
vyos@vyos# set protocols static table 100 description "example whitespace"

  Description too long or contains whitespace (limit 64 characters)
  Value validation failed
  Set failed

[edit]
vyos@vyos# set protocols static table 100 description "example-no-whitespace"
[edit]
vyos@vyos#
```

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-04-22 16:12 UTC, dmbaturin requested changes
Since whitespace used to be allowed and didn't cause commit failures, this will require a migration script if we are to merge it.

2024-04-22 18:22 UTC, Embezzle commented
> Since whitespace used to be allowed and didn't cause commit failures, this will require a migration script if we are to merge it.

I have added a migration script to replace whitespace in existing table descriptions with underscores.

2024-04-22 18:48 UTC, c-po commented on interface-definitions/include/version/static-routing-version.xml.i
> +<syntaxVersion component='static-routing' version='1'></syntaxVersion>
I wonder if we should introduce a new component here or rely on the good old fashioned `quagga-version` here.

2024-04-23 05:53 UTC, c-po commented
I see the main reason for the description use-case at the moment is to alias a routing table by name instead of it's table ID. There is no VyOS CLI for retrieving the routing table with a given alias.

Using the alias can only by done by `sudo ip route show table <description alias>`. Why not keep it simple: When rendering the description into `/etc/iproute2/rt_tables.d/vyos-static.conf` replace whitespace with `_`. If we really wan't to make use of mnemonics we should probably add a proper `alias` CLI node making explicit use of this feature.

2024-04-23 17:14 UTC, Embezzle commented
> I see the main reason for the description use-case at the moment is to alias a routing table by name instead of it's table ID. There is no VyOS CLI for retrieving the routing table with a given alias.
> 
> Using the alias can only by done by `sudo ip route show table <description alias>`. Why not keep it simple: When rendering the description into `/etc/iproute2/rt_tables.d/vyos-static.conf` replace whitespace with `_`. If we really wan't to make use of mnemonics we should probably add a proper `alias` CLI node making explicit use of this feature.

Thank you @c-po for the feedback, looks like I have been approaching this from the wrong angle!
As requested, I have editing my commit to just replace whitespace in rendering & have updated the PR description to reflect.

2024-04-23 18:42 UTC, c-po approved these changes

2024-04-23 18:44 UTC, merged

2024-04-23 18:45 UTC, c-po commented
@MergifyIo backport sagitta