T6273: Allowed the use of "-" and "_" in PPPoE access-concentrator name
vyos/vyos-1x pull request #3374
Opened 2024-04-29 09:41 UTC by aapostoliuk

## Change Summary

Allowed the use of "-" and "_" in PPPoE access-concentrator name

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6273

## Related PR(s)

## Component(s) name

pppoe
## Proposed changes

Allowed the use of "-" and "_" in PPPoE access-concentrator name

## How to test

`vyos@vyos# set service pppoe-server access-concentrator first_concentrator`

```
vyos@vyos# set service pppoe-server access-concentrator first+concentrator

  Access-concentrator name can  only contain alpha-numeric letters, hyphen and underscores(max. 100 characters)
  Value validation failed
  Set failed

[edit]
```

## Smoketest result

```
vyos@vyos:~$ /usr/libexec/vyos/tests/smoke/cli/test_service_pppoe-server.py
test_accel_ipv4_pool (__main__.TestServicePPPoEServer.test_accel_ipv4_pool) ... ok
test_accel_ipv6_pool (__main__.TestServicePPPoEServer.test_accel_ipv6_pool) ...
WARNING: IPv4 Server requires gateway-address to be configured!

WARNING: 'default-ipv6-pool' is not defined

ok
test_accel_limits (__main__.TestServicePPPoEServer.test_accel_limits) ... ok
test_accel_local_authentication (__main__.TestServicePPPoEServer.test_accel_local_authentication) ...
User "test" has rate-limit configured for only one direction but both
upload and download must be given!

ok
test_accel_name_servers (__main__.TestServicePPPoEServer.test_accel_name_servers) ... ok
test_accel_next_pool (__main__.TestServicePPPoEServer.test_accel_next_pool) ...
WARNING: 'default-pool' is not defined

ok
test_accel_ppp_options (__main__.TestServicePPPoEServer.test_accel_ppp_options) ... ok
test_accel_radius_authentication (__main__.TestServicePPPoEServer.test_accel_radius_authentication) ... ok
test_accel_shaper (__main__.TestServicePPPoEServer.test_accel_shaper) ... ok
test_accel_snmp (__main__.TestServicePPPoEServer.test_accel_snmp) ... ok
test_accel_wins_server (__main__.TestServicePPPoEServer.test_accel_wins_server) ... ok
test_pppoe_limits (__main__.TestServicePPPoEServer.test_pppoe_limits) ... ok
test_pppoe_server_authentication_protocols (__main__.TestServicePPPoEServer.test_pppoe_server_authentication_protocols) ... ok
test_pppoe_server_pado_delay (__main__.TestServicePPPoEServer.test_pppoe_server_pado_delay) ... ok
test_pppoe_server_shaper (__main__.TestServicePPPoEServer.test_pppoe_server_shaper) ... ok
test_pppoe_server_vlan (__main__.TestServicePPPoEServer.test_pppoe_server_vlan) ... ok

----------------------------------------------------------------------
Ran 16 tests in 58.363s

OK
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-04-29 09:50 UTC, sever-sever approved these changes

2024-04-29 13:50 UTC, c-po approved these changes

2024-04-29 13:51 UTC, c-po requested changes

2024-04-29 13:51 UTC, c-po commented on interface-definitions/include/pppoe-access-concentrator.xml.i
> +    <constraintErrorMessage>Access-concentrator name can  only contain alpha-numeric letters, hyphen and underscores(max. 100 characters)</constraintErrorMessage>
double whitespace after `can` before `only`

2024-04-30 06:30 UTC, aapostoliuk commented on interface-definitions/include/pppoe-access-concentrator.xml.i
> +    <constraintErrorMessage>Access-concentrator name can  only contain alpha-numeric letters, hyphen and underscores(max. 100 characters)</constraintErrorMessage>
Done

2024-04-30 06:34 UTC, c-po commented
@MergifyIo backport sagitta

2024-04-30 06:34 UTC, merged