[WIP] fix: remove warnings for negated interface selections by name
vyos/vyos-1x pull request #3482
Opened 2024-05-18 13:54 UTC by alryaz

## Change Summary

Avoids spam of invalid warnings when a negated interface name is used.

```
...
WARNING: NAT interface "!bond0.2" for destination NAT rule "430" does
not exist!
WARNING: NAT interface "!bond0.2" for destination NAT rule "450" does
not exist!
WARNING: NAT interface "!bond0.2" for destination NAT rule "470" does
not exist!
WARNING: NAT interface "!bond0.2" for destination NAT rule "490" does
not exist!
WARNING: NAT interface "!bond0.2" for destination NAT rule "510" does
not exist!
...
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

## Related PR(s)

## Component(s) name

- nat source
- nat destination

## Proposed changes
Added code to parse negation (in a similar manner groups are used).

## How to test

```
set nat destination rule 10 description 'DNS'
set nat destination rule 10 destination address 10.0.0.1
set nat destination rule 10 destination port 53
set nat destination rule 10 inbound-interface name '!eth0'
set nat destination rule 10 protocol 'tcp_udp'
set nat destination rule 10 translation address 172.16.0.1
```

And perform a `commit`.

## Smoketest result

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-05-18 14:26 UTC, sever-sever commented
Read please contributing; you used an incorrect commit message
https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md#prepare-patchcommit

You can change it with `git commit --amend` and force push option, to overwrite

2024-05-18 19:07 UTC, c-po requested changes

2024-05-18 19:07 UTC, c-po commented on src/conf_mode/nat.py
> +                        if interface_name[0] == '!':
Please use `interface_name.startswith()` instead.

2024-05-18 19:07 UTC, c-po commented on src/conf_mode/nat.py
> +                        if interface_name[0] == '!':
Please use `interface_name.startswith()` instead.

2024-05-22 17:55 UTC, sever-sever approved these changes

2024-05-22 17:56 UTC, c-po commented
```
cpo@LR1.wue3:~$ /usr/libexec/vyos/tests/smoke/cli/test_nat.py
test_dnat (__main__.TestNAT.test_dnat) ... ok
test_dnat_negated_addresses (__main__.TestNAT.test_dnat_negated_addresses) ... ok
test_dnat_redirect (__main__.TestNAT.test_dnat_redirect) ... ok
test_dnat_without_translation_address (__main__.TestNAT.test_dnat_without_translation_address) ... ok
test_nat_balance (__main__.TestNAT.test_nat_balance) ... ok
test_nat_no_rules (__main__.TestNAT.test_nat_no_rules) ... ok
test_snat (__main__.TestNAT.test_snat) ... ok
test_snat_groups (__main__.TestNAT.test_snat_groups) ... ok
test_snat_net_port_map (__main__.TestNAT.test_snat_net_port_map) ... ok
test_snat_required_translation_address (__main__.TestNAT.test_snat_required_translation_address) ... ok
test_static_nat (__main__.TestNAT.test_static_nat) ... ok

----------------------------------------------------------------------
Ran 11 tests in 38.363s

OK
```

2024-05-22 18:00 UTC, c-po approved these changes

2024-05-22 18:00 UTC, c-po commented
@MergifyIo backport sagitta

2024-05-22 18:00 UTC, merged