T4576: Accel-ppp logging level configuration
vyos/vyos-1x pull request #3510
Opened 2024-05-23 12:13 UTC by HollyGurza

add ability to change logging level config for:
* VPN L2TP
* VPN PPTP
* VPN SSTP
* IPoE Server
* PPPoE Serve

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T4576

## Related PR(s)

## Component(s) name

## Proposed changes

## How to test

Configure service e.g. VPN L2TP:
```
set vpn ipsec interface 'eth0'
set vpn l2tp remote-access authentication local-users username test password 'test'
set vpn l2tp remote-access authentication mode 'local'
set vpn l2tp remote-access client-ip-pool L2TP-POOL range '192.168.255.2-192.168.255.254'
set vpn l2tp remote-access default-pool 'L2TP-POOL'
set vpn l2tp remote-access gateway-address '192.168.255.1'
set vpn l2tp remote-access ipsec-settings authentication mode 'pre-shared-secret'
set vpn l2tp remote-access ipsec-settings authentication pre-shared-secret 'test'
set vpn l2tp remote-access outside-address '192.168.122.166'
```
and connect to service:
```
vyos@vyos:~$ show l2tp-server sessions
 ifname | username |      ip       | ip6 | ip6-dp |  calling-sid  | rate-limit | state  |  uptime  | rx-bytes | tx-bytes 
--------+----------+---------------+-----+--------+---------------+------------+--------+----------+----------+----------
 l2tp0  | test     | 192.168.255.2 |     |        | 192.168.122.1 |            | active | 00:00:29 | 52 B     | 208 B
```
log level = 5
```
vyos@vyos:~$ journalctl --unit accel-ppp@l2tp.service
May 23 12:06:14 vyos systemd[1]: Stopping accel-ppp@l2tp.service - Accel-PPP - >
May 23 12:06:14 vyos accel-l2tp[2883]: terminate, sig = 15
May 23 12:06:15 vyos systemd[1]: accel-ppp@l2tp.service: Deactivated successful>
May 23 12:06:15 vyos systemd[1]: Stopped accel-ppp@l2tp.service - Accel-PPP - H>
May 23 12:06:15 vyos systemd[1]: Starting accel-ppp@l2tp.service - Accel-PPP - >
May 23 12:06:15 vyos systemd[1]: Started accel-ppp@l2tp.service - Accel-PPP - H>
May 23 12:06:15 vyos accel-l2tp[3925]: l2tp: iprange module disabled, improper >
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp: recv [L2TP tid=0 sid=0 Ns=0 Nr=0 <>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp: handling SCCRQ from 192.168.122.1
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp: new tunnel 48754-6741 created foll>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp session 48754-6741, 54439-63018: se>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp session 48754-6741, 54439-63018: ha>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: l2tp tunnel 48754-6741 (192.168.122.1:17>
May 23 12:06:45 vyos accel-l2tp[3925]: :: starting data channel for l2tp(192.16>
May 23 12:06:45 vyos accel-l2tp[3925]: :: lcp_layer_init
May 23 12:06:45 vyos accel-l2tp[3925]: :: auth_layer_init
May 23 12:06:45 vyos accel-l2tp[3925]: :: ccp_layer_init
May 23 12:06:45 vyos accel-l2tp[3925]: :: ipcp_layer_init
May 23 12:06:45 vyos accel-l2tp[3925]: :: ipv6cp_layer_init
May 23 12:06:45 vyos accel-l2tp[3925]: :: ppp establishing
May 23 12:06:45 vyos accel-l2tp[3925]: :: lcp_layer_start
May 23 12:06:45 vyos accel-l2tp[3925]: :: send [LCP ConfReq id=61 <auth PAP> <m>
May 23 12:06:45 vyos accel-l2tp[3925]: :: recv [LCP ConfReq id=1 <mru 1400> < 2>
May 23 12:06:45 vyos accel-l2tp[3925]: :: send [LCP ConfRej id=1 < 2 6 0 0 0 0 >
May 23 12:06:45 vyos accel-l2tp[3925]: :: recv [LCP ConfReq id=2 <mru 1400> <ma>
May 23 12:06:45 vyos accel-l2tp[3925]: :: send [LCP ConfAck id=2]
May 23 12:06:48 vyos accel-l2tp[3925]: :: fsm timeout 9
```
log level 0:
```
vyos@vyos# set vpn l2tp remote-access log level 0
[edit]
vyos@vyos# commit
[edit]
vyos@vyos# journalctl --unit accel-ppp@l2tp.service
May 23 12:10:10 vyos systemd[1]: Stopping accel-ppp@l2tp.service - Accel-PPP - >
May 23 12:10:10 vyos accel-l2tp[3925]: terminate, sig = 15
May 23 12:10:11 vyos systemd[1]: accel-ppp@l2tp.service: Deactivated successful>
May 23 12:10:11 vyos systemd[1]: Stopped accel-ppp@l2tp.service - Accel-PPP - H>
May 23 12:10:11 vyos systemd[1]: Starting accel-ppp@l2tp.service - Accel-PPP - >
May 23 12:10:11 vyos systemd[1]: accel-ppp@l2tp.service: Can't open PID file /r>
May 23 12:10:11 vyos systemd[1]: Started accel-ppp@l2tp.service - Accel-PPP - H>
```

## Smoketest result

```
vyos@vyos:~$ python3 /usr/libexec/vyos/tests/smoke/cli/test_vpn_l2tp.py 
test_accel_ipv4_pool (__main__.TestVPNL2TPServer.test_accel_ipv4_pool) ... ok
test_accel_ipv6_pool (__main__.TestVPNL2TPServer.test_accel_ipv6_pool) ... 
WARNING: IPv4 Server requires gateway-address to be configured!

WARNING: 'default-ipv6-pool' is not defined

ok
test_accel_limits (__main__.TestVPNL2TPServer.test_accel_limits) ... ok
test_accel_local_authentication (__main__.TestVPNL2TPServer.test_accel_local_authentication) ... 
User "test" has rate-limit configured for only one direction but both
upload and download must be given!

ok
test_accel_log_level (__main__.TestVPNL2TPServer.test_accel_log_level) ... ok
test_accel_name_servers (__main__.TestVPNL2TPServer.test_accel_name_servers) ... ok
test_accel_next_pool (__main__.TestVPNL2TPServer.test_accel_next_pool) ... 
WARNING: 'default-pool' is not defined

ok
test_accel_ppp_options (__main__.TestVPNL2TPServer.test_accel_ppp_options) ... ok
test_accel_radius_authentication (__main__.TestVPNL2TPServer.test_accel_radius_authentication) ... ok
test_accel_shaper (__main__.TestVPNL2TPServer.test_accel_shaper) ... ok
test_accel_snmp (__main__.TestVPNL2TPServer.test_accel_snmp) ... ok
test_accel_wins_server (__main__.TestVPNL2TPServer.test_accel_wins_server) ... ok
test_l2tp_radius_server (__main__.TestVPNL2TPServer.test_l2tp_radius_server) ... ok
test_l2tp_server_authentication_protocols (__main__.TestVPNL2TPServer.test_l2tp_server_authentication_protocols) ... ok
test_vpn_l2tp_dependence_ipsec_swanctl (__main__.TestVPNL2TPServer.test_vpn_l2tp_dependence_ipsec_swanctl) ... 
WARNING: 'default-pool' is not defined

ok

----------------------------------------------------------------------
Ran 15 tests in 81.208s

OK
```

```
vyos@vyos:~$ python3 /usr/libexec/vyos/tests/smoke/cli/test_vpn_pptp.py 
test_accel_ipv4_pool (__main__.TestVPNPPTPServer.test_accel_ipv4_pool) . [...]

2024-05-23 12:18 UTC, HollyGurza commented
Our log level is set to 5 by default, but in accel-ppp documentation, default log level is 0
https://docs.accel-ppp.org/configuration/log.html
should we change our default level to 0 or continue to keep 5?

2024-05-23 12:57 UTC, dmbaturin requested changes

2024-05-23 12:57 UTC, dmbaturin commented on interface-definitions/service_ipoe-server.xml.in
> +              <help>Logging IPoE Server</help>
This isn't a good grammar. I'd say "IPoE server logging". This applies to all instances of that string.

2024-05-23 12:57 UTC, dmbaturin commented on interface-definitions/include/accel-ppp/log-level.xml.i
> +  <defaultValue>5</defaultValue>
>Our log level is set to 5 by default, but in accel-ppp documentation, default log level is 0

I don't think either of those extremes is a good idea. Level 3 sounds like a good default for me.

2024-05-23 12:57 UTC, dmbaturin commented on interface-definitions/vpn_l2tp.xml.in
> +              <help>Logging L2TP VPN</help>
Arguably, it should be "L2TP server logging" as well.

2024-05-24 13:26 UTC, dmbaturin approved these changes

2024-05-24 17:17 UTC, c-po requested changes

2024-05-24 17:17 UTC, c-po commented on src/conf_mode/vpn_pptp.py
> +    pptp['log'] = conf.get_config_dict(['vpn', 'pptp', 'log'],
I wonder why this is necessary?

That‘s why we have `get_accel_dict()` for, to abstract away recurring config retrieval tasks. Why not throw `['vpn', 'pptp']` at `get_accel_dict()` so that it‘s read in by the default helper function for accel? This will add one more key to the dict level (remote-access), which should be adjusted in the rest of the file. Thats way more generic then re-reading the dict at another level.

2024-05-24 17:18 UTC, c-po commented on interface-definitions/service_ipoe-server.xml.in
> +              <help>Logging IPoE Server</help>
By removing the service name (IPoE) from the help string, you can generalize this. As this is under `service ipoe-server` we can safely assume the user knows he is working under IPoE node.

2024-05-27 12:24 UTC, HollyGurza commented on interface-definitions/service_ipoe-server.xml.in
> +              <help>Logging IPoE Server</help>
done

2024-05-27 12:27 UTC, HollyGurza commented on src/conf_mode/vpn_pptp.py
> +    pptp['log'] = conf.get_config_dict(['vpn', 'pptp', 'log'],
i moved `log` node to `remote-access` for `pptp` and `l2tp`
now it looks and work the same as other accel-ppp services

2024-05-30 15:26 UTC, c-po approved these changes

2024-05-30 15:27 UTC, dmbaturin commented
@mergifyio backport sagitta

2024-05-30 15:27 UTC, merged