dns: T6422: allow multiple redundant NS records
vyos/vyos-1x pull request #3557
Opened 2024-05-30 15:08 UTC by haimgel

## Change Summary
NS is unlike CNAME or PTR, multiple NS records are perfectly valid and is a common use case: multiple redundant DNS servers is a common configuration and should be supported.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Component(s) name
dns

## Proposed changes
Make NS record configuration behave more like A record, where multiple records with the same target are allowed.

## How to test

```
set service dns forwarding authoritative-domain example.com records ns test target 'ns1.example.com'
set service dns forwarding authoritative-domain example.com records ns test target 'ns2.example.com'
commit

dig ns test.example.com

Response:
;; ANSWER SECTION:
test.example.com.	254	IN	NS	ns2.example.com.
test.example.com.	254	IN	NS	ns1.example.com.

```

## Smoketest result
```
$ /usr/libexec/vyos/tests/smoke/cli/test_service_dns_forwarding.py
test_basic_forwarding (__main__.TestServicePowerDNS.test_basic_forwarding) ...
DNS forwarding requires a listen-address

DNS forwarding requires a listen-address

ok
test_dns64 (__main__.TestServicePowerDNS.test_dns64) ...
DNS 6to4 prefix must be of length /96

ok
test_dnssec (__main__.TestServicePowerDNS.test_dnssec) ... ok
test_domain_forwarding (__main__.TestServicePowerDNS.test_domain_forwarding) ... ok
test_ecs_add_for (__main__.TestServicePowerDNS.test_ecs_add_for) ... ok
test_ecs_ipv4_bits (__main__.TestServicePowerDNS.test_ecs_ipv4_bits) ... ok
test_edns_subnet_allow_list (__main__.TestServicePowerDNS.test_edns_subnet_allow_list) ... ok
test_exclude_throttle_adress (__main__.TestServicePowerDNS.test_exclude_throttle_adress) ... ok
test_external_nameserver (__main__.TestServicePowerDNS.test_external_nameserver) ... ok
test_listening_port (__main__.TestServicePowerDNS.test_listening_port) ... ok
test_no_rfc1918_forwarding (__main__.TestServicePowerDNS.test_no_rfc1918_forwarding) ... ok
test_serve_stale_extension (__main__.TestServicePowerDNS.test_serve_stale_extension) ... ok

----------------------------------------------------------------------
Ran 12 tests in 195.660s

OK
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-05-30 15:17 UTC, dmbaturin requested changes, later dismissed

2024-05-30 15:17 UTC, dmbaturin commented on src/conf_mode/service_dns_forwarding.py
> +                            dns['authoritative_zone_errors'].append(f'{subnode}.{node}: at leaast one target is required')
Typo: "leaast".

2024-05-30 15:17 UTC, dmbaturin commented
Please add a smoke test, too!

2024-05-30 16:17 UTC, haimgel commented
@dmbaturin, thanks! I added a smoke test and fixed the typo. Note that smoke coverage for authoritative DNS setup is not great to begin with, I focused here on what this change does only.

2024-05-30 19:11 UTC, c-po requested changes

2024-05-30 19:11 UTC, c-po commented on src/conf_mode/service_dns_forwarding.py
> +                                'value': '{}.'.format(target)
Can we get an `f`-ormated string here?

`f'value': '{target}.'`

2024-05-30 19:26 UTC, haimgel commented on src/conf_mode/service_dns_forwarding.py
> +                                'value': '{}.'.format(target)
👍 , updated.

2024-05-30 19:43 UTC, c-po commented
Please update the PR description with a more recent output of your smoketest, as the provided one lacks your newly added testcase.

other then that, LGTM

2024-05-30 20:16 UTC, haimgel commented
> Please update the PR description with a more recent output of your smoketest, as the provided one lacks your newly added testcase.
> 
> other then that, LGTM

Thank you. Done.

2024-05-31 07:57 UTC, c-po approved these changes

2024-05-31 07:57 UTC, c-po commented
@MergifyIo backport sagitta

2024-05-31 09:01 UTC, sever-sever approved these changes

2024-05-31 09:39 UTC, merged