T5931: Add option to append route-target when adding additional imports
vyos/vyos-1x pull request #3623
Opened 2024-06-10 15:56 UTC by l0crian1

This PR adds the ability to have multiple import/export lines of route-target configs within the VPN address-family.

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T5931
## Related PR(s)

## Component(s) name

frr, bdgd
## Proposed changes

## How to test

Prior to the change, you could only configure a single import or export line. This required you to place the route-targets in a space separated string:
```
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:1 1:2'
```
After the change, you can have those on a single line. This logic more falls in line with industry standards when configuring route-targets:
```
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:1'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:2'
```
Verification can be performed within FRR:
```
router bgp 65000 vrf Admins
 address-family ipv4 unicast
  rt vpn import 1:1 1:2
 exit-address-family
```
Configurations that contain space separated values can still exist alongside the additional config:
```
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:1'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:2'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:3 1:4'

router bgp 65000 vrf Admins
 address-family ipv4 unicast
  rt vpn import 1:1 1:2 1:3 1:4
 exit-address-family
```

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-06-10 16:16 UTC, sever-sever requested changes
CLI syntax changed and a migration script is required
```
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:1 1:2'
```
The configuration needs to be checked to see if several imports are used before changes and migrating to the new format.

2024-06-10 16:28 UTC, l0crian1 commented
> CLI syntax changed and a migration script is required
> 
> ```
> set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:1 1:2'
> ```
> 
> The configuration needs to be checked to see if several imports are used before changes and migrating to the new format.

A request was made to allow both to be used.  If both of these are allowed, then there's no need for any migration:
```
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:1'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:2'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:3 1:4'
```
This creates the following for the FRR config:
```
  rt vpn import 1:1 1:2 1:3 1:4
```
I think allowing both makes sense. This would provide familiarity for people coming from other products, but maintain familiarity for those that have been using VyOS/FRR.

2024-06-10 17:59 UTC, fett0 commented
@l0crian1  Do you test when both are equal (import/export) and add different import ?

2024-06-10 18:06 UTC, l0crian1 commented
> @l0crian1 Do you test when both are equal (import/export) and add different import ?

@fett0 Do you mean like this?
```
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn export '1:3'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:3'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:4'
```
If so, that works completely fine.
```
router bgp 65000 vrf Admins
 address-family ipv4 unicast
  rt vpn import 1:3 1:4
  rt vpn export 1:3
 exit-address-family
```
If you meant something like this:
```
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn both '1:3'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:4'
```
That'll already throw an error since both is prevented from existing alongside either import or export.

2024-06-10 18:26 UTC, fett0 commented
> > @l0crian1 Do you test when both are equal (import/export) and add different import ?
> 
> @fett0 Do you mean like this?
> 
> ```
> set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn export '1:3'
> set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:3'
> set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:4'
> ```
> 
> If so, that works completely fine.
> 
> ```
> router bgp 65000 vrf Admins
>  address-family ipv4 unicast
>   rt vpn import 1:3 1:4
>   rt vpn export 1:3
>  exit-address-family
> ```
> 
> If you meant something like this:
> 
> ```
> set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn both '1:3'
> set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:4'
> ```
> 
> That'll already throw an error since both is prevented from existing alongside either import or export.

Exactly ! yes , we've had some problems with those combinations in the past , not all the combinations are possible on FRR and for that reason , that was my question . I like the idea that you propose in this PR.

2024-06-11 06:13 UTC, c-po requested changes
> A request was made to allow both to be used. If both of these are allowed, then there's no need for any migration:

I'd recommend not to use both "styles" as this will lead to a validation hell and also is unintuitive.
As 1.4 syntax is frozen this change will only make it into 1.5 and we should make it `<multi/>` only and migrate existing configurations.

2024-06-12 14:50 UTC, l0crian1 commented
> > A request was made to allow both to be used. If both of these are allowed, then there's no need for any migration:
> 
> I'd recommend not to use both "styles" as this will lead to a validation hell and also is unintuitive. As 1.4 syntax is frozen this change will only make it into 1.5 and we should make it `<multi/>` only and migrate existing configurations.

I'm wary to make that change if not allowing both. The current syntax has existed for 3 years, and if it'll only make it into 1.5, it could be another 3 years before that is LTS. So that is potentially 3-6 years of user created tools that would need to be refactored when they move to 1.5. Could lead to a lot of customer unhappiness in the future.

2024-06-13 11:39 UTC, sever-sever commented
Change to the correct format; we won't accept both formats
Expected format:
```
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:1'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:2'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:3'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:4'
```
Unexpected format:
```
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:1'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:2'
set vrf name Admins protocols bgp address-family ipv4-unicast route-target vpn import '1:3 1:4'
```

Also, the migration script must check if several values are used.

2024-06-13 13:28 UTC, l0crian1 commented
Going to close this PR for now. The functionality for multiple route-targets already exists, so I worry this change will create more problems in the future than it solves right now.

2024-06-13 13:28 UTC, closed without merging