l2tpv3: T2352: check that the local-ip exists
vyos/vyos-1x pull request #367
Opened 2020-04-21 16:11 UTC by thomas-mangin

2020-04-21 17:26 UTC, dmbaturin approved these changes

2020-04-21 19:19 UTC, c-po commented
Why not make use of an already existing function? `vyos.validate.is_addr_assigned()` ?

2020-04-21 19:20 UTC, c-po requested changes
Why not make use of an already existing function? `vyos.validate.is_addr_assigned()` ? The wheel should not be invented multiple times.

2020-04-21 22:02 UTC, thomas-mangin commented
Agree this is duplication. I thought that validation was performing data validation (regex / checks) this is a query of the operation of the router, hence why I placed it under operational but I think you are right. opening a task to discuss.

2020-04-22 05:17 UTC, c-po commented
No Task needed - please use it. The file has been called validate b/c it is called by most verify() functions which is true here, too.

2020-04-22 16:49 UTC, thomas-mangin commented
kept the function as a separate commit. using the validate function in the code.

2020-04-22 17:05 UTC, c-po commented
This means we have unused code now? Not a fan of it.

2020-04-22 17:17 UTC, thomas-mangin commented
Just merge half the patch.

2020-04-22 17:52 UTC, c-po requested changes

2020-04-22 17:52 UTC, c-po commented on src/conf_mode/interfaces-l2tpv3.py
> +    if not l2tpv3['assigned']:
Why not call `is_addr_assigned(l2tpv3['local_address'])` here directly?

2020-04-22 17:52 UTC, c-po commented on src/conf_mode/interfaces-l2tpv3.py
> +    if l2tpv3['intf'] in l2tpv3['interfaces']:
Why use a cached version of `interfaces()``

2020-04-23 18:27 UTC, merged