t5633, t6465: tech-support report: Fixes error when op cmd interrupted, updates some system call syntax
vyos/vyos-1x pull request #3700
Opened 2024-06-21 14:05 UTC by Giggum

## Change Summary

- Add exception catching for broken pipe error to exit gracefully when user stops program output. Resolves T5633: Bug #1 and 3
- Corrects syntax for invoked "show ipv6 route bgp" command
- Updates syntax for invoked show system image version / show system image storage to new CLI syntax

Note: Bug #2 identified in T5633 is non-breaking but has not been solved in this PR.

I've narrowed the issue down to the underlying vyatta-op-cmd-wrapper shell code. I'm proposing to open a new Maniphest ticket specifically on this bug and close T5633 when PR is merged that way its still tracked and can be fixed separately.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T5633 bugs #1 and #3
https://vyos.dev/T6465

## Related PR(s)

## Component(s) name

## Proposed changes

## How to test

## Smoketest result

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-06-21 14:15 UTC, Giggum commented
**Before**
Pressing 'q' to exit during op-command output yielded a BrokenPipeError
```
vyos@vyos:~$ sh tech-support report

--------------------------------
VyOS Version and Package Changes
--------------------------------
Version:          VyOS 1.5-rolling-202310021845
Release train:    current

Built by:         autobuild@vyos.net
Built on:         Mon 02 Oct 2023 20:06 UTC
Build UUID:       51c6bd24-f741-4df2-8dc2-053ffa2e992c
Build commit ID:  86f80f99c57240

Architecture:     x86_64
Boot via:         installed image
System type:      KVM guest

Hardware vendor:  QEMU
Hardware model:   Standard PC (i440FX + PIIX, 1996)
Hardware S/N:
Hardware UUID:    b78d1414-6c0b-485c-b20a-7418cf5668c7

Copyright:        VyOS maintainers and contributors

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf>
BrokenPipeError: [Errno 32] Broken pipe
```

**After**
No error when 'q' pressed to exit running of op-command

```
vyos@vyos:~$ show tech-support report

--------------------------------
VyOS Version and Package Changes
--------------------------------
Version:          VyOS 1.5-rolling-202406060020
Release train:    current
Release flavor:   generic

Built by:         autobuild@vyos.net
Built on:         Thu 06 Jun 2024 03:11 UTC
Build UUID:       e0cb746f-5572-4aaf-8d6c-536ac82e5957
Build commit ID:  9c2ec5e3d31713

Architecture:     x86_64
Boot via:         installed image
System type:      QEMU guest

Hardware vendor:  QEMU
Hardware model:   Standard PC (Q35 + ICH9, 2009)
Hardware S/N:     
Hardware UUID:    b165d52d-5db7-4edb-990a-09d083799a23

Copyright:        VyOS maintainers and contributors

------------------
Configuration file
------------------
interfaces {
    ethernet eth0 {
        address "dhcp"
        address "2001:db8:3456::1/48"
        mtu "1492"
        offload {
            gro
            gso
vyos@vyos:~$ 
```

2024-06-24 07:37 UTC, sever-sever commented on src/op_mode/show_techsupport_report.py
> -
PEP8 E302 expected 2 blank lines
I do not think that you should delete it

2024-06-24 13:49 UTC, Giggum commented on src/op_mode/show_techsupport_report.py
> -
@sever-sever okay will add back the blank likes to make PEP8 compliant. Note: we should specify this more clearly in the contributor docs as other files in vyos-1x repo are single spaced between function definitions.

2024-06-24 14:16 UTC, sever-sever commented on src/op_mode/show_techsupport_report.py
> -
Probably not a requirement, but if it exists and was added due to PEP8 it should not be changed
Just my opinion.
Other examples where it is used and should not be changed to 1 line:

https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/container.py
https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/interfaces_virtual-ethernet.py
https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/nat64.py
https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/nat_cgnat.py
https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/qos.py
https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/service_aws_glb.py
https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/service_config-sync.py
https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/service_monitoring_zabbix-agent.py
https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/service_ipoe-server.py
...

So, the old code does not have two blank lines, but if two lines exist, it should be OK and even recommended due to PEP8, and there is no requirement to delete one line or strictly use two now.

We do not obligate users to use PEP8 only, but it is a good practice.
My IMHO

2024-06-24 16:00 UTC, Giggum commented on src/op_mode/show_techsupport_report.py
> -
Sounds good will update the format later today.

2024-06-25 05:08 UTC, sever-sever approved these changes

2024-06-27 06:26 UTC, c-po requested changes

2024-06-27 06:26 UTC, c-po commented on src/op_mode/show_techsupport_report.py
> +    execute_command(op('show system storage'), 'Show System Storage')
Please also add `show system image details`

2024-06-27 11:48 UTC, Giggum commented on src/op_mode/show_techsupport_report.py
> +    execute_command(op('show system storage'), 'Show System Storage')
@c-po will do!

2024-06-27 13:18 UTC, closed without merging