T6496: Added support for WPA-Enterprise client-mode
vyos/vyos-1x pull request #3711
Opened 2024-06-23 23:20 UTC by part1cleth1ef

## Change Summary

Added support for WPA-Enterprise client-mode
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6496

## Related PR(s)

## Component(s) name

wireless

## Proposed changes

## How to test

Configuration:
```
vyos@vyos# edit interfaces wireless wlan0
set security wpa enterprise_username 'somedomain\someuser'
set security wpa enterprise_passphrase 'somepassphrase'
vyos@vyos#
```
`show interface wireless` output:
```
vyos@vyos:~$ show interfaces wireless
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface        IP Address                        S/L  Description
---------        ----------                        ---  -----------
wlan0            -                                 A/D  SWC-24
wlan1            10.1.0.1/24                       A/D  Test AP (2.4Ghz)
wlan2            10.6.32.101/20                     u/u  SWC-5
vyos@vyos:~$
```

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation -->  it doesn't seem like the docs for wireless security document everything so I'm going to take that approach.
- [ ] I have updated the documentation accordingly

2024-06-24 06:24 UTC, c-po commented
Please use: 

* `set security wpa enterprise username`
* `set security wpa enterprise password`

instead.

When using username and password please include our common building blocks

```
#include <include/generic-password.xml.i>
#include <include/generic-username.xml.i>
```

2024-06-24 06:26 UTC, c-po requested changes

2024-06-24 06:26 UTC, c-po commented on interface-definitions/interfaces_wireless.xml.in
> +              <leafNode name="bssid">
Is BSSID required for WPA enterprise? Or is it the SSID you try to connect to?

2024-06-24 06:31 UTC, part1cleth1ef commented on interface-definitions/interfaces_wireless.xml.in
> +              <leafNode name="bssid">
Ah, this was for my testing network, felt that I might as well add it ...

2024-06-24 09:21 UTC, c-po commented on interface-definitions/interfaces_wireless.xml.in
> +              <leafNode name="bssid">
If this is required please add it in a separate PR. This way it's easier for us the backport changes to other (e.g. LTS) branches

2024-06-24 09:26 UTC, c-po approved these changes

2024-06-24 09:26 UTC, c-po commented on data/templates/wifi/wpa_supplicant.conf.j2
> +    password="{{ security.wpa.enterprise_passphrase }}"
Please use: `password="{{ security.wpa.passphrase }}"` instead.

2024-06-24 09:26 UTC, c-po commented on interface-definitions/interfaces_wireless.xml.in
> +                  <leafNode name="enterprise_passphrase">
This CLI node can be dropped, we will utilize the above `passphrase` instead.

2024-06-24 09:26 UTC, c-po commented on interface-definitions/interfaces_wireless.xml.in
> +                      <help>WPA personal shared passphrase. If you are using special characters in the WPA passphrase then single quotes are required.</help>
`<help>WPA passphrase to be used. WPA personal mode will be used if username is not specified, enterprise mode will be used otherwise.</help>`

2024-06-24 09:28 UTC, part1cleth1ef commented on interface-definitions/interfaces_wireless.xml.in
> +                      <help>WPA personal shared passphrase. If you are using special characters in the WPA passphrase then single quotes are required.</help>
Hi, the enterprise passphrase is important because the wpa personal passphrase has the regex to ensure that it is of the correct length, I don't believe it's currently possible to have a conditional check.

2024-06-24 09:28 UTC, c-po commented
So in general my requested changes can be sumarised as:

## Personal mode

* `set interfaces wireless wlan0 security wpa passphrase`

## Enterprise Mode

* `set interfaces wireless wlan0 security wpa username`
* `set interfaces wireless wlan0 security wpa passphrase`


If `username` is specified, but not `password` you should `raise ConfigError()` in `verify()`

2024-06-24 12:13 UTC, c-po commented on interface-definitions/interfaces_wireless.xml.in
> +                      <help>WPA personal shared passphrase. If you are using special characters in the WPA passphrase then single quotes are required.</help>
Conditional checks are not possible indeed. Do you think that the used regex (min 8 max 63) characters will not work for enterprise environments?

2024-06-24 12:15 UTC, part1cleth1ef commented on interface-definitions/interfaces_wireless.xml.in
> +                      <help>WPA personal shared passphrase. If you are using special characters in the WPA passphrase then single quotes are required.</help>
I can confirm that there isn't a requirement.

2024-06-24 12:25 UTC, c-po commented on interface-definitions/interfaces_wireless.xml.in
> +                      <help>WPA personal shared passphrase. If you are using special characters in the WPA passphrase then single quotes are required.</help>
Then please alter your proposed CLI as outlined in https://github.com/vyos/vyos-1x/pull/3711#issuecomment-2186035530, many thanks

2024-06-29 23:20 UTC, part1cleth1ef commented
@c-po I've completed the requested checks, additionally I didn't edit anything that would mess with the smoketests so perhaps something is temperamental?

2024-07-05 06:51 UTC, sever-sever approved these changes

2024-07-05 07:00 UTC, c-po commented
```
cpo@LR2.wue3:~$ /usr/libexec/vyos/tests/smoke/cli/test_interfaces_wireless.py
test_add_multiple_ip_addresses (__main__.WirelessInterfaceTest.test_add_multiple_ip_addresses) ... ok
test_add_single_ip_address (__main__.WirelessInterfaceTest.test_add_single_ip_address) ... ok
test_dhcp_client_options (__main__.WirelessInterfaceTest.test_dhcp_client_options) ... ok
test_dhcp_disable_interface (__main__.WirelessInterfaceTest.test_dhcp_disable_interface) ... ok
test_dhcp_vrf (__main__.WirelessInterfaceTest.test_dhcp_vrf) ... ok
test_dhcpv6_client_options (__main__.WirelessInterfaceTest.test_dhcpv6_client_options) ... ok
test_dhcpv6_vrf (__main__.WirelessInterfaceTest.test_dhcpv6_vrf) ... ok
test_dhcpv6pd_auto_sla_id (__main__.WirelessInterfaceTest.test_dhcpv6pd_auto_sla_id) ... ok
test_dhcpv6pd_manual_sla_id (__main__.WirelessInterfaceTest.test_dhcpv6pd_manual_sla_id) ... ok
test_interface_description (__main__.WirelessInterfaceTest.test_interface_description) ... ok
test_interface_disable (__main__.WirelessInterfaceTest.test_interface_disable) ... ok
test_interface_ip_options (__main__.WirelessInterfaceTest.test_interface_ip_options) ... ok
test_interface_ipv6_options (__main__.WirelessInterfaceTest.test_interface_ipv6_options) ... skipped 'not supported'
test_interface_mtu (__main__.WirelessInterfaceTest.test_interface_mtu) ... skipped 'not supported'
test_ipv6_link_local_address (__main__.WirelessInterfaceTest.test_ipv6_link_local_address) ... skipped 'not supported'
test_mtu_1200_no_ipv6_interface (__main__.WirelessInterfaceTest.test_mtu_1200_no_ipv6_interface) ... skipped 'not supported'
test_span_mirror (__main__.WirelessInterfaceTest.test_span_mirror) ... skipped 'not supported'
test_vif_8021q_interfaces (__main__.WirelessInterfaceTest.test_vif_8021q_interfaces) ... skipped 'not supported'
test_vif_8021q_lower_up_down (__main__.WirelessInterfaceTest.test_vif_8021q_lower_up_down) ... skipped 'not supported'
test_vif_8021q_mtu_limits (__main__.WirelessInterfaceTest.test_vif_8021q_mtu_limits) ... skipped 'not supported'
test_vif_8021q_qos_change (__main__.WirelessInterfaceTest.test_vif_8021q_qos_change) ... skipped 'not supported'
test_vif_s_8021ad_vlan_interfaces (__main__.WirelessInterfaceTest.test_vif_s_8021ad_vlan_interfaces) ... ok
test_vif_s_protocol_change (__main__.WirelessInterfaceTest.test_vif_s_protocol_change) ... ok
test_wireless_access_point_bridge (__main__.WirelessInterfaceTest.test_wireless_access_point_bridge) ... ok
test_wireless_add_single_ip_address (__main__.WirelessInterfaceTest.test_wireless_add_single_ip_address) ... ok
test_wireless_hostapd_config (__main__.WirelessInterfaceTest.test_wireless_hostapd_config) ... ok
test_wireless_hostapd_he_config (__main__.WirelessInterfaceTest.test_wireless_hostapd_he_config) ... ok
test_wireless_hostapd_vht_mu_beamformer_config (__main__.WirelessInterfaceTest.test_wireless_hostapd_vht_mu_beamformer_config) ... ok
test_wireless_hostapd_vht_su_beamformer_config (__main__.WirelessInterfaceTest.test_wireless_hostapd_vht_su_beamformer_config) ... ok
test_wireless_hostapd_wpa_config (__main__.WirelessInterfaceTest.test_wireless_hostapd_wpa_config) ... ok
test_wireless_security_station_address (__main__.WirelessInterfaceTest.test_wireless_security_station_address) ... ok

----------------------------------------------------------------------
Ran 31 tests in 240.015s

OK (skipped=9)

```

2024-07-05 07:00 UTC, merged

2024-09-19 06:59 UTC, sever-sever commented
@MergifyIo backport circinus