T6313: Add "NAT" to "generate" command for rule resequence
vyos/vyos-1x pull request #3715
Opened 2024-06-24 14:00 UTC by HollyGurza

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6313

## Related PR(s)

## Component(s) name

## Proposed changes

## How to test

```
generate firewall rule-resequence
generate firewall rule-resequence start 200
generate firewall rule-resequence start 200 step 100

generate nat rule-resequence
generate nat rule-resequence start 200
generate nat rule-resequence start 200 step 100

generate nat64 rule-resequence
generate nat64 rule-resequence start 200
generate nat64 rule-resequence start 200 step 100

generate nat66 rule-resequence
generate nat66 rule-resequence start 200
generate nat66 rule-resequence start 200 step 100
```
## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-06-26 07:47 UTC, sever-sever approved these changes

2024-06-27 06:29 UTC, c-po requested changes

2024-06-27 06:29 UTC, c-po commented on src/op_mode/generate_service_rule-resequence.py
> +        # Remove global-options, group and flowtable as they don't need sequencing
Could be improved to:

```python

for item in ['global-options', 'group', 'flowtable']:
    if item in config_dict['firewall']:
        del config_dict['firewall'][item]
```

2024-06-27 08:04 UTC, HollyGurza commented on src/op_mode/generate_service_rule-resequence.py
> +        # Remove global-options, group and flowtable as they don't need sequencing
done

2024-06-27 13:42 UTC, c-po approved these changes

2024-06-27 13:42 UTC, merged

2024-07-30 12:00 UTC, sever-sever commented
@MergifyIo backport circinus sagitta