ssh: T5878: Allow change the PubkeyAcceptedAlgorithms option
vyos/vyos-1x pull request #3721
Opened 2024-06-25 10:39 UTC by HollyGurza

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

## Related PR(s)

## Component(s) name

## Proposed changes

## How to test

## Smoketest result

```
vyos@vyos# python3 /usr/libexec/vyos/tests/smoke/cli/test_service_ssh.py 
test_ssh_default (__main__.TestServiceSSH.test_ssh_default) ... ok
test_ssh_dynamic_protection (__main__.TestServiceSSH.test_ssh_dynamic_protection) ... ok
test_ssh_login (__main__.TestServiceSSH.test_ssh_login) ... ok
test_ssh_multiple_listen_addresses (__main__.TestServiceSSH.test_ssh_multiple_listen_addresses) ... ok
test_ssh_ndcpp (__main__.TestServiceSSH.test_ssh_ndcpp) ... ok
test_ssh_pubkey_accepted_algorithm (__main__.TestServiceSSH.test_ssh_pubkey_accepted_algorithm) ... 
Only one of the following methods can be used at a time: append,
exclude, or override

ok
test_ssh_single_listen_address (__main__.TestServiceSSH.test_ssh_single_listen_address) ... ok
test_ssh_vrf_multi (__main__.TestServiceSSH.test_ssh_vrf_multi) ... 
VRF "red" does not exist!

ok
test_ssh_vrf_single (__main__.TestServiceSSH.test_ssh_vrf_single) ... 
VRF "mgmt" does not exist!

ok

----------------------------------------------------------------------
Ran 9 tests in 47.334s

OK
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-06-25 14:00 UTC, dmbaturin requested changes
Could you please correct the grammar in the commit message? I corrected in the PR title. I have no issues with the implementation.

2024-06-26 07:31 UTC, sever-sever approved these changes

2024-06-26 09:31 UTC, HollyGurza commented
doc PR: https://github.com/vyos/vyos-documentation/pull/1492

2024-06-27 15:08 UTC, dmbaturin requested changes
All other SSH options (key exchange, cipher...) use explicit lists of values and don't allow excluding algorithms.

We should redo the PR to only allow explicit lists as well.

2024-07-02 14:13 UTC, dmbaturin approved these changes
The smoketest failure is unrelated to the change and is safe to ignore.

2024-07-02 14:13 UTC, merged

2024-07-03 13:32 UTC, dmbaturin commented
@mergifyio backport circinus

2024-07-03 13:32 UTC, dmbaturin commented
@mergifyio backport sagitta