T6536: nat: add migration script that replaces wildcard charater
vyos/vyos-1x pull request #3749
Opened 2024-07-02 12:17 UTC by nicolas-fort

## Change Summary

Change wildcard character from + to *
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6536

## Related PR(s)

## Component(s) name

nat
## Proposed changes

## How to test

Config valid an running on 1.3:
```
vyos@vyos:~$ show version | grep Version
Version:          VyOS 1.3.7
vyos@vyos:~$ 
vyos@vyos:~$ show config comm | grep nat
set nat destination rule 10 destination port '9101'
set nat destination rule 10 inbound-interface 'eth2'
set nat destination rule 10 protocol 'tcp'
set nat destination rule 10 translation address '198.51.100.2'
set nat destination rule 200 inbound-interface 'pppoe2.+'
set nat destination rule 200 protocol 'gre'
set nat destination rule 200 translation address '203.0.113.66'
set nat source rule 10 outbound-interface 'eth0'
set nat source rule 10 translation address 'masquerade'
set nat source rule 200 outbound-interface 'l2tp+'
set nat source rule 200 protocol 'udp'
set nat source rule 200 translation port '8899'
vyos@vyos:~$ 
vyos@vyos:~$ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-N VYATTA_PRE_DNAT_HOOK
-N VYATTA_PRE_SNAT_HOOK
-A PREROUTING -j VYATTA_PRE_DNAT_HOOK
-A PREROUTING -i eth2 -p tcp -m tcp --dport 9101 -m comment --comment DST-NAT-10 -j DNAT --to-destination 198.51.100.2
-A PREROUTING -i pppoe2.+ -p gre -m comment --comment DST-NAT-200 -j DNAT --to-destination 203.0.113.66
-A POSTROUTING -j VYATTA_PRE_SNAT_HOOK
-A POSTROUTING -o eth0 -m comment --comment SRC-NAT-10 -j MASQUERADE
-A POSTROUTING -o l2tp+ -p udp -m comment --comment SRC-NAT-200 -j SNAT --to-source :8899
-A VYATTA_PRE_DNAT_HOOK -j RETURN
-A VYATTA_PRE_SNAT_HOOK -j RETURN
vyos@vyos:~$ 
```
And after upgrade:
```
vyos@upgrade-test:~$ show config comm | grep nat
set nat destination rule 10 destination port '9101'
set nat destination rule 10 inbound-interface name 'eth2'
set nat destination rule 10 protocol 'tcp'
set nat destination rule 10 translation address '198.51.100.2'
set nat destination rule 200 inbound-interface name 'pppoe2.*'
set nat destination rule 200 protocol 'gre'
set nat destination rule 200 translation address '203.0.113.66'
set nat source rule 10 outbound-interface name 'eth0'
set nat source rule 10 translation address 'masquerade'
set nat source rule 200 outbound-interface name 'l2tp*'
set nat source rule 200 protocol 'udp'
set nat source rule 200 translation port '8899'
vyos@upgrade-test:~$ sudo nft list table ip vyos_nat
table ip vyos_nat {
	chain PREROUTING {
		type nat hook prerouting priority dstnat; policy accept;
		counter packets 96 bytes 26850 jump VYOS_PRE_DNAT_HOOK
		iifname "eth2" tcp dport 9101 counter packets 0 bytes 0 dnat to 198.51.100.2 comment "DST-NAT-10"
		iifname "pppoe2.*" meta l4proto gre counter packets 0 bytes 0 dnat to 203.0.113.66 comment "DST-NAT-200"
	}

	chain POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;
		counter packets 13 bytes 776 jump VYOS_PRE_SNAT_HOOK
		oifname "eth0" counter packets 0 bytes 0 masquerade comment "SRC-NAT-10"
		oifname "l2tp*" meta l4proto udp counter packets 0 bytes 0 snat to :8899 comment "SRC-NAT-200"
	}

	chain VYOS_PRE_DNAT_HOOK {
		return
	}

	chain VYOS_PRE_SNAT_HOOK {
		return
	}
}
vyos@upgrade-test:~$
```
## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-07-02 13:36 UTC, c-po requested changes
I wonder if this should be done in a new migration script with a new version number.

*TL;DR;* 
please move the migration code to `nat/6-to-7`

As with the original bug report it seems that the NAT config is "lost in migration" I see no reason for a bump of the version number as the actual migrator `nat/6-to-7` seems to have the issue and should get the fix.

One can not upgrade from 1.4.0 -> 1.4.1 to restore the behavior which would be the only reason for a new migration version, but the user should rather re-upgrade form 1.3.x -> 1.4.1 or re-load the configuration from his 1.3.x installation on the upgraded 1.4.1 image.

2024-07-02 13:37 UTC, sarthurdev approved these changes

2024-07-02 13:38 UTC, dmbaturin reviewed
There is another place in the CLI where the plus-notation for wildcard interfaces was supported: `set zone-policy zone Foo interface 'vti+'`.

From my look in the firewall migration scripts, we don't have a similar migration there. Am I missing anything? If not, I think we need a firewall counterpart to the NAT script as well.

2024-07-03 06:19 UTC, c-po approved these changes

2024-07-03 06:48 UTC, sever-sever approved these changes

2024-07-03 14:32 UTC, c-po approved these changes

2024-07-03 14:32 UTC, merged

2024-07-03 14:33 UTC, c-po commented
@MergifyIo backport circinus sagitta