disable :T2372: disable sub-interface if parent is
vyos/vyos-1x pull request #383
Opened 2020-04-28 10:18 UTC by thomas-mangin

The patchset rewrites the vlan_to_dict code so that if an interface is disabled, all the VLAN of that interface are also disabled (admin down).

The code creates a new helper function to look for the disable option in parent interfaces.

It also refactor much of the dictionary generation for interfaces and VLANs (as they are indicatical,  and create a helper function to parse vif, vif-s, vif-c.

2020-04-29 13:10 UTC, c-po requested changes

2020-04-29 13:10 UTC, c-po commented on python/vyos/configdict.py
> +    # get the '100' in 'interfaces bonding bond0 vif-s 100'
What do you mean with this comment?

2020-04-29 13:10 UTC, c-po commented on python/vyos/configdict.py
> +    # address is no longer valid and needs to be removed from the bond
I guess bond here is just a leftover.

2020-04-29 13:10 UTC, c-po commented
I really like the idea and besides those two small comments all looks good to me. Less duplicated code!

2020-04-29 16:18 UTC, thomas-mangin commented on python/vyos/configdict.py
> +    # get the '100' in 'interfaces bonding bond0 vif-s 100'
leftover from line 109 ..

2020-04-29 16:18 UTC, thomas-mangin commented on python/vyos/configdict.py
> -        'id': conf.get_level()[-1], # get the '100' in 'interfaces bonding bond0 vif-s 100'
@c-po this left over.

2020-04-29 16:19 UTC, thomas-mangin commented on python/vyos/configdict.py
> +    # address is no longer valid and needs to be removed from the bond
Yes, this comment is also a left-over !

2020-05-01 18:30 UTC, jjakob commented
@thomas-mangin one of us will need to rebase our changes as we were working on the same code. Look at my PR.

Does this work fine regarding the link-local address code?

2020-05-02 07:56 UTC, c-po commented
@thomas-mangin can you please fox the leftovers?

2020-05-02 11:56 UTC, thomas-mangin commented
I fixed the two comments

2020-05-02 12:12 UTC, merged