T6181: Make tools for scaning ports
vyos/vyos-1x pull request #3940
Opened 2024-08-05 02:47 UTC by mkorobeinikov

Make tools for scaning ports
show ports local <--- show opened ports on a local host 
show ports <HOST_IP> <--- show opened ports and services on a remote host (scan popular ports) 
show ports all <HOST_IP> <--- show opened ports and services on a remote host (scan all ports 1-65535)
for latest version 1.5

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T6181

## Related PR(s)

## Component(s) name

## Proposed changes

## How to test

To check, needs to execute the command and get the result.
show ports local <--- show opened ports on a local host
show ports <HOST_IP> <--- show opened ports and services on a remote host (scan popular ports)
show ports all <HOST_IP> <--- show opened ports and services on a remote host (scan all ports 1-65535)

## Smoketest result

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-08-07 08:37 UTC, dmbaturin requested changes
I have nothing against a CLI for `nmap` but here both the CLI design and the implementation have multiple issues that we need to address before merging.

Malicious use isn't really a concern since all logged in users have access to everything now, `nmap` is already in the image, and when we have the op mode daemon, we can restrict this command to admins only.

My biggest concern is where this should really go. I don't think `show` is a good place. We should probably think about a generic op mode word for such commands, like `perform`.

2024-08-07 08:37 UTC, dmbaturin commented on op-mode-definitions/show-local-ports.xml.in
> +              <help>show opened ports on a local host</help>
I don't see how this shortcut is useful. Anyone who needs port scanning also knows what `127.0.0.1` and `::1` or `localhost` are and they aren't long to type. More on this later.

Besides, `netstat` or `ss` is a better way to show open ports on the local machine anyway, so this use case is rare and doesn't benefit from a shortcut.

2024-08-07 08:37 UTC, dmbaturin commented on op-mode-definitions/show-ports-all.xml.in
> +<?xml version="1.0"?>
I see no reason to split these commands in three different files. The usual reason why we split them is either that commands are unrelated or that a file is reusable. These commands are closely related and these files are not reusable.

2024-08-07 08:37 UTC, dmbaturin commented on src/op_mode/scan_all_ports.py
> +#!/usr/bin/env python3
I can't see why this script is needed. Python startup time is notoriously slow, and this script only takes one argument that could easily be appended to the base command. It doesn't provide machine-friendly op mode either (we don't have a generic "perform" or "initiate" op mode word yet).

We need to either figure out a way to make this machine-friendly and use Python or just use a shell command for the time being (I'd prefer the former).

2024-08-07 08:37 UTC, dmbaturin commented on src/op_mode/scan_localhost.py
> +#!/usr/bin/env python3
Why use two different script files if the logic is the same, just some arguments are different?

2024-08-07 08:37 UTC, dmbaturin commented on src/op_mode/scan_ports_popular.py
> +    popular_ports = [
Popular according to whom? I see no reason to have a special case for this. 21 (FTP) and 23 (telnet) are quite rare now, but it's beside the point. People who want specific ports can specify a list in the command argument.

2024-08-07 08:47 UTC, sever-sever commented on op-mode-definitions/show-local-ports.xml.in
> +              <help>show opened ports on a local host</help>
We already have `show system connections`
```
vyos@r4:~$ show system connections 
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 192.168.122.14:53       0.0.0.0:*               LISTEN     
tcp        0      0 100.64.0.14:53          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2623          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2617          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2616          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2612          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2609          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2608          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2605          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2604          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2601          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2602          0.0.0.0:*               LISTEN     
tcp        0      0 203.0.113.1:1194        0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2002          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 192.168.122.14:22       192.168.122.1:55144     ESTABLISHED
tcp6       0      0 :::10050                :::*                    LISTEN     
tcp6       0      0 ::1:2603                :::*                    LISTEN     
tcp6       0      0 ::1:2606                :::*                    LISTEN     
tcp6       0      0 ::1:2622                :::*                    LISTEN     
tcp6       0      0 :::443                  :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
udp        0      0 0.0.0.0:4784            0.0.0.0:*                          
udp        0      0 0.0.0.0:4784            0.0.0.0:*                          
udp        0      0 192.168.122.14:53       0.0.0.0:*                          
udp        0      0 100.64.0.14:53          0.0.0.0:*                          
udp        0      0 0.0.0.0:67              0.0.0.0:*                          
udp        0      0 0.0.0.0:123             0.0.0.0:*                          
udp        0      0 127.0.0.1:323           0.0.0.0:*                          
udp        0      0 0.0.0.0:3784            0.0.0.0:*                          
udp        0      0 0.0.0.0:3784            0.0.0.0:*                          
udp6       0      0 :::4784                 :::*                               
udp6       0      0 :::4784                 :::*                               
udp6       0      0 ::1:323                 :::*                               
udp6       0      0 :::3784                 :::*                               
udp6       0      0 :::3784                 :::*                               
udp6       0      0 :::3785                 :::*                               
udp6       0      0 :::3785                 :::*                               
raw        0      0 0.0.0.0:255             0.0.0.0:*               7          
raw6       0      0 :::103                  :::*                    7          
raw6       0      0 :::103                  :::*                    7          
raw6       0      0 :::58                   :::*                    7          
raw6       0      0 :::58                   :::*                    7          
raw6   10752      0 :::58                   :::*                    7          
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  3      [ ]         STREAM     CONNECTED     3433     /var/run/frr/babeld.vty
unix  2      [ ]         DGRAM      CONNECTED     10282    
unix  2      [ ]         DGRAM      CONNECTED     4783     
unix  3      [ ]         STREAM     CONNECTED     17859    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     15252    
unix  3      [ ]         STREAM     CONNECTED     6775     
unix  3      [ ]         STREAM     CONNECTED     7965     
unix  3      [ ]         STREAM     CONNECTED     3303     
unix  3      [ ]         STREAM     CONNECTED     5411     /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    20847    /run/user/1003/systemd/notify
unix  2      [ ACC ]     STREAM     LISTENING     20850    /run/user/1003/systemd/private
unix  3      [ ]         STREAM     CONNECTED     4980     
unix  2      [ ]         DGRAM      CONNECTED     10267    
unix  3      [ ]         STREAM     CONNECTED     15247    
unix  3      [ ]         STREAM     CONNECTED     2735     /var/run/frr/staticd.vty
unix  2      [ ACC ]     STREAM     LISTENING     21536    /run/openvpn/openvpn-mgmt-intf
unix  2      [ ]         DGRAM      CONNECTED     6302     
unix  3      [ ]         STREAM     CONNECTED     526      /var/run/frr/mgmtd_be.sock
unix  2      [ ]         DGRAM      CONNECTED     3396     
unix  3      [ ]         STREAM     CONNECTED     15250    
unix  3      [ ]         STREAM     CONNECTED     496      /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     6551     /var/run/frr/zserv.api
unix  3      [ ]         STREAM     CONNECTED     7960     
unix  2      [ ACC ]     STREAM     LISTENING     2443     /run/acpid.socket
unix  3      [ ]         STREAM     CONNECTED     6561     
unix  3      [ ]         STREAM     CONNECTED     506      
unix  2      [ ACC ]     STREAM     LISTENING     2445     /run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     2447     /run/uuidd/request
unix  2      [ ]         DGRAM      CONNECTED     20820    
unix  3      [ ]         STREAM     CONNECTED     15253    
unix  2      [ ]         DGRAM      CONNECTED     20607    
unix  2      [ ]         DGRAM      CONNECTED     4839     
unix  3      [ ]         DGRAM      CONNECTED     7939     
unix  3      [ ]         STREAM     CONNECTED     10364    
unix  3      [ ]         STREAM     CONNECTED     3427     
unix  3      [ ]         STREAM     CONNECTED     15248    
unix  3      [ ]         STREAM     CONNECTED     6768     
unix  3      [ ]         STREAM     CONNECTED     6558     
unix  3      [ ]         STREAM     CONNECTED     5416     /run/systemd/journal/stdout
unix  2      [ ]         DGRAM      CONNECTED     519      
unix  3      [ ]         STREAM     CONNECTED     20852    
unix  3      [ ]         STREAM     CONNECTED     6771     
unix  2      [ ]         DGRAM      CONNECTED     10315    
unix  3      [ ]         STREAM     CONNECTED     6556     
unix  3      [ ]         STREAM     CONNECTED     9837     /var/run/frr/pim6d.vty
unix  2      [ ACC ]     STREAM     LISTENING     504      /var/run/frr/watchfrr.vty
unix  3      [ ]         STREAM     CONNECTED     4977     
unix  2      [ ]         DGRAM      CONNECTED     3413     
unix  3      [ ]         STREAM     CONNECTED     15245    
unix  3      [ ]         STREAM     CONNECTED     17139    
unix  2      [ ]         DGRAM      CONNECTED     10304    
unix  2      [ ACC ]     STREAM     LISTENING     6517     /var/run/frr/zserv.api
unix  2      [ ACC ]     STREAM     LISTENING     6519     /var/run/frr/zebra.vty
unix  2      [ ACC ]     STREAM     LISTENING     3418     /var/run/frr/mgmtd_fe.sock
unix  3      [ ]         STREAM     CONNECTED     4802     /run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     18914    /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     3419     /var/run/frr/mgmtd_be.sock
unix  2      [ ]         DGRAM                    20615    /run/chrony/chronyd.sock
unix  2      [...]

2024-08-09 03:34 UTC, mkorobeinikov commented
Guys, thanks for the comments. I'm working on fixing the code and design.

2024-08-09 08:49 UTC, dmbaturin commented on op-mode-definitions/show-local-ports.xml.in
> +              <help>show opened ports on a local host</help>
Yes, my point exactly. If there are reason to nmap localhost, they must be to specific and rare that a shortcut isn't useful

2024-08-21 04:56 UTC, dmbaturin commented
Note: we do have `execute` top level op mode word now, thanks to the work of @natali-rs1985, so this PR can be adjusted to use that word.

2024-09-03 08:42 UTC, dmbaturin commented
This PR has implementation issues and it's abandoned by the author now. @natali-rs1985 will work on a new implementation, in the new `execute` command family.

2024-09-03 08:42 UTC, closed without merging