dhclient: T6667: Added workaround for communication with FRR
vyos/vyos-1x pull request #4002
Opened 2024-08-21 19:08 UTC by zdc

## Change Summary

Added workaround for communication with FRR

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6667

## Related PR(s)

## Component(s) name

dhclient

## Proposed changes

To increase the chance for dhclient to configure routes in FRR, added a workaround. Now 10 attempts are performed with 1 second delay and only after this dhclient gives up.

## How to test

Unfortunately, the issue is hard to catch, using VyOS config scripts only, without explicitly forcing it.
More details about reproducing are in: https://vyos.dev/T6667

## Smoketest result

N/A

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-08-22 09:52 UTC, dmbaturin requested changes
Looks good, I think log message wording can be improved, though.

2024-08-22 09:52 UTC, dmbaturin commented on src/etc/dhcp/dhclient-enter-hooks.d/03-vyos-ipwrapper
> +            logmsg info "Command was configured successfully via vtysh: \"$1\""
Command was _executed_ successfully?

2024-08-22 09:52 UTC, dmbaturin commented on src/etc/dhcp/dhclient-enter-hooks.d/03-vyos-ipwrapper
> +    logmsg error "Failed to configure command via vtysh after 10 attempts: \"$1\""
I'd also say "Failed to _execute_ command $1 via vtysh after 10 attempts" here.

2024-08-22 10:34 UTC, zdc commented on src/etc/dhcp/dhclient-enter-hooks.d/03-vyos-ipwrapper
> +            logmsg info "Command was configured successfully via vtysh: \"$1\""
If you say so. It was "executed" before the `-c "conf t" -c ` was added to it. :)

2024-08-22 11:11 UTC, sever-sever approved these changes

2024-08-24 08:06 UTC, dmbaturin approved these changes

2024-08-24 08:06 UTC, merged

2024-09-26 13:22 UTC, zdc commented
@Mergifyio backport sagitta

2024-09-26 13:23 UTC, zdc commented
@Mergifyio backport circinus