T6647: firewall. Introduce patch for accepting invalid ARP and DHCP
vyos/vyos-1x pull request #4018
Opened 2024-08-26 18:23 UTC by nicolas-fort

## Change Summary

Introduce patch for accepting invalid ARP and DHCP in stateful bridge firewall. This patch is needed because ARP and DHCP are marked as invalid connections.
Also, add ehternet-type matcher in bridge firewall.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6647

## Related PR(s)

## Component(s) name

firewall
## Proposed changes

At first  we tried accepting ARP packets with the new option `ehternet-type`. This was not enough because if global state policies were configured, this rules were evaluated before custom rules, so ARP replies, which are flaged as INVALID still got droped.
So now there's a new global-option for bridge firewall, which accepts invalid connections for the two known scenarios where this connections are marked as invalid:
 * For DHCP: when bridge is configured as a DHCP server
 * For ARP. 

## How to test

```
vyos@bri# run show config comm | grep firewall
set firewall bridge prerouting filter rule 10 action 'accept'
set firewall bridge prerouting filter rule 10 ethernet-type 'arp'
set firewall global-options apply-to-bridged-traffic invalid-connections
set firewall global-options state-policy established action 'accept'
set firewall global-options state-policy invalid action 'drop'
set firewall global-options state-policy related action 'accept'
[edit]
vyos@bri# 
```
And nftables output:
```
vyos@bri# sudo nft -s list table bridge vyos_filter
table bridge vyos_filter {
        chain VYOS_FORWARD_filter {
                type filter hook forward priority filter; policy accept;
                jump VYOS_STATE_POLICY
                counter accept comment "FWD-filter default-action accept"
        }

        chain VYOS_INPUT_filter {
                type filter hook input priority filter; policy accept;
                jump VYOS_STATE_POLICY
                counter accept comment "INP-filter default-action accept"
        }

        chain VYOS_OUTPUT_filter {
                type filter hook output priority filter; policy accept;
                ct state invalid udp sport 67 udp dport 68 counter accept
                ct state invalid ether type arp counter accept
                jump VYOS_STATE_POLICY
                counter accept comment "OUT-filter default-action accept"
        }

        chain VYOS_PREROUTING_filter {
                type filter hook prerouting priority filter; policy accept;
                ether type arp counter accept comment "bri-PRE-filter-10"
                counter accept comment "PRE-filter default-action accept"
        }

        chain VYOS_STATE_POLICY {
                ct state established counter accept
                ct state invalid counter drop
                ct state related counter accept
                return
        }
}
[edit]
vyos@bri# 
```

## Smoketest result

test_firewall.py --> OK

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-08-26 18:31 UTC, c-po approved these changes

2024-08-26 18:32 UTC, c-po requested changes

2024-08-26 18:32 UTC, c-po commented on interface-definitions/include/firewall/match-ether-type.xml.i
> +      <format>8021q</format>
Probably should use `802.1q` and `802.1ad` to be inline with the standards

2024-08-26 18:32 UTC, c-po commented on interface-definitions/include/firewall/match-ether-type.xml.i
> +      <format>ip6</format>
We usually call it ipv6

2024-08-26 18:33 UTC, c-po commented on interface-definitions/include/firewall/match-ether-type.xml.i
> +      <format>8021q</format>
I know it might need transcoding in the Python scripts but the CLI exported to the user looks more consistent.

2024-08-27 08:40 UTC, sever-sever commented on python/vyos/firewall.py
> +        if ether_type == '802.1q':
Just for notice, if you have several `if/elif` you can use maps
for example
```
ether_type_mapping = {
    '802.1q': '8021q',
    '802.1ad': '8021ad',
    'ipv6': 'ip6',
    'ipv4': 'ip'
}

if 'ethernet_type' in rule_conf:
    ether_type = rule_conf['ethernet_type']
    operator = '!=' if ether_type.startswith('!') else ''
    
    ether_type = ether_type.lstrip('!')
    ether_type = ether_type_mapping.get(ether_type, ether_type)
    
    output.append(f'ether type {operator} {ether_type}')

```

2024-08-27 16:02 UTC, c-po approved these changes

2024-08-27 16:02 UTC, c-po commented on interface-definitions/include/firewall/match-ether-type.xml.i
> +      <list>802.1q 802.1ad arp ipv4 ipv6 </list>
Stray Whitespace at the end

2024-08-29 10:30 UTC, sarthurdev approved these changes

2024-09-02 11:01 UTC, merged