T861: op-mode: initial parts for UEFI secure boot CLI
vyos/vyos-1x pull request #4020
Opened 2024-08-26 18:30 UTC by c-po

## Change Summary

Add `show secure-boot [keys]` CLI command together with `install mok` CLI command.

Current SB state is displayed too via `show ver`

```
vyos@vyos:~$ show ver
...
Architecture:     x86_64
Boot via:         installed image
System type:      KVM guest
Secure Boot:      enabled
...
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T861

## Related PR(s)

## Component(s) name

Secure Boot / UEFI

## Proposed changes

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-09-04 07:28 UTC, sever-sever approved these changes

2024-09-15 14:37 UTC, dmbaturin approved these changes

2024-09-15 22:09 UTC, sarthurdev requested changes

2024-09-15 22:09 UTC, sarthurdev commented on python/vyos/utils/system.py
> +    if not is_uefi_system:
needs to call the function? `is_uefi_system()`

2024-09-16 15:32 UTC, sarthurdev approved these changes

2024-09-16 15:33 UTC, merged

2024-10-07 01:04 UTC, fatpelt commented on python/vyos/utils/system.py
> +    tmp = cmd('mokutil --sb-state')
This line throws an exception for devices that do not support secure-boot.  should this be wrapped in a try?

```
# show ver
Traceback (most recent call last):
  File "/usr/libexec/vyos/op_mode/version.py", line 91, in <module>
    res = vyos.opmode.run(sys.modules[__name__])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vyos/opmode.py", line 271, in run
    res = func(**args)
          ^^^^^^^^^^^^
  File "/usr/libexec/vyos/op_mode/version.py", line 81, in show
    version_data = _get_raw_data(funny=funny)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/libexec/vyos/op_mode/version.py", line 67, in _get_raw_data
    if get_secure_boot_state():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vyos/utils/system.py", line 148, in get_secure_boot_state
    tmp = cmd('mokutil --sb-state')
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vyos/utils/process.py", line 155, in cmd
    raise OSError(code, feedback)
OSError: [Errno 255] failed to run command: mokutil --sb-state
returned:
exit code: 255

# mokutil --sb-state
This system doesn't support Secure Boot
```