T6681: Add option for SLAAC to support suppress Interval Advertisement on RA Packet
vyos/vyos-1x pull request #4022
Opened 2024-08-27 13:59 UTC by rgwan

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T6681

## Related PR(s)

## Component(s) name

## Proposed changes

MikroTik's IPv6 SLAAC client has a bug, when the RA sent by router (e.g.) VyOS has Interval field, it can't obtain an address correctly from the router.

So I'm working on a patch which allows VyOS don't send Interval advertisement on RA packet.

e.g. the command line will be:

```
set service router-advert interface <some int> no-send-interval
```

## How to test

Run the command I described above, and use Wireshark to capture packet from router, and the 'Interval Advertisement' field in RA packet is gone.

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-08-27 16:14 UTC, c-po requested changes
Thank you for the contribution. This is a behavioral change to VyOS, as in the past both options got set with a single command `set service router-advert interface <some int> no-send-advert`.

To preserve existing behavior a migration script is mandatory which will set the new CLI node once it detects that an interface has `no-send-advert` defined. This will preserve old behavior and add support for users to individually toggle the fields.

2024-08-28 01:04 UTC, rgwan commented
> Thank you for the contribution. This is a behavioral change to VyOS, as in the past both options got set with a single command `set service router-advert interface <some int> no-send-advert`.
> 
> To preserve existing behavior a migration script is mandatory which will set the new CLI node once it detects that an interface has `no-send-advert` defined. This will preserve old behavior and add support for users to individually toggle the fields.

In fact, when `no-send-advert` is set, the RADVD daemon will not send any router-advertise to the interface, so `AdvIntervalOpt` option will be omitted by RADVD daemon in this situation.

I don't think we need a migration script for it, it didn't changes old behavior of `no-send-advert`.

2024-08-30 12:00 UTC, rgwan commented
@c-po  So, any further question about this PR?

2024-08-31 19:19 UTC, c-po commented
> In fact, when `no-send-advert` is set, the RADVD daemon will not send any router-advertise to the interface, so `AdvIntervalOpt` option will be omitted by RADVD daemon in this situation.
> 
> I don't think we need a migration script for it, it didn't changes old behavior of `no-send-advert`.

Confirmed:

https://github.com/radvd-project/radvd/blob/f2de4764559e102fe8492520be328858af0f964d/send.c#L880-L885

RADVD code bails out early if  `no-send-advert` is set, thos omitting any other option and not adding a need for a migrator.

2024-08-31 19:20 UTC, c-po approved these changes

2024-09-01 05:55 UTC, c-po commented
@MergifyIo backport sagitta circinus

2024-09-01 06:11 UTC, c-po commented
Added smoketests for the new option


```
cpo@LR2.wue3:~$ /usr/libexec/vyos/tests/smoke/cli/test_service_router-advert.py
test_advsendadvert_advintervalopt (__main__.TestServiceRADVD.test_advsendadvert_advintervalopt) ... ok
test_common (__main__.TestServiceRADVD.test_common) ... ok
test_deprecate_prefix (__main__.TestServiceRADVD.test_deprecate_prefix) ... ok
test_dns (__main__.TestServiceRADVD.test_dns) ... ok
test_nat64prefix (__main__.TestServiceRADVD.test_nat64prefix) ... ok
test_rasrcaddress (__main__.TestServiceRADVD.test_rasrcaddress) ... ok
test_route (__main__.TestServiceRADVD.test_route) ... ok

----------------------------------------------------------------------
Ran 7 tests in 19.518s

OK
```

2024-09-02 10:59 UTC, dmbaturin approved these changes

2024-09-02 10:59 UTC, merged