pppoe-service: T6685: Possibility of any services name or blank in pppoe
vyos/vyos-1x pull request #4041
Opened 2024-09-10 09:37 UTC by natali-rs1985

## Change Summary

Added options:
```
accept-any-service
accept-blank-service
```
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6685
## Related PR(s)

## Component(s) name

pppoe-server
## Proposed changes

## How to test

```
set service pppoe-server authentication local-users username user1 password 'user1'
set service pppoe-server authentication mode 'local'
set service pppoe-server client-ip-pool first range '100.64.0.1-100.64.0.100'
set service pppoe-server default-pool 'first'
set service pppoe-server gateway-address '100.64.0.1'
set service pppoe-server interface eth1

set service pppoe-server accept-blank-service
set service pppoe-server accept-any-service

commit

vyos@vyos# cat /run/accel-pppd/pppoe.conf | grep -service
accept-any-service=1
accept-blank-service=1
```
## Smoketest result

```
vyos@vyos# sudo nano /usr/libexec/vyos/tests/smoke/cli/test_service_pppoe-server.py
[edit]
vyos@vyos# python3 /usr/libexec/vyos/tests/smoke/cli/test_service_pppoe-server.py
test_accel_ipv4_pool (__main__.TestServicePPPoEServer.test_accel_ipv4_pool) ... ok
test_accel_ipv6_pool (__main__.TestServicePPPoEServer.test_accel_ipv6_pool) ... ok
test_accel_limits (__main__.TestServicePPPoEServer.test_accel_limits) ... ok
test_accel_local_authentication (__main__.TestServicePPPoEServer.test_accel_local_authentication) ... ok
test_accel_log_level (__main__.TestServicePPPoEServer.test_accel_log_level) ... ok
test_accel_name_servers (__main__.TestServicePPPoEServer.test_accel_name_servers) ... ok
test_accel_next_pool (__main__.TestServicePPPoEServer.test_accel_next_pool) ... ok
test_accel_ppp_options (__main__.TestServicePPPoEServer.test_accel_ppp_options) ... ok
test_pppoe_server_shaper (__main__.TestServicePPPoEServer.test_pppoe_server_shaper) ... ok
test_pppoe_server_vlan (__main__.TestServicePPPoEServer.test_pppoe_server_vlan) ... ok

----------------------------------------------------------------------
Ran 19 tests in 139.655s

OK
[edit]
```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-09-10 10:02 UTC, sever-sever approved these changes

2024-09-10 13:14 UTC, dmbaturin requested changes

2024-09-10 13:14 UTC, dmbaturin commented on interface-definitions/service_pppoe-server.xml.in
> +          <leafNode name="accept-blank-service">
Should we also clarify here that it's about PADR, like in the help string for `accept-any-service`?

2024-09-12 12:49 UTC, dmbaturin approved these changes
I might use the same wording in both help strings, but we probably need to agree on a policy for that.

2024-09-12 12:49 UTC, merged