T6884: adds mtu option for container networks
vyos/vyos-1x pull request #4195
Opened 2024-11-18 07:46 UTC by nvollmar

## Change Summary
Add new config option to set mtu on container networks

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)
* https://vyos.dev/T6884

## Related PR(s)

## Component(s) name
container

## Proposed changes
Add new config option to set mtu on container networks

## How to test
Set up a container network
```
set container network example prefix 172.20.0.0/16
set container network example mtu 1280
```
Then verify network with
```
sudo podman network inspect example
```
that the configuration has mtu set
```
          ....
          "options": {
               "mtu": "1280"
          },
          ....
```

## Smoketest result
```
vyos@vyos:~$ /usr/libexec/vyos/tests/smoke/cli/test_container.py
test_api_socket (__main__.TestContainer.test_api_socket) ... ok
test_basic (__main__.TestContainer.test_basic) ... ok
test_cpu_limit (__main__.TestContainer.test_cpu_limit) ... ok
test_dual_stack_network (__main__.TestContainer.test_dual_stack_network) ... ok
test_ipv4_network (__main__.TestContainer.test_ipv4_network) ... ok
test_ipv6_network (__main__.TestContainer.test_ipv6_network) ... ok
test_network_mtu (__main__.TestContainer.test_network_mtu) ... ok
test_no_name_server (__main__.TestContainer.test_no_name_server) ... ok
test_uid_gid (__main__.TestContainer.test_uid_gid) ... ok
```

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [X] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-11-18 10:38 UTC, sever-sever requested changes

2024-11-18 10:38 UTC, sever-sever commented on interface-definitions/container.xml.in
> +          #include <include/interface/mtu-68-1500.xml.i>
It is possible to set MTU 16000

```
vyos@r14:~$ sudo podman network create pod-net3 --opt mtu=16000
pod-net3
vyos@r14:~$ 
vyos@r14:~$ sudo podman network inspect pod-net3
[
     {
          "name": "pod-net3",
          "id": "6b774a3edb8a8c1d301d1dcbce721bab4e116ed5f107c817ceb9d8c2611d8978",
          "driver": "bridge",
          "network_interface": "podman2",
          "created": "2024-11-18T10:37:44.832040746Z",
          "subnets": [
               {
                    "subnet": "10.89.1.0/24",
                    "gateway": "10.89.1.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "options": {
               "mtu": "16000"
          },
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
vyos@r14:~$ 
```

2024-11-18 10:40 UTC, nvollmar commented on interface-definitions/container.xml.in
> +          #include <include/interface/mtu-68-1500.xml.i>
👍 switched to `mtu-68-16000.xml.i`

2024-11-18 10:41 UTC, sever-sever approved these changes

2024-11-19 10:25 UTC, dmbaturin approved these changes

2024-11-19 10:26 UTC, merged