multicast: T6920: static multicast routing throws TypeError
vyos/vyos-1x pull request #4210
Opened 2024-11-27 17:05 UTC by natali-rs1985

## Change Summary

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6920
## Related PR(s)

## Component(s) name

protocols static multicast
## Proposed changes

## How to test

```
vyos@vyos# set protocols static multicast route 192.168.0.0/16 next-hop 1.2.3.4
[edit]
vyos@vyos# commit
[ protocols static multicast ]
192.168.0.0/16 not a multicast network

[[protocols static multicast]] failed
Commit failed
[edit]
```
## Smoketest result

```
vyos@vyos# python3 /usr/libexec/vyos/tests/smoke/cli/test_protocols_st
test_protocols_static_arp.py        test_protocols_static_multicast.py  test_protocols_static.py
[edit]
vyos@vyos# python3 /usr/libexec/vyos/tests/smoke/cli/test_protocols_static_multicast.py
test_01_static_multicast (__main__.TestProtocolsStaticMulticast.test_01_static_multicast) ... ok

----------------------------------------------------------------------
Ran 1 test in 7.929s

OK
```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-11-27 17:28 UTC, sever-sever approved these changes

2024-11-27 19:20 UTC, sarthurdev requested changes

2024-11-27 19:20 UTC, sarthurdev commented on src/conf_mode/protocols_static_multicast.py
> +    for mroute in mroute['mroute']:
Perhaps another name than 'mroute' should be used? It is overriding the function parameter.

2024-11-27 22:14 UTC, sarthurdev approved these changes

2024-11-28 06:14 UTC, c-po requested changes

2024-11-28 06:14 UTC, c-po commented on src/conf_mode/protocols_static_multicast.py
> +            raise ConfigError(mcast_route + " not a multicast network")
Please use f'ormat string instead.

2024-11-28 11:43 UTC, c-po approved these changes

2024-11-28 17:43 UTC, merged