ids: T6919: remove Fastnetmon from the base system
vyos/vyos-1x pull request #4214
Opened 2024-12-02 14:32 UTC by dmbaturin

## Change Summary

Remove Fastnetmon from the base system. It will eventually be moved to an addon.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): feature removal.

## Related Task(s)

## Related PR(s)

## Component(s) name

IDS.

## Proposed changes

There is no deep integration into the firewall subsystem for Fastnetmon and there doesn't seem to be any interest in improving the VyOS integration from its maintainers. If it's not getting a deep integration, it's better to move it to an optional addon.

## How to test

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-12-12 19:32 UTC, sever-sever commented
I’m disagree with this decision.
At least until we do not have addon.
And I do not see any alternative options for this feature.

2025-01-20 11:00 UTC, sever-sever requested changes

2025-01-20 11:00 UTC, sever-sever commented on op-mode-definitions/monitor-log.xml.in
> -          <node name="ids">
If you still want to drop it, you have to add `migration scripts`

2025-04-14 15:13 UTC, sever-sever requested changes

2025-04-14 15:13 UTC, sever-sever commented on debian/vyos-1x.postinst
> +        /etc/networks_list /etc/networks_whitelist
This is a part of the fastnetmon package and could be removed
There were options for fastnemon networks list to limit processing interesting destination prefixes.

2025-04-14 15:13 UTC, sever-sever commented on src/tests/test_utils_network.py
> +        #self.assertTrue(vyos.utils.network.is_addr_assigned('::1'))
What is wrong with it? Why do you skip this check?
Probably not related to this PR

2025-04-14 15:13 UTC, sever-sever commented on src/migration-scripts/ids/1-to-2
> +        config.delete(base)
Do we need a `1-to-2` migration, or can we make this change in the `0-to-1` migration instead?
Because in my understanding, if you add a new migration, it should be declared/marked here https://github.com/vyos/vyos-1x/blob/f06087155cb6c9e8d7f39d1ac41eef8f1a2cf288/interface-definitions/include/version/ids-version.xml.i#L2

2025-04-14 15:48 UTC, dmbaturin commented on debian/vyos-1x.postinst
> +        /etc/networks_list /etc/networks_whitelist
Removed that line.

2025-04-14 15:48 UTC, dmbaturin commented on src/tests/test_utils_network.py
> +        #self.assertTrue(vyos.utils.network.is_addr_assigned('::1'))
Yes, that's completely spurious. Removed.

2025-04-14 15:50 UTC, dmbaturin commented on src/migration-scripts/ids/1-to-2
> +        config.delete(base)
Good catch, that was a file missing from the PR! I've included it now.

2025-04-14 16:01 UTC, sever-sever approved these changes
This PR removes everything related to Fastnemon files/features.
The code/scripts/migrations look good.

But I still do not think that it is a good idea (my IMHO).

2025-04-15 14:50 UTC, jestabro approved these changes
Approved.

2025-04-15 14:51 UTC, merged

2025-04-15 14:51 UTC, c-po approved these changes
"De-"implementation of the feature looks correct