T6641: Add vyos-network-event-logger Service
vyos/vyos-1x pull request #4216
Opened 2024-12-03 09:25 UTC by HollyGurza

The service parses and logs network events for improved monitoring and diagnostics. Supported event types include:

- `RTM_NEWROUTE`, `RTM_DELROUTE`
- `RTM_NEWLINK`, `RTM_DELLINK`
- `RTM_NEWADDR`, `RTM_DELADDR`
- `RTM_NEWNEIGH`, `RTM_DELNEIGH`, `RTM_GETNEIGH`
- `RTM_NEWRULE`, `RTM_DELRULE`

Added operational mode commands for filtered log retrieval:
- `show log network-event <event-type> <interface>`: Retrieve logs filtered by event type and interface.
- `show interfaces <type> <name> event-log <event-type>`: Display interface-specific logs filtered by event type.

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6641
## Related PR(s)

## Component(s) name

## Proposed changes

log examples:
```
run show log network-event interface eth1

Dec 03 09:23:34 vyos-network-event-logger[21158]: [LINK]   3: eth1:  <BROADCAST,MULTICAST>  mtu 1500  qdisc fq_codel  state DOWN  group 0  link/ether 0c:89:0a:2e:00:01  brd ff:ff:ff:ff:ff:ff  [altname enp0s4] [altname ens4]
Dec 03 09:23:34 vyos-network-event-logger[21158]: [NEIGH]  Deleted  ff02::16  dev eth1 lladdr 33:33:00:00:00:16    NOARP
Dec 03 09:23:40 vyos-network-event-logger[21158]: [LINK]   3: eth1:  <BROADCAST,MULTICAST,UP,LOWER_UP>  mtu 1500  qdisc fq_codel  state UP  group 0  link/ether 0c:89:0a:2e:00:01  brd ff:ff:ff:ff:ff:ff  [altname enp0s4] [altname ens4]
Dec 03 09:23:40 vyos-network-event-logger[21158]: [ROUTE]  broadcast 10.0.0.255 tos 0  dev eth1 table local proto kernel scope link src 10.0.0.1
Dec 03 09:23:40 vyos-network-event-logger[21158]: [ROUTE]  unicast 10.0.0.0/24 tos 0  dev eth1 table main proto kernel scope link src 10.0.0.1
Dec 03 09:23:40 vyos-network-event-logger[21158]: [ROUTE]  multicast ff00::/8 tos 0  dev eth1 table local proto kernel metric 256  pref medium
```
## How to test

To check the correct parsing you can use logs from `ip monitor label`
configure network-event logger to listen events:
```
conf
set service monitoring network-event event addr
set service monitoring network-event event link
set service monitoring network-event event neigh
set service monitoring network-event event route
set service monitoring network-event event rule
commit
```
you can use IP utils to manipulate the interface and check logs or use some `set interface *` commands e.g.

```
generate pki ca install test_ca

conf
set interfaces bonding bond1 address 11.11.11.11/32
commit
run show interfaces bonding bond1 event-log
del interfaces bonding bond1
commit

set interfaces bridge br1 address 11.11.11.11/32
commit
run show interfaces bridge br1 event-log
del interfaces bridge br1
commit

set interfaces dummy dum1 address 11.11.11.11/32
commit
run show interfaces dummy dum1  event-log
del interfaces dummy dum1
commit

sudo ip link set down dev eth1
sudo ip link set up dev eth1
run show interfaces ethernet eth1 event-log

set interfaces geneve gnv1  address 11.11.11.11/32
set interfaces geneve gnv1 remote 127.0.0.1
set interfaces geneve gnv1 vni 10
commit
run show interfaces geneve gnv1 event-log
del interfaces geneve gnv1
commit

set interfaces input ifb1 redirect eth1
commit
run show interfaces input ifb1  event-log
del interfaces input ifb1
commit

set interfaces loopback lo address 11.11.11.11/32
commit
run show interfaces loopback lo event-log
del interfaces loopback lo address
commit

set interfaces macsec macsec1 address '11.11.11.11/32'
set interfaces macsec macsec1 security cipher 'gcm-aes-128'
set interfaces macsec macsec1 source-interface 'eth1'
commit
run show interfaces macsec macsec1 event-log
del interfaces macsec macsec1
commit

set interfaces pseudo-ethernet peth1 address '11.11.11.11/32'
set interfaces pseudo-ethernet peth1 source-interface 'eth1'
commit
run show interfaces pseudo-ethernet peth1 event-log
del interfaces pseudo-ethernet peth1
commit

set interfaces sstpc sstpc1 server '127.0.0.1'
set interfaces sstpc sstpc1 ssl ca-certificate 'test_ca'
commit
run show interfaces sstpc sstpc1 event-log
del interfaces sstpc sstpc1
commit

set interfaces tunnel tun1 address '11.11.11.11/32'
set interfaces tunnel tun1 encapsulation 'gre'
set interfaces tunnel tun1 source-interface 'eth1'
commit
run show interfaces tunnel tun1 event-log
del interfaces tunnel tun1
commit

set interfaces virtual-ethernet veth1 address '11.11.11.11/32'
set interfaces virtual-ethernet veth1 peer-name 'veth2'
set interfaces virtual-ethernet veth2 peer-name 'veth1'
commit
run show interfaces virtual-ethernet veth1 event-log
del interfaces virtual-ethernet veth1
del interfaces virtual-ethernet veth2
commit

set interfaces vti vti1 address 11.11.11.11/32
commit
run show interfaces vti vti1 event-log
del interfaces vti vti1
commit

set interfaces vxlan vxlan1 address '11.11.11.11/32'
set interfaces vxlan vxlan1 mtu '1400'
set interfaces vxlan vxlan1 source-interface 'eth1'
set interfaces vxlan vxlan1 vni '12'
commit
run show interfaces vxlan vxlan1 event-log
del interfaces vxlan
commit
```

## Smoketest result

```
vyos@vyos:~$ python3 /usr/libexec/vyos/tests/smoke/cli/test_service_monitoring_network_event.py 
test_network_event_log (__main__.TestMonitoringNetworkEvent.test_network_event_log) ... ok

----------------------------------------------------------------------
Ran 1 test in 6.043s

OK
```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-12-10 14:34 UTC, jestabro commented
As mentioned on Slack, this should be rebased over current and pushed to sync with the changes in
https://github.com/vyos/vyos-1x/pull/4226
https://github.com/vyos/vyos-build/pull/824

A local build of this PR confirms a successful build and smoketests.

2024-12-19 19:22 UTC, c-po commented
Is there any downside not enabling this service by default?

2024-12-20 07:33 UTC, HollyGurza commented
> Is there any downside not enabling this service by default?

at least, you must remember to turn it on to analyze some situations and reproduce these? otherwise logs will not stored.
I'm not sure if this should be enabled by default

2025-01-06 14:08 UTC, dmbaturin requested changes
I left a bunch of suggestions for improvement.

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +  <command>journalctl --no-hostname --boot --unit vyos-network-event-logger.service | grep "\b$4\b"</command>
`journalctl` has a built-in `--grep=` option that supports PCRE, so I think there is no need to use an external filter here. The built-in will be faster and will preserve coloring, etc.

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +      <command>journalctl --no-hostname --boot --unit vyos-network-event-logger.service | grep "$(echo "\[$6\]" | tr '[:lower:]' '[:upper:]')" | grep "\b$4\b"</command>
The journalctl command is duplicated a lot here. Should we make it a script?

I'm also not convinced about the value of the `tr` call here.

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +    <help>Show interface network event log</help>
```suggestion
    <help>Show network interface change event log</help>
```

2025-01-06 14:08 UTC, dmbaturin commented on interface-definitions/service_monitoring_network_event.xml.in
> +      <node name="monitoring">
We should probably make a skeleton node for monitoring and include everything else into it, although it's a topic for a different PR.

2025-01-06 14:08 UTC, dmbaturin commented on src/services/vyos-network-event-logger
> +# https://github.com/torvalds/linux/blob/adc218676eef25575469234709c2d87185ca223a/include/uapi/linux/neighbour.h#L46
Should we move the constants to a separate module? There may be more places in the future where they might be useful for handling netlink events.

2025-01-06 14:08 UTC, dmbaturin commented on interface-definitions/service_monitoring_network_event.xml.in
> +                      <help>Log link status changes events</help>
```suggestion
                      <help>Log link status change events</help>
```

2025-01-06 14:08 UTC, dmbaturin commented on interface-definitions/service_monitoring_network_event.xml.in
> +              <leafNode name="queue-size">
I'm always uneasy about such parameters. Why is the upper limit exactly `999999`? `queue.Queue`'s `maxsize` can be any integer, I see no reason to introduce an artificial limit.

2025-01-06 14:08 UTC, dmbaturin commented on interface-definitions/service_monitoring_network_event.xml.in
> +                  <help>Set log-level. Log must be enable</help>
What exactly does "Log must be enable" (sic) mean here?

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +        <help>Show log for link network events</help>
```suggestion
        <help>Show log for network link events</help>
```

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +        <help>Show log for addr network events</help>
```suggestion
        <help>Show log for network address events</help>
```

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +        <help>Show log for neigh network events</help>
```suggestion
        <help>Show log for neighbor table events</help>
```

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +        <help>Show log for rule network events</help>
```suggestion
        <help>Show log for PBR rule change events</help>
```

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/show-log.xml.in
> +                  <help>Show log for route network events</help>
```suggestion
                  <help>Show log for route events</help>
```

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/show-log.xml.in
> +                  <help>Show log for link network events</help>
```suggestion
                  <help>Show log for network link events</help>
```

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/show-log.xml.in
> +                  <help>Show log for addr network events</help>
```suggestion
                  <help>Show log for network address events</help>
```

2025-01-06 14:08 UTC, dmbaturin commented on op-mode-definitions/show-log.xml.in
> +                  <help>Show log for neigh network events</help>
```suggestion
                  <help>Show log for neighbor table events</help>
```

2025-01-08 19:44 UTC, c-po commented
Another reason for having this running always in the background:

From FRR `show interface eth0`
```
Interface eth0 is up, line protocol is up
  Link ups:       1    last: 2025/01/08 08:03:49.20
  Link downs:     0    last: (never)
```

2025-01-14 03:21 UTC, HollyGurza commented on op-mode-definitions/show-log.xml.in
> +                  <help>Show log for addr network events</help>
fixed

2025-01-16 10:15 UTC, HollyGurza commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +  <command>journalctl --no-hostname --boot --unit vyos-network-event-logger.service | grep "\b$4\b"</command>
fixed

2025-01-16 10:15 UTC, HollyGurza commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +      <command>journalctl --no-hostname --boot --unit vyos-network-event-logger.service | grep "$(echo "\[$6\]" | tr '[:lower:]' '[:upper:]')" | grep "\b$4\b"</command>
I think this is too simple a command to make a script, in the case of a script we will also duplicate the script call with approximately the same parameters

2025-01-16 10:15 UTC, HollyGurza commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +    <help>Show interface network event log</help>
fixed

2025-01-16 10:16 UTC, HollyGurza commented on src/services/vyos-network-event-logger
> +# https://github.com/torvalds/linux/blob/adc218676eef25575469234709c2d87185ca223a/include/uapi/linux/neighbour.h#L46
I moved a few constants to the vyos library, but it would probably be better to make a PR for the pyroute2 library in future

2025-01-16 10:16 UTC, HollyGurza commented on interface-definitions/service_monitoring_network_event.xml.in
> +                      <help>Log link status changes events</help>
fixed

2025-01-16 10:16 UTC, HollyGurza commented on interface-definitions/service_monitoring_network_event.xml.in
> +              <leafNode name="queue-size">
fixed

2025-01-16 10:16 UTC, HollyGurza commented on interface-definitions/service_monitoring_network_event.xml.in
> +                  <help>Set log-level. Log must be enable</help>
looks like a copy-past, fixed

2025-01-16 10:16 UTC, HollyGurza commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +        <help>Show log for link network events</help>
fixed

2025-01-16 10:16 UTC, HollyGurza commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +        <help>Show log for addr network events</help>
fixed

2025-01-16 10:16 UTC, HollyGurza commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +        <help>Show log for neigh network events</help>
fixed

2025-01-16 10:16 UTC, HollyGurza commented on op-mode-definitions/include/show-interface-type-event-log.xml.i
> +        <help>Show log for rule network events</help>
fixed

2025-01-16 10:16 UTC, HollyGurza commented on op-mode-definitions/show-log.xml.in
> +                  <help>Show log for route network events</help>
fixed

2025-01-16 10:16 UTC, HollyGurza commented on op-mode-definitions/show-log.xml.in
> +                  <help>Show log for link network events</help>
fixed

2025-01-16 10:16 UTC, HollyGurza commented on op-mode-definitions/show-log.xml.in
> +                  <help>Show log for neigh network events</help>
fixed

2025-01-17 14:42 UTC, sever-sever requested changes

2025-01-17 14:42 UTC, sever-sever commented on op-mode-definitions/include/log/network-event-type-interface.xml.i
> +<!-- included start from isis-common.xml.i -->
How does it relate to `isis-common`?

2025-01-17 14:42 UTC, sever-sever commented on src/services/vyos-network-event-logger
> +    # rtnl.RTM_DELADDRLABEL: {'parser': AddrlabelFormatter, 'event': 'addrlabel'},
Do we need this?

2025-01-17 14:42 UTC, sever-sever commented on src/services/vyos-network-event-logger
> +    # rtnl.RTM_DELNETCONF: {'parser': NetconfFormatter, 'event': 'netconf'},
Do we need this?

2025-01-21 04:16 UTC, HollyGurza commented on src/services/vyos-network-event-logger
> +    # rtnl.RTM_DELNETCONF: {'parser': NetconfFormatter, 'event': 'netconf'},
don't necessary, but it is convenient to see what event logs have not been implemented yet.  It does not affect app functionality.

2025-01-21 04:16 UTC, HollyGurza commented on src/services/vyos-network-event-logger
> +    # rtnl.RTM_DELADDRLABEL: {'parser': AddrlabelFormatter, 'event': 'addrlabel'},
don't necessary, but it is convenient to see what event logs have not been implemented yet.  It does not affect app functionality.

2025-01-21 04:16 UTC, HollyGurza commented on op-mode-definitions/include/log/network-event-type-interface.xml.i
> +<!-- included start from isis-common.xml.i -->
fixed

2025-01-21 07:32 UTC, sever-sever approved these changes

2025-01-24 17:58 UTC, dmbaturin approved these changes

2025-01-24 17:58 UTC, merged