nhrp: T2326: NHRP migration to FRR
vyos/vyos-1x pull request #4217
Opened 2024-12-03 10:29 UTC by aapostoliuk

NHRP migration to FRR

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): migration to another package

## Related Task(s)

https://vyos.dev/T2326

## Related PR(s)

## Component(s) name

nhrp

## Proposed changes

Replaced the old package opnnhrp with FRR nhrpd.
Advantages:
1. opennhrp project is not supported now.
2. It fixes compatibility between NHRP and IPSec. FRR manages an IPSec VPN connection.
3. It will allow the use of IPv6 over DMVPN in the future.

Restrictions:
1. The tunnel interface subnet mask must be /32

Changes:
Configuration mode:
All commands were remade according to FRR.
```
vyos@vyos# set protocols nhrp tunnel tun100
Possible completions:
   authentication       NHRP authentication
   holdtime             Holding time in seconds
 > map                  Map tunnel IP to NBMA
   mtu                  Maximum Transmission Unit (MTU)
+  multicast            Map multicast to NBMA
   network-id           NHRP network id
 > nhs                  Map tunnel IP to NBMA of Next Hop Server
   redirect             Enable sending of Cisco style NHRP Traffic Indication packets
   registration-no-unique
                        Zone to be local-zone
   shortcut             Enable creation of shortcut routes. A received NHRP Traffic
                        Indication will trigger the resolution and establishment of a
                        shortcut route
```
Operational mode:
All commands were remade according to FRR.
```
vyos@vyos:~$ show ip nhrp
Possible completions:
  cache                 Show NHRP interface connection information
  nhs                   Show NHRP tunnel connection information
  shortcut

```
```
vyos@vyos:~$ reset ip nhrp
Possible completions:
  cache                 Clear Dynamic cache entries
  shortcut              Clear Shortcut entries

```

## How to test

## Smoketest result

```
vyos@vyos:~$ /usr/libexec/vyos/tests/smoke/cli/test_protocols_nhrp.py
test_01_nhrp_config (__main__.TestProtocolsNHRP.test_01_nhrp_config) ... ok

----------------------------------------------------------------------
Ran 1 test in 9.307s

OK
vyos@vyos:~$ /usr/libexec/vyos/tests/smoke/cli/test_vpn_ipsec.py
test_dhcp_fail_handling (__main__.TestVPNIPsec.test_dhcp_fail_handling) ... ok
test_dmvpn (__main__.TestVPNIPsec.test_dmvpn) ... ok
test_flex_vpn_vips (__main__.TestVPNIPsec.test_flex_vpn_vips) ... ok
test_remote_access (__main__.TestVPNIPsec.test_remote_access) ... ok
test_remote_access_dhcp_fail_handling (__main__.TestVPNIPsec.test_remote_access_dhcp_fail_handling) ... ok
test_remote_access_eap_tls (__main__.TestVPNIPsec.test_remote_access_eap_tls) ... ok
test_remote_access_no_rekey (__main__.TestVPNIPsec.test_remote_access_no_rekey) ... ok
test_remote_access_pool_range (__main__.TestVPNIPsec.test_remote_access_pool_range) ... ok
test_remote_access_vti (__main__.TestVPNIPsec.test_remote_access_vti) ... ok
test_remote_access_x509 (__main__.TestVPNIPsec.test_remote_access_x509) ... ok
test_site_to_site (__main__.TestVPNIPsec.test_site_to_site) ... ok
test_site_to_site_vti (__main__.TestVPNIPsec.test_site_to_site_vti) ... ok
test_site_to_site_x509 (__main__.TestVPNIPsec.test_site_to_site_x509) ... ok

----------------------------------------------------------------------
Ran 13 tests in 88.830s

OK
vyos@vyos:~$ /usr/libexec/vyos/tests/smoke/cli/test_interfaces_tunnel.py
test_add_multiple_ip_addresses (__main__.TunnelInterfaceTest.test_add_multiple_ip_addresses) ... ok
test_add_single_ip_address (__main__.TunnelInterfaceTest.test_add_single_ip_address) ... ok
test_add_to_invalid_vrf (__main__.TunnelInterfaceTest.test_add_to_invalid_vrf) ... ok
test_dhcp_client_options (__main__.TunnelInterfaceTest.test_dhcp_client_options) ... skipped 'not supported'
test_dhcp_disable_interface (__main__.TunnelInterfaceTest.test_dhcp_disable_interface) ... skipped 'not supported'
test_dhcp_vrf (__main__.TunnelInterfaceTest.test_dhcp_vrf) ... skipped 'not supported'
test_dhcpv6_client_options (__main__.TunnelInterfaceTest.test_dhcpv6_client_options) ... skipped 'not supported'
test_dhcpv6_vrf (__main__.TunnelInterfaceTest.test_dhcpv6_vrf) ... skipped 'not supported'
test_dhcpv6pd_auto_sla_id (__main__.TunnelInterfaceTest.test_dhcpv6pd_auto_sla_id) ... skipped 'not supported'
test_dhcpv6pd_manual_sla_id (__main__.TunnelInterfaceTest.test_dhcpv6pd_manual_sla_id) ... skipped 'not supported'
test_eapol (__main__.TunnelInterfaceTest.test_eapol) ... skipped 'not supported'
test_erspan_v1 (__main__.TunnelInterfaceTest.test_erspan_v1) ... ok
test_gretap_parameters_change (__main__.TunnelInterfaceTest.test_gretap_parameters_change) ... ok
test_interface_description (__main__.TunnelInterfaceTest.test_interface_description) ... ok
test_interface_disable (__main__.TunnelInterfaceTest.test_interface_disable) ... ok
test_interface_ip_options (__main__.TunnelInterfaceTest.test_interface_ip_options) ... ok
test_interface_ipv6_options (__main__.TunnelInterfaceTest.test_interface_ipv6_options) ... ok
test_interface_mtu (__main__.TunnelInterfaceTest.test_interface_mtu) ... ok
test_ip6erspan_v2 (__main__.TunnelInterfaceTest.test_ip6erspan_v2) ... ok
test_ipv4_encapsulations (__main__.TunnelInterfaceTest.test_ipv4_encapsulations) ... ok
test_ipv6_encapsulations (__main__.TunnelInterfaceTest.test_ipv6_encapsulations) ... ok
test_ipv6_link_local_address (__main__.TunnelInterfaceTest.test_ipv6_link_local_address) ... ok
test_move_interface_between_vrf_instances (__main__.TunnelInterfaceTest.test_move_interface_between_vrf_instances) ... ok
test_mtu_1200_no_ipv6_interface (__main__.TunnelInterfaceTest.test_mtu_1200_no_ipv6_interface) ... ok
test_multiple_gre_tunnel_different_remote (__main__.TunnelInterfaceTest.test_multiple_gre_tunnel_different_remote) ... ok
test_multiple_gre_tunnel_same_remote (__main__.TunnelInterfaceTest.test_multiple_gre_tunnel_same_remote) ... ok
test_span_mirror (__main__.TunnelInterfaceTest.test_span_mirror) ... skipped 'not supported'
test_tunnel_invalid_source_interface (__main__.TunnelInterfaceTest.test_tunnel_invalid_source_interface) ... ok
test_tunnel_parameters_gre (__main__.TunnelInterfaceTest.test_tunnel_parameters_gre) ... ok
test_tunnel_src_any_gre_key (__main__.TunnelInterfaceTest.test_tunnel_src_any_gre_key) ... ok
test_vif_8021q_interfaces (__main__.TunnelInterfaceTest.test_vif_8021q_interfaces) ... skipped 'not supported'
test_vif_8021q_lower_up_down (__main__.TunnelInterfaceTest.test_vif_8021q_lower_up_down) ... skipped 'not supported'
test_vif_8021q_mtu_limits (__main__.TunnelInterfaceTest.test_vif_8021q_mtu_limits) ... skipped 'not supported'
test_vif_8021q_qos_change (__main__.TunnelInterfaceTest.test_vif_8021q_qos_change) ... skipped 'not supported'
test_vif_s_8021ad_vlan_interfaces (__main__.TunnelInterfaceTest.test_vif_s_8021ad_vlan_interfaces) ... skipped 'not supported'
test_vif_s_protocol_change (__main__.TunnelInterfaceTest.test_vif_s_protocol_change) ... skipped 'not supported'

----------------------------------------------------------------------
Ran 36 tests in 139.949s

OK (skipped=15)
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2025-01-09 15:42 UTC, sarthurdev approved these changes
LGTM

Should also have PR to remove the package build: https://github.com/vyos/vyos-build/tree/current/scripts/package-build/opennhrp

2025-01-09 15:57 UTC, c-po requested changes

2025-01-09 15:57 UTC, c-po commented on python/vyos/frrender.py
> +        nflog_redirect = 1
What are those magic numbers? Please add a proper comment.

2025-01-09 15:57 UTC, c-po commented on python/vyos/frrender.py
> +            if 'disable' not in profile_conf:
You can unindent one entire block by using

```suggestion
            if 'disable' in profile_conf:
                continue
```

2025-01-09 15:57 UTC, c-po commented on python/vyos/frrender.py
> +
Why are those whitespace lines needed?

2025-01-09 16:17 UTC, aapostoliuk commented on python/vyos/frrender.py
> +            if 'disable' not in profile_conf:
done

2025-01-09 16:17 UTC, aapostoliuk commented on python/vyos/frrender.py
> +
done

2025-01-09 16:20 UTC, aapostoliuk commented on python/vyos/frrender.py
> +        nflog_redirect = 1
I have added comments about these two numbers.
https://github.com/vyos/vyos-1x/pull/4217/files#diff-5fa707da9950d5de7cf947091ea150f12fd562a821f70857f1733ef1bcab9091R152-R155

More about NFLOG in FRR is described in FRR documentation

2025-01-13 14:03 UTC, aapostoliuk commented
Opennhrp is removed in 
https://github.com/vyos/vyos-build/pull/885

2025-01-13 18:51 UTC, c-po approved these changes

2025-01-13 18:52 UTC, merged