op_mode: T6767: Check latest image version in VRF context for "add system image latest vrf <name>"
vyos/vyos-1x pull request #4225
Opened 2024-12-06 13:22 UTC by natali-rs1985

## Change Summary

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): change lisence file

## Related Task(s)

* https://vyos.dev/T6767
## Related PR(s)

## Component(s) name

op mode
## Proposed changes

## How to test

```
set system update-check url https://raw.githubusercontent.com/vyos/vyos-rolling-nightly-builds/main/version.json
commit

vyos@vyos# run add system image  latest vrf TEST
Validating signature
Signature is valid
Validating image compatibility
Validating image checksums
What would you like to name this image? (Default: 1.5-rolling-202412060007) Would you like to set the new image as the default one for boot? [Y/n]
An active configuration was found. Would you like to copy it to the new image? [Y/n]
Copying configuration directory
Would you like to copy SSH host keys? [Y/n]
Copying SSH host keys
Copying system image files
Cleaning up
Unmounting target filesystems
Removing temporary files
...
```
## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-12-08 15:44 UTC, c-po requested changes

2024-12-08 15:44 UTC, c-po commented on src/op_mode/image_installer.py
> +            if config.exists('system update-check url'):
Why duplicate the content of `/usr/libexec/vyos/latest-image-url.py` here and not reference it, too?

2024-12-10 14:31 UTC, jestabro commented
As mentioned on Slack, this should be rebased over current and pushed to sync with the changes in
https://github.com/vyos/vyos-1x/pull/4226
https://github.com/vyos/vyos-build/pull/824

A local build of this PR confirms a successful build.

2024-12-10 19:06 UTC, c-po commented
@MergifyIo rebase

2024-12-10 19:21 UTC, jestabro commented
I have not found a 'mergifyio rebase' to suffice in the past; this will likely need an explicit rebase and force push to the branch.

2024-12-11 06:13 UTC, c-po approved these changes

2024-12-11 06:19 UTC, c-po commented
I wonder if it's a good idea to show REMOTE_USERNAME and REMOTE_PASSWORD on the CLI on error

```
The image cannot be fetched from: https://github.com/vyos/vyos-nightly-build/releases/download/1.5-rolling-202412100007/vyos-1.5-rolling-202412100007-generic-amd64.iso [Errno 1] failed to run command: REMOTE_USERNAME= REMOTE_PASSWORD=                 ip vrf exec red /usr/libexec/vyos/simple-download.py                 --local-file /tmp/vyos_installation.iso --remote-path https://github.com/vyos/vyos-nightly-build/releases/download/1.5-rolling-202412100007/vyos-1.5-rolling-202412100007-generic-amd64.iso
returned: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /vyos/vyos-nightly-build/releases/download/1.5-rolling-202412100007/vyos-1.5-rolling-202412100007-generic-amd64.iso (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe011080a90>: Failed to establish a new connection: [Errno 16] Device or resource busy'))
```

2024-12-11 06:20 UTC, c-po requested changes
I wonder if it's a good idea to show REMOTE_USERNAME and REMOTE_PASSWORD on the CLI on error

```
The image cannot be fetched from: https://github.com/vyos/vyos-nightly-build/releases/download/1.5-rolling-202412100007/vyos-1.5-rolling-202412100007-generic-amd64.iso [Errno 1] failed to run command: REMOTE_USERNAME= REMOTE_PASSWORD=                 ip vrf exec red /usr/libexec/vyos/simple-download.py                 --local-file /tmp/vyos_installation.iso --remote-path https://github.com/vyos/vyos-nightly-build/releases/download/1.5-rolling-202412100007/vyos-1.5-rolling-202412100007-generic-amd64.iso
returned: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /vyos/vyos-nightly-build/releases/download/1.5-rolling-202412100007/vyos-1.5-rolling-202412100007-generic-amd64.iso (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe011080a90>: Failed to establish a new connection: [Errno 16] Device or resource busy'))
```

2024-12-17 18:02 UTC, dmbaturin reviewed
I agree that this solution fixes the immediate problem. I still think we can do it better, though.

First, do we really need to execute the update check script as a subprocess? I think we could import it as a Python module and call a function from it instead.

Second, executing something in a VRF context is a need common enough that I believe we should add a named argument (`vrf`) to everything in `vyos.utils.subprocess`. That part should be a separate task, though.

2024-12-18 14:19 UTC, dmbaturin approved these changes
I don't mind merging it right now since it solves a problem but we need to address the deeper issue of VRF-awareness nonetheless.

2024-12-18 18:36 UTC, c-po approved these changes

2024-12-18 18:36 UTC, merged