T6927: adds option to set container name server
vyos/vyos-1x pull request #4232
Opened 2024-12-10 16:15 UTC by nvollmar

## Change Summary
Adds additional validation

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)
https://vyos.dev/T6927

## Related PR(s)
#4218

## Component(s) name
container

## Proposed changes
Warn that setting name-server on container has no effect if attached network has dns enabled.

## How to test
Configure container with name server and network with dns.

## Smoketest result
```
vyos@vyos:~$ /usr/libexec/vyos/tests/smoke/cli/test_container.py
test_api_socket (__main__.TestContainer.test_api_socket) ... ok
test_basic (__main__.TestContainer.test_basic) ... ok
test_cpu_limit (__main__.TestContainer.test_cpu_limit) ... ok
test_dual_stack_network (__main__.TestContainer.test_dual_stack_network) ... ok
test_ipv4_network (__main__.TestContainer.test_ipv4_network) ... ok
test_ipv6_network (__main__.TestContainer.test_ipv6_network) ... ok
test_name_server (__main__.TestContainer.test_name_server) ... ok
test_network_mtu (__main__.TestContainer.test_network_mtu) ... ok
test_no_name_server (__main__.TestContainer.test_no_name_server) ... ok
test_uid_gid (__main__.TestContainer.test_uid_gid) ... ok
```

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-12-10 19:03 UTC, c-po requested changes
It's a good idea to perform validation, but please extend the container name-server smoketests to also trigger this error.

Example: https://github.com/vyos/vyos-1x/blob/current/smoketest/scripts/cli/test_container.py#L142-L144

2024-12-10 19:03 UTC, c-po commented on src/conf_mode/container.py
> +                    raise ConfigError(f'Setting name server has no effect when container network with name server is used!')
This reads a bit bumpy - can you please rephrase?

2024-12-11 09:06 UTC, sever-sever approved these changes

2024-12-12 20:23 UTC, c-po approved these changes

2024-12-12 20:24 UTC, merged