T6918: firewall. Introduce patch for accepting invalid PPPoE Session
vyos/vyos-1x pull request #4236
Opened 2024-12-13 05:41 UTC by opswill

## Change Summary

This patch is related to T6647, PPPoE sessions (ether type 0x8864) are also marked as invalid connections, this patch will accept PPPoE session .

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T6918

## Related PR(s)

## Component(s) name

firewall

## Proposed changes

In https://vyos.dev/T6647, invalid connections are already accepted for DHCP and ARP; now we have also added PPPoE sessions.
## How to test

```
vyos@vyos# run show config comm | grep firewall
set firewall global-options apply-to-bridged-traffic invalid-connections
set firewall global-options state-policy established action 'accept'
set firewall global-options state-policy invalid action 'drop'
set firewall global-options state-policy invalid log
set firewall global-options state-policy invalid log-level 'debug'
set firewall global-options state-policy related action 'accept'

And nftables output:
vyos@vyos# sudo nft -s list table bridge vyos_filter
table bridge vyos_filter {
        chain VYOS_FORWARD_filter {
                type filter hook forward priority filter; policy accept;
                jump VYOS_STATE_POLICY
                counter accept comment "FWD-filter default-action accept"
        }

        chain VYOS_INPUT_filter {
                type filter hook input priority filter; policy accept;
                jump VYOS_STATE_POLICY
                counter accept comment "INP-filter default-action accept"
        }

        chain VYOS_OUTPUT_filter {
                type filter hook output priority filter; policy accept;
                ct state invalid ether type 0x8864 counter accept
                ct state invalid udp sport 67 udp dport 68 counter accept
                ct state invalid ether type arp counter accept
                jump VYOS_STATE_POLICY
                counter accept comment "OUT-filter default-action accept"
        }

        chain VYOS_PREROUTING_filter {
                type filter hook prerouting priority filter; policy accept;
                counter accept comment "PRE-filter default-action accept"
        }

        chain VYOS_STATE_POLICY {
                ct state established counter accept
                ct state invalid log prefix "[STATE-POLICY-INV-A]" level debug counter accept
                ct state related counter accept
                return
        }
}
[edit]
```
## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-12-13 06:46 UTC, sever-sever commented
Looks good, Only commit message format is wrong. It have to contain the task number.
Thanks

2024-12-13 07:57 UTC, opswill commented
I have corrected the commit message format to include the task number.

2024-12-13 09:04 UTC, sever-sever approved these changes

2024-12-16 11:06 UTC, nicolas-fort approved these changes

2024-12-16 11:19 UTC, dmbaturin requested changes
There should be a comma between protocols in a list of more than two items, at least. ;)

But there's a bigger question. I get that this PR patches the immediate problem. I'm not against merging it to address the problem of unintentionally mis-classified and dropped PPPoE connections.

My concern is that the list of special cases is growing and we have no guarantee that PPPoE is the last in the list. There's also a chance that people want, say, only DHCP, only ARP, or only PPPoE, depending on what they use.

I wonder if the command should be reworked into something like `accept-invalid-connections <ethertype>`. That will require a migration script. I made a  task about it: https://vyos.dev/T6951

If you don't think you'll have the time to work on it, I can approve the PR after the punctuation fix.

2024-12-16 11:19 UTC, dmbaturin commented on interface-definitions/include/firewall/global-options.xml.i
> +            <help>Accept ARP DHCP and PPPoE despite they are marked as invalid connection</help>
```suggestion
            <help>Accept ARP, DHCP and PPPoE despite they are marked as invalid connection</help>
```

2024-12-17 03:05 UTC, opswill commented
@dmbaturin Thank you for your insights. I suggest we go ahead and approve this PR for now since it solves the current problem. Since you've created a task for the rework, I can also take a look and see if I can help complete it.

2024-12-18 11:17 UTC, dmbaturin approved these changes

2024-12-18 11:17 UTC, merged