T6948: Keep DHCP server leases in sync with hostd records
vyos/vyos-1x pull request #4237
Opened 2024-12-13 11:28 UTC by indrajitr

## Change Summary

Keep DHCP server leases in sync with hostd records via `ExecStartPost` directive in `kea-dhcp{4,6}-server.service`.

This ensures that hostd records with the DHCP server leases are kept in sync with VyOS hostd records right after DHCP server is started.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6948

## Related PR(s)

## Component(s) name

dhcp{4,6} server

## Proposed changes

## How to test

1. Enable DHCP server and have active server leases
2. Ensure that relevant host entries exist in `/etc/hosts` and/or `/run/vyos-hostsd/vyos-hostsd.state`
4. Restart VyOS
5. Verify DHCP server leases are still active (`show dhcp server leases`)
6. Verify that the leases have NOT been applied to `/etc/hosts`
7. Restart dhcp server (`restart dhcp server`)
8. Verify that the leases have been applied to `/etc/hosts`

## Smoketest result

TBD

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-12-13 18:01 UTC, indrajitr commented
Keeping it as draft till I have a working test environment.

2024-12-26 18:17 UTC, indrajitr commented
Update: Ready for review.
This has been working fine for me in the local environment for the last few days.

2025-01-09 22:00 UTC, sarthurdev approved these changes
LGTM. Thanks for adding the smoketest.

2025-01-09 22:41 UTC, indrajitr commented on src/etc/systemd/system/kea-dhcp4-server.service.d/override.conf
> +ExecStartPost=!/usr/bin/python3 /usr/libexec/vyos/op_mode/dhcp.py update_dhcp_server_lease_to_hostd_state --family inet
Thanks for the review @sarthurdev! I need some feedback on the convention of invoking this one.
So far I haven't seen any precedence of invoking `op_mode/*.py` directly in the codebase. Is this okay, or do you want me to revisit this?

2025-01-10 00:12 UTC, sarthurdev commented on src/etc/systemd/system/kea-dhcp4-server.service.d/override.conf
> +ExecStartPost=!/usr/bin/python3 /usr/libexec/vyos/op_mode/dhcp.py update_dhcp_server_lease_to_hostd_state --family inet
it's not the ideal solution, as I don't see a use case where it'd be needed in op-mode, nor is it defined in XML.

Probably best done in a script in `src/system` like the Kea hook scripts.

2025-01-10 00:42 UTC, indrajitr commented on src/etc/systemd/system/kea-dhcp4-server.service.d/override.conf
> +ExecStartPost=!/usr/bin/python3 /usr/libexec/vyos/op_mode/dhcp.py update_dhcp_server_lease_to_hostd_state --family inet
Yes, that's why I asked :)

As you can see in the implementation of `update_dhcp_server_lease_to_hostd_state`, the method crucially depends on `_get_dhcp_pools` and `_get_raw_server_leases` which are implemented in `op_mode/dhcp.py` which is why I added the method in `update_dhcp_server_lease_to_hostd_state`. Could they be refactored to kea lib (`python/vyos/kea.py`) perhaps so that they can be reused?

Or what if we actually add an op-mode command - something like `update hostd state` and define it in XML as well?

NB: I realize that we are getting into design discussion here. We can discuss the options on Slack if necessary.

2025-01-12 19:01 UTC, sarthurdev commented on src/etc/systemd/system/kea-dhcp4-server.service.d/override.conf
> +ExecStartPost=!/usr/bin/python3 /usr/libexec/vyos/op_mode/dhcp.py update_dhcp_server_lease_to_hostd_state --family inet
Ideally there shouldn't be a scenario where the user needs to manually re-sync hostd state.

I agree that the utility functions could move to the `vyos.kea` module and be imported in op-mode and a new src/system script. Though for the module function, it should probably be just the logic that needs to be re-used (no sorting, filtering etc. Just returning the lease data as-is).

2025-01-16 06:37 UTC, indrajitr commented on src/etc/systemd/system/kea-dhcp4-server.service.d/override.conf
> +ExecStartPost=!/usr/bin/python3 /usr/libexec/vyos/op_mode/dhcp.py update_dhcp_server_lease_to_hostd_state --family inet
@sarthurdev, raised #4307 to refactor utility functions to `vyos.kea`. Would appreciate feedback on that.

2025-01-21 04:43 UTC, indrajitr commented on src/etc/systemd/system/kea-dhcp4-server.service.d/override.conf
> +ExecStartPost=!/usr/bin/python3 /usr/libexec/vyos/op_mode/dhcp.py update_dhcp_server_lease_to_hostd_state --family inet
Now that #4307 has been applied, I have made the necessary changes to better comply with the recommended convention.

2025-01-21 09:18 UTC, sever-sever approved these changes

2025-02-17 07:05 UTC, c-po approved these changes
This looks good to me. I asked @sarthurdev as our VyOS most experienced KEA user for his opinion, too.

2025-02-17 18:37 UTC, sarthurdev requested changes
LGTM, just this last issue

2025-02-17 18:37 UTC, sarthurdev commented on src/system/sync-dhcp-lease-to-hosts.py
> +    if not config.exists('service dhcp-server'):
This should check v4/v6 node depending on the argument

2025-02-17 18:37 UTC, sarthurdev commented on src/system/sync-dhcp-lease-to-hosts.py
> +    if not config.exists('service dhcp-server hostfile-update'):
This should check v4/v6 node depending on the argument

2025-02-17 19:47 UTC, indrajitr commented on src/system/sync-dhcp-lease-to-hosts.py
> +    if not config.exists('service dhcp-server'):
DHCPv6 doesn't support hostfile update and the script will hard fail before reaching here. But you are right, since there is a cli arg for v4/v6, we might as well have this in place.

2025-02-17 19:47 UTC, indrajitr commented on src/system/sync-dhcp-lease-to-hosts.py
> +    if not config.exists('service dhcp-server hostfile-update'):
This config path doesn't exist anyway since DHCPv6 doesn't support hostfile update. But you are right, since there is a cli arg for v4/v6, we might as well have this in place.

2025-02-19 12:08 UTC, sarthurdev approved these changes

2025-02-27 20:05 UTC, merged

2025-04-02 12:44 UTC, sarthurdev commented on smoketest/scripts/cli/test_service_dhcp-server.py
> +        self.assertTrue(process_named_running(PROCESS_NAME, timeout=30))
Noticed this while working on something else, Is there meant to be a service restart here?