T6953: merges node and frr exporter under prometheus section
vyos/vyos-1x pull request #4242
Opened 2024-12-18 14:15 UTC by nvollmar

## Change Summary
Gather all prometheus exporters under the config section prometheus similar to telegraph

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [X] Other (please describe): config/code consolidation (requires config migration)

## Related Task(s)
https://vyos.dev/T6953

## Related PR(s)
* https://github.com/vyos/vyos-documentation/pull/1580

## Component(s) name
monitoring

## Proposed changes
Moving currently separate node-exporter and frr-exporter under prometheus umbrella.

## How to test
```
set service monitoring prometheus node-exporter listen-address 192.0.2.1
set service monitoring prometheus frr-exporter listen-address 192.0.2.1
```

## Smoketest result
```
DEBUG - Running Testcase: /usr/libexec/vyos/tests/smoke/cli/test_service_monitoring_prometheus.py
DEBUG - test_01_node_exporter (__main__.TestMonitoringPrometheus.test_01_node_exporter) ... ok
DEBUG - test_02_frr_exporter (__main__.TestMonitoringPrometheus.test_02_frr_exporter) ... ok
```

## Checklist:
- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [X] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

2024-12-19 13:53 UTC, nvollmar commented
failing tests don't seem to be related to this changes

2024-12-19 16:11 UTC, c-po requested changes

2024-12-19 16:11 UTC, c-po commented on src/conf_mode/service_monitoring_prometheus.py
> +    monitoring = conf.get_config_dict(base, key_mangling=('-', '_'), get_first_key=True)
```suggestion
    monitoring = conf.get_config_dict(base, key_mangling=('-', '_'), get_first_key=True, with_recursive_defaults=True)
```

2024-12-19 16:11 UTC, c-po commented on src/conf_mode/service_monitoring_prometheus.py
> +    monitoring = conf.merge_defaults(monitoring, recursive=True)
```suggestion
```

2024-12-20 17:19 UTC, sever-sever approved these changes

2024-12-20 22:02 UTC, c-po approved these changes

2024-12-20 22:02 UTC, merged