Adds support for configuring a lua script in PowerDNS
vyos/vyos-1x pull request #425
Opened 2020-05-24 03:05 UTC by shafer

This is something I currently use on my VyOS install so I can take advantage of LUA scripts that alter the behaviour of the server.

You can find a few examples here: https://github.com/PowerDNS/pdns/tree/master/pdns/recursordist/examples

There isn't a phabricator for this work. If required to get this accepted I could setup an account and link this PR to a feature request.

2020-05-24 04:08 UTC, jjakob commented
I'm working on T2486 right now which will add a lua file, but not via config. This would then need to be joined with the config-set lua. I can add your changes to my patch set, I'd need to rebase on your work anyway if this PR were merged as there are significant changes needed on my end.
You should always create a phabricator task to avoid duplication of work with other people, so they know what they're working on in cases like this, and it's mandatory to have the task ID in the commit messages and PR name to get the patch accepted.

2020-05-24 04:22 UTC, shafer commented
Ok. I can add a task next time. I'm an infrequent contributor and haven't been able to stay caught up with the new processes.

Would you suggest I close this PR? I'm just happy for the feature to wind up in rolling. I don't care how. :)

2020-05-24 05:26 UTC, dmbaturin commented
There's no need to close it. You can force push to the same branch, with correct commit descriptions.

2020-05-24 07:11 UTC, jjakob commented
I see no need to either as I'll incorporate the changes into my current work.

On May 24, 2020 7:27:00 AM GMT+02:00, Daniil Baturin <notifications@github.com> wrote:
>There's no need to close it. You can force push to the same branch, with correct commit descriptions.
>

2020-05-25 13:01 UTC, jjakob commented
- I'd name the node 'lua-dns-script' to avoid confusion with 'lua-config-file' (TIL pdns-recursor has 2 different lua config files)
- add the empty variable `"lua_script": "",` to default_config data
- put a warning in the new node <help> field like there is in dhcp-server *-parameters (e.g. "You must use a file suitable for use with pdns-recursor's lua-dns-script, any errors in the file will result in a service failure. Check the system log for errors after modifying.")

2020-05-28 02:48 UTC, shafer commented
I made a comment in Phabricator already, but I'll make one here as well. I added the suggestions and pushed a new branch.

2020-06-10 19:05 UTC, jjakob commented
You haven't actually pushed any changes?

2020-06-11 00:33 UTC, shafer commented
I shouldn't have said pushed a new branch. I pushed an updated branch. In the "Files changed" section of this PR I'm seeing the empty default, the warning language, and the node name change.

2020-06-11 01:08 UTC, jjakob commented
Well none of the issues I raised in the review are fixed, so the current code won't even work, that's why I suspect it's still waiting to be merged. Double check the comments in my review.

2020-06-11 02:09 UTC, shafer commented
Based on the feedback in this [comment](https://github.com/vyos/vyos-1x/pull/425#issuecomment-633561147) I made changes. I don't see feedback other than that.

Here is a screenshot showing what I see. Which includes a new node name of lua-dns-script, a warning similar to making custom dhcpd changes, and the empty default.

![Screenshot_2020-06-10_19-06-58](https://user-images.githubusercontent.com/2249341/84337128-a78ba600-ab4d-11ea-92aa-f6596d352171.png)

I'm at a loss to find other comments in this PR or in Phabricator that suggest code changes.

2020-06-11 02:43 UTC, jjakob commented
That's odd, the code comments are definitely showing here... I'm closing the current review and reopening it in case Github messed up somehow

2020-06-11 03:23 UTC, shafer commented
Please let me know in a comment when you do. As of this comment I'm not seeing anything new yet.

2020-06-11 04:41 UTC, jjakob commented
![Screenshot from 2020-06-11 06-39-43](https://user-images.githubusercontent.com/5466039/84345730-a7b39200-ab9d-11ea-88fb-7e9c1541d135.png)
 
I have no idea why you're not seeing it (it shows "jjakob started a review" 2 hours ago on this very page)...

2020-06-11 04:41 UTC, jjakob requested changes

2020-06-11 04:41 UTC, jjakob commented on data/templates/dns-forwarding/recursor.conf.tmpl
> +{% if lua_script -%}
This variable doesn't exist, it's named lua_dns_script in the main script (the 'dns' dict variable keys are the variables in the jinja2 template)

2020-06-11 04:41 UTC, jjakob commented on src/conf_mode/dns_forwarding.py
> +        lua_dns_script = conf.return_value('lua-dns-script')
Still an unneeded variable assignment, you can assign it directly to the end variable like this:
```dns['lua_dns_script'] = conf.return_value('lua-dns-script')```

2020-06-11 04:42 UTC, jjakob commented
Figured it out, it was a PEBKAC on my part, the comments were "pending" until I actually clicked "start review"...

2020-06-12 10:46 UTC, jjakob commented
@shafer one issue was fixed, the other comment wasn't - it'll still work that way, but I don't see the reason for the unnecessary intermediate local scope variable. Assign the result of conf.return_value to the dns dict key directly in one line.

2020-06-15 03:31 UTC, shafer commented
Maybe I didn't do something with the review I was supposed to. I commented that I did it that way because it matched the pattern. I've updated again to use the code that takes fewer lines, but doesn't match the pattern for cache_size or negative_ttl as examples.

2020-06-15 03:31 UTC, shafer commented on data/templates/dns-forwarding/recursor.conf.tmpl
> +{% if lua_script -%}
Fixed this in latest push. I forgot to rename if in template after renaming it other places.

2020-06-15 03:31 UTC, shafer commented on src/conf_mode/dns_forwarding.py
> +        lua_dns_script = conf.return_value('lua-dns-script')
I'm aware you can do this, but I was following the pattern already present in the code. My pref would be to leave it as-is and let a different phabricator efffort to clean/optimize handle it.

2020-06-27 03:36 UTC, closed without merging