T6013: Add support for AuthorizedPrincipalsFile to trusted_user_ca_key
vyos/vyos-1x pull request #4266
Opened 2024-12-28 20:02 UTC by takehaya

This commit introduces the bind-user subcommand to support AuthorizedPrincipalsFile. With this addition, it is now possible to associate SSH login users with their respective principals.

## Change Summary

This PR complements [[vyos/vyos-1x#4234](https://github.com/vyos/vyos-1x/pull/4234)](https://github.com/vyos/vyos-1x/pull/4234) by adding support for `AuthorizedPrincipalsFile`. With this enhancement, SSH login using CA certificates and arbitrary user principals is now fully supported.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

## Related PR(s)

https://github.com/vyos/vyos-1x/pull/4234

## Component(s) name

## Proposed changes

## How to test

## Smoketest result

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2025-04-14 16:01 UTC, dmbaturin approved these changes
I do not have any objections against this feature, and I cannot see any logic issues, either. It's a straightforward and useful extension of https://github.com/vyos/vyos-1x/pull/4234

2025-04-20 19:21 UTC, c-po requested changes
Thank you for the PR and sorry for the late feedback.

This is a good addition to the TrustedUserCAKeys feature. But I do not like the CLI design of this. As this implementation mainly focuses on the fact to allow a principal for a given user - and that file is rendered to the users home directory - this is no more different then how we manage SSH keys - except the file path is different.

I would request a change in CLI from:
`vyos@vyos# set system login user bind-user vyos principal AwesomeCertFooBar`
to
`vyos@vyos# set system login user cpo authentication principal AwesomeCertFooBar`

Thus we have everything under the same place in our configuration and make the users life a little less miserable.

2025-04-20 19:21 UTC, c-po commented on interface-definitions/service_ssh.xml.in
> +                  <help>user-name</help>
In order to make this feature properly work this most likely corresponds to a username defined already under: `set system login user` - so this node misses a completionHelper for lazy people like me:

```suggestion
                  <help>Username for principal list</help>
                  <completionHelp>
                    <path>system login user</path>
                  </completionHelp>                  
```

2025-04-20 19:21 UTC, c-po commented on interface-definitions/service_ssh.xml.in
> +                      <help>principal-name</help>
```suggestion
                      <help>Principal listed in user certificate</help>
```

2025-04-22 14:43 UTC, dmbaturin commented on interface-definitions/service_ssh.xml.in
> +                  <help>user-name</help>
I agree, @c-po's idea is better than adding it to `service ssh`.

2025-05-29 12:02 UTC, c-po approved these changes
```
cpo@LR1.wue3:~$ /usr/libexec/vyos/tests/smoke/cli/test_service_ssh.py 
test_ssh_default (__main__.TestServiceSSH.test_ssh_default) ... ok
test_ssh_dynamic_protection (__main__.TestServiceSSH.test_ssh_dynamic_protection) ... ok
test_ssh_login (__main__.TestServiceSSH.test_ssh_login) ... ok
test_ssh_multiple_listen_addresses (__main__.TestServiceSSH.test_ssh_multiple_listen_addresses) ... ok
test_ssh_ndcpp (__main__.TestServiceSSH.test_ssh_ndcpp) ... ok
test_ssh_pubkey_accepted_algorithm (__main__.TestServiceSSH.test_ssh_pubkey_accepted_algorithm) ... ok
test_ssh_single_listen_address (__main__.TestServiceSSH.test_ssh_single_listen_address) ... ok
test_ssh_trusted_user_ca (__main__.TestServiceSSH.test_ssh_trusted_user_ca) ... ok
test_ssh_vrf_multi (__main__.TestServiceSSH.test_ssh_vrf_multi) ... ok
test_ssh_vrf_single (__main__.TestServiceSSH.test_ssh_vrf_single) ... ok

----------------------------------------------------------------------
Ran 10 tests in 47.562s

OK
```

2025-05-29 18:16 UTC, merged