T978: Support PowerDNS Recursor outbound queries over IPv6.
vyos/vyos-1x pull request #58
Opened 2018-11-08 19:39 UTC by gsadams

This requires adding a query-local-address6 setting to enable outbound
IPv6 queries in general, and also formatting upstream nameserver IPv6
addresses in such a way that Recursor can parse them.

2018-11-08 20:14 UTC, c-po commented
Thx for the contribution. Usually we prefix our commit headline with the phabricator task id, thus commits can be automassigned to tasks. Can you please reword your commit?

2018-11-08 21:20 UTC, gsadams commented
Done.

2018-11-08 21:31 UTC, c-po requested changes
Could you please add query-local-address=0.0.0.0/0 for completion, too?
Then we have both IPv4 and IPv6 statements.

2018-11-08 21:31 UTC, c-po commented on src/conf_mode/dns_forwarding.py
> +query-local-address6=::
Could you please add `query-local-address=0.0.0.0/0` for completion, too? 
Then we have both IPv4 and IPv6 statements.

2018-11-08 22:40 UTC, gsadams commented on src/conf_mode/dns_forwarding.py
> +query-local-address6=::
Done (but without the /0; it doesn't like that). This is the default value, so I didn't include it, but it does seem valuable to be explicit.

2018-11-09 06:41 UTC, c-po approved these changes

2018-11-09 06:41 UTC, merged