bridge:T3067: You should not modify the vlan filter settings without setting VLAN awareness
vyos/vyos-1x pull request #613
Opened 2020-11-17 08:56 UTC by jack9603301

You should not modify the vlan filter settings without setting VLAN awareness

2020-11-17 08:57 UTC, dmbaturin approved these changes

2020-11-17 19:11 UTC, c-po commented
Hi @jack9603301 you have two commits here both with the same headline and different changes.

Please be more precise when descibing your change in the individual commit messages. Proper commit messages help us in the future identifying the reason why code was added/removed.

2020-11-17 19:17 UTC, c-po commented
Good to go once the commit messages are properly rephrased.

```
cpo@LR4.wue3# brctl show
bridge name     bridge id               STP enabled     interfaces
br0             8000.000db95307ee       no              eth2
                                                        eth3
                                                        wlan0
```

2020-11-17 19:35 UTC, c-po commented
Okay, this was to fast unfortunately. As you have removed my code to not add wlan interfaces in `bridge.py` this will now trigger an exception on system bootup - looks like this was not tested.

```
Traceback (most recent call last):
  File "/usr/libexec/vyos/conf_mode/interfaces-wireless.py", line 288, in <module>
    apply(c)
  File "/usr/libexec/vyos/conf_mode/interfaces-wireless.py", line 268, in apply
    w.update(wifi)
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/wireless.py", line 74, in update
    super().update(config)
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/interface.py", line 1088, in update
    self.add_to_bridge(bridge_dict)
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/interface.py", line 858, in add_to_bridge
    Section.klass(bridge)(bridge, create=True).add_port(self.ifname)
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/bridge.py", line 196, in add_port
    return self.set_interface('add_port', interface)
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/control.py", line 184, in set_interface
    return self._set_command(self.config, name, value)
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/control.py", line 109, in _set_command
    return self._command_set[name].get('format', lambda _: _)(self._cmd(cmd))
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/control.py", line 51, in _cmd
    return cmd(command, self.debug)
  File "/usr/lib/python3/dist-packages/vyos/util.py", line 179, in cmd
    raise OSError(code, feedback)
FileNotFoundError: [Errno 2] failed to run command: ip link set dev wlan0 master br0
returned:
exit code: 2
```

2020-11-17 19:50 UTC, jack9603301 commented
I will deal with your message in a few hours `bridge.py` Adding a wireless port is bound to be a bit troublesome, which means that VLAN filter cannot be set, and VLAN sensing cannot be set directly when there are WLAN ports

2020-11-17 19:57 UTC, c-po commented
Easiest thing would be to not allow wlan member interfaces in vlan mode, check this in verify()

2020-11-17 20:03 UTC, jack9603301 commented
I will try to modify PR in a few hours. If VLAN aware is not supported, I will take your advice (VLAN aware is not supported for WLAN interface). I seem to have got some clues in your error information. I'll take a test first.

Thanks

2020-11-18 01:18 UTC, jack9603301 commented
@c-po I banned the WLAN port bridge from entering the sensing bridge mode

2020-11-18 20:40 UTC, c-po requested changes

2020-11-18 20:40 UTC, c-po commented on python/vyos/ifconfig/bridge.py
> +                if 'wlan' in interface:
Why not leave the code as it was before? This feels like an unnecessary change which probably does more harm then good.

2020-11-19 19:54 UTC, merged