upnpd: T3420: Support UPNP protocol
vyos/vyos-1x pull request #789
Opened 2021-03-25 11:14 UTC by jack9603301

## Change Summary

Support UPNP protocol

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3420

## Component(s) name

upnpd

## Proposed changes

## How to test

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2021-03-25 16:19 UTC, jack9603301 commented
associated: https://github.com/vyos/vyos-build/pull/153

2021-03-25 18:24 UTC, jack9603301 commented
associated: https://github.com/vyos/vyatta-cfg-system/pull/142

2021-04-18 09:11 UTC, c-po commented
Hi @jack9603301,

thanks for this contribution. Unfortunately I have had yet no time to dig myself through UPnP and your commit. Will do in the next couple of days.

2021-07-10 09:08 UTC, c-po commented
Given the recent flaws and "problems" once more uncovered by UPNP, I am sorry but I must say: -1

2021-07-10 12:30 UTC, KittyFort commented
Realistically, uPnP - like any other tool - still has value despite being a potential attack vector. _Especially_ if it's not enabled by default. Let's talk about ways to get the most out of uPnP:

1. Being able to lock uPnP support to specific interfaces, IP ranges or zones will prevent concerns with untrusted devices being able to punch holes in the NAT. We're all aware uPnP isn't the _only_ way to allow incoming traffic, but its simplicity makes targeting it substantially easier.
2. Only allowing devices to do uPnP configuration for their own IPs prevents some of the worst vulnerabilities around uPnP. This is one of the worst of the uPnP implementation issues seen.
3. Limiting the number of ports that a device can open is another simple, sane restriction. Similarly, a range of ports could be reserved up front for uPnP applications.
4. Malware attempting to utilize uPnP doesn't go away just because uPnP is disabled. Compromised systems will still be compromised.
5. uPnP doesn't have to actually _open the port_ or _save the configuration_. I think it's greatest potential is as a draft port mapping tool. A uPnP service could actually be used to auto-discover ports used by applications. Some of this can be done with firewall rules, and service implementations aren't there yet. But potential should be a good reason to not unilaterally block an optional service.
6. uPnP is a consumer technology used on consumer routers. Which, in the end, are a massive security risk. An optional and _limited_ implementation of uPnP could be a means to push consumers away from terrible turnkey router e-waste that, despite being insecure, actually lets them play Xbox or whatever without much hassle. If we won't support anything that isn't perfect, we miss the opportunity to improve the already terrible market.
7. uPnP actually has some potential use in DMZ zones as well, as long as traffic between zones is properly firewalled.
8. When we actually get a GUI in place, uPnP could integrate with the UI and with admin notification systems to deal with the security issues of eternal access to immediate port mapping. Temporary uPnP enablement windows, mapping approval procedures, etc.
9. No one's going to work on betting uPnP (or any other technology, for that matter) if we refuse to even allow it to be optionally enabled until it's perfect. Especially when _existing_ services and kernel interfaces don't have all their options available through the config interface.

I would strongly dissent to making uPnP a default service. But, then again, Vyos doesn't really have default services. I'd rather have the option there and _documented_ for its potential security risks than just take a purist approach that ignores existing standards that can be misused.

uPnP is hardly the only thing a sloppy IT admin could do to put the network at risk. And having the ability to configure it but leave it disabled until someone needs to start up some random P2P application service would make it significantly easier to deploy and manage among less tech-savvy locations. That could change a port-mapping chore from an hour-long fiasco of googling for documentation to a five-minute affair.

2021-08-29 05:41 UTC, lucasec commented
@jack9603301 Thanks for working on this, UPnP was also on my plate to look into contributing. This looks pretty similar to what I was planning to implement, will try it out tomorrow and see if I have any feedback on how it was implemented.

I think this could still be enhanced by adding a run mode command to show active UPnP leases. I also planned to do some testing on whether upnp could stomp on existing DNAT/firewall rules and if so whether we could autogenerate "exclude" rules in the daemon config to prevent that.

As to arguments against merging UPnP, I think @KittyFort did a good job rebutting most. `miniupnpd` is pretty mature at this point, and by nature of being widely used, bugs get found and patched pretty quickly. It also has a good variety of hardening options, such as `secure_mode` (can we default this to `yes` and require an opt-out `insecure-mode` instead?) and the ACL-style "rules" list that lets you prohibit clients mapping certain ports.

I suppose the real question is whether we want to exclude some use cases from VyOS. To me there is real value to having one platform that can serve many uses. For example, I run VyOS as a VPN gateway in the cloud but I also use VyOS as a CPE in high end residential and certain small business usecases. UPnP is sort of a necessary evil as unfortunately some devices targeted at those segments simply don't function fully without it. Game consoles get mentioned frequently, but also some VoIP devices, camera systems, and random IoT devices (yes, I know, but I can't stop clients from installing these and I get the call when they don't work).

VyOS supports dynamic dns, which certainly has its share of insecure implementations and arguably is not needed in a tightly-managed IT environment. I would argue UPnP falls in the same camp. I'd rather put effort towards an in-tree solution (where we can ensure `miniupnpd` gets updated regularly) than maintaining a fork or patch.

2021-09-05 12:02 UTC, jack9603301 commented
> As to arguments against merging UPnP, I think @KittyFort did a good job rebutting most. miniupnpd is pretty mature at this point, and by nature of being widely used, bugs get found and patched pretty quickly. It also has a good variety of hardening options, such as secure_mode (can we default this to yes and require an opt-out insecure-mode instead?) and the ACL-style "rules" list that lets you prohibit clients mapping certain ports.

Perhaps, it’s a good idea to require upnp to enter secure mode by default.

2021-11-12 18:44 UTC, fegauthier commented
Hi @jack9603301,

I just tried your PR with the latest current build. I got an error when I commit. I think it's about IPV6 interfaces. The only IPV6 address that I have is on the loopback interface.

`vyos@vyos:~$ show interfaces
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface        IP Address                        S/L  Description
---------        ----------                        ---  -----------
br0              192.168.1.1/24                    u/u  LAN
br0.10           192.168.10.1/24                   u/u  VLAN10
br0.11           192.168.11.1/24                   u/u  VLAN11
br0.12           192.168.12.1/24                   u/u  VLAN12
br0.13           192.168.13.1/24                   u/u  VLAN13
br0.14           192.168.14.1/24                   u/u  VLAN14
br0.15           192.168.15.1/24                   u/u  VLAN15
br0.16           192.168.16.1/24                   u/u  VLAN16
br0.17           192.168.17.1/24                   u/u  VLAN17
br0.18           192.168.18.1/24                   u/u  VLAN18
br0.19           192.168.19.1/24                   u/u  VLAN19
br0.20           192.168.20.1/24                   u/u  VLAN20
br0.21           192.168.21.1/24                   u/u  VLAN21
br0.22           192.168.22.1/24                   u/u  VLAN22
br0.23           192.168.23.1/24                   u/u  VLAN23
br0.24           192.168.24.1/24                   u/u  VLAN24
br0.25           192.168.25.1/24                   u/u  VLAN25
br0.26           192.168.26.1/24                   u/u  VLAN26
br0.27           192.168.27.1/24                   u/u  VLAN27
br0.28           192.168.28.1/24                   u/u  VLAN28
br0.29           192.168.29.1/24                   u/u  VLAN29
br0.30           192.168.30.1/24                   u/u  VLAN30
br0.31           192.168.31.1/24                   u/u  VLAN31
br0.32           192.168.32.1/24                   u/u  VLAN32
br0.33           192.168.33.1/24                   u/u  VLAN33
br0.34           192.168.34.1/24                   u/u  VLAN34
br0.35           192.168.35.1/24                   u/u  VLAN35
eth0             -                                 u/u  BELL_FIBER
eth0.35          -                                 u/u  BELL_VLAN
eth1             -                                 u/u
eth2             -                                 u/u
eth3             -                                 u/D
lo               127.0.0.1/8                       u/u
                 ::1/128
pppoe0           **.**.**.102/32                   u/u
`

There is the error I got

`[ service upnp ]
VyOS had an issue completing a command.

We are sorry that you encountered a problem while using VyOS.
There are a few things you can do to help us (and yourself):
- Contact us using the online help desk if you have a subscription:
  https://support.vyos.io/
- Make sure you are running the latest version of VyOS available at:
  https://vyos.net/get/
- Consult the community forum to see how to handle this issue:
  https://forum.vyos.io
- Join us on Slack where our users exchange help and advice:
  https://vyos.slack.com

When reporting problems, please include as much information as possible:
- do not obfuscate any data (feel free to contact us privately if your
  business policy requires it)
- and include all the information presented below

Report time:      2021-11-12 13:38:21
Image version:    VyOS 1.4-rolling-202111121453
Release train:    sagitta

Built by:         felixetienne.gauthier@gmail.com
Built on:         Fri 12 Nov 2021 14:53 UTC
Build UUID:       0a351274-8975-443e-970c-0ffa64be61d3
Build commit ID:  e05bc2941a4164

Architecture:     x86_64
Boot via:         installed image
System type:      bare metal

Hardware vendor:  INTEL
Hardware model:   J1900
Hardware S/N:     To be filled by O.E.M.
Hardware UUID:    03000200-0400-0500-0006-000700080009

Traceback (most recent call last):
  File "/usr/libexec/vyos/conf_mode/service_upnp.py", line 150, in <module>
    verify(c)
  File "/usr/libexec/vyos/conf_mode/service_upnp.py", line 113, in verify
    system_addrs_cidr = get_all_interface_addr(True, [], [netifaces.AF_INET, netifaces.AF_INET6])
  File "/usr/libexec/vyos/conf_mode/service_upnp.py", line 85, in get_all_interface_addr
    bits = bin(int(addr['netmask'].replace(':', ''), 16)).count('1')
ValueError: invalid literal for int() with base 16: 'ffffffffffffffff/64'



[[service upnp]] failed
Commit failed
`

Do you know what is the problem?

2021-11-12 19:11 UTC, fegauthier commented
I fixed it! 

Changing the line 85 in the service_upnp.py

`bits = bin(int(addr['netmask'].replace(':', ''), 16)).count('1')`

by

`bits = bin(int(addr['netmask'].replace(':', '').split('/')[0], 16)).count('1')`

Fixed the issue

2021-11-13 10:40 UTC, jack9603301 commented
> bits = bin(int(addr['netmask'].replace(':', '').split('/')[0], 16)).count('1')

thanks

2021-11-15 00:19 UTC, fegauthier commented
Hi @jack9603301 

It doesn't seems to work. Do you how can I get miniupnpd logs? If I run miniupnpd standalone, I got these errors

```
invalid option in file /run/upnp/miniupnp.conf line 74 : anchor=VyOS
invalid option in file /run/upnp/miniupnp.conf line 79 : lease_file=/config/upnp.leases
miniupnpd[49644]: system uptime is 112133 seconds
miniupnpd[49644]: mnl_socket bound, port_id=49644
miniupnpd[49644]: send_batch: mnl_cb_run returned -1
miniupnpd[49644]: table_op(0, 1, miniupnpd) send_batch failed -4
miniupnpd[49644]: Failed to init redirection engine. EXITING

```

Do you know what could be wrong?

2021-11-15 13:48 UTC, fegauthier commented
@jack9603301 

The actual version of miniupnpd is 2.2.1. I compiled the new version which is 2.2.3 and the problem is the same.

2021-11-22 03:25 UTC, jack9603301 commented
You can freely consult the configuration file of UPnP and compare it. If necessary, you can modify it and run upnpd manually or automatically. If you have any new harvest, please let me know.

2021-11-22 03:31 UTC, jack9603301 commented
> @jack9603301
> 
> The actual version of miniupnpd is 2.2.1. I compiled the new version which is 2.2.3 and the problem is the same.

If you run it in the same way as the implementation, it should get the correct results. For details, see:

https://www.freebsd.org/cgi/man.cgi?query=miniupnpd&sektion=8

2021-11-22 13:27 UTC, fegauthier commented
I finally get it worked, but there is some changes that we need to do.

1. Validator port-range doesn't exist. I got this error

```
vyos@vyos# set service upnp rules 1 external-port-range 1024-65535

  Could not execute validator /usr/libexec/vyos/validators/port-range

  Invalid value
  Value validation failed
  Set failed
```

2. We have to remove anchor option in the config file because it's useless in our case because we use nftables.

2022-01-05 19:31 UTC, dmbaturin approved these changes
I'm inclined to merge this, now that 1.3 is out and 1.4 is entering active development. There will be time to refine the implementation.

2022-01-13 01:27 UTC, sever-sever requested changes

2022-01-13 01:27 UTC, sever-sever commented on src/conf_mode/service_upnp.py
> +        for rule,rule_config in upnpd['rule'].items():
Add whitespace after the comma.

2022-01-13 01:27 UTC, sever-sever commented on src/conf_mode/service_upnp.py
> +        for rule,rule_config in upnpd['rule'].items():
Add whitespace after the comma.

2022-01-13 01:27 UTC, sever-sever commented on data/templates/firewall/upnpd.conf.tmpl
> +#presentation_url= {{ presentation_url }}
Should it be uncommented?

2022-01-29 17:08 UTC, merged

2022-06-03 13:04 UTC, jack9603301 commented on data/templates/firewall/upnpd.conf.tmpl
> +#presentation_url= {{ presentation_url }}
Do you think I should uncomment it?