T3561: router-advert: add support for specific routes
vyos/vyos-1x pull request #851
Opened 2021-05-21 10:00 UTC by mark-royds

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3561

## Component(s) name

service router-advert

## Proposed changes

add support for the `route` directive 
## How to test

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2021-05-21 16:12 UTC, c-po requested changes

2021-05-21 16:12 UTC, c-po commented on data/templates/router-advert/radvd.conf.tmpl
> +{%     for route in interface[iface].route %}
Please add an `if` condition to check if the `route` key is set.

2021-05-21 16:12 UTC, c-po commented on data/templates/router-advert/radvd.conf.tmpl
> +{%     if interface[iface].route[route].valid_lifetime is defined %}
Please indent this by two more whitespaces as this is nested inside the `for` loop.

2021-05-21 16:12 UTC, c-po commented on src/conf_mode/service_router-advert.py
> +
Please drop this whitespace line.

2021-05-21 20:50 UTC, c-po commented
LGTM

2021-05-21 20:50 UTC, c-po approved these changes

2021-05-23 10:14 UTC, dmbaturin approved these changes

2021-05-23 10:20 UTC, merged