T3275: conntrack: Migrate 'disable' syntax to 'enable' syntax for the new default behavior
vyos/vyos-1x pull request #964
Opened 2021-08-12 12:41 UTC by erkin

## Change Summary

Conntrack syntax v3

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): Migration
## Related Task(s)

* https://phabricator.vyos.net/T3275

## Component(s) name

conntrack

## Proposed changes

Delete all `disable` statements and add `enable` statements for other conntrack modules.

## How to test

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2021-08-12 16:19 UTC, dmbaturin requested changes

2021-08-12 16:19 UTC, dmbaturin commented on src/migration-scripts/conntrack/2-to-3
> +module_templates_dir = '/opt/vyatta/share/vyatta-cfg/templates/system/conntrack/modules'
The `/opt/vyatta/` dir is to eventually get removed, but the migration script will likely last much longer. The `/opt/vyatta/share/vyatta-cfg/templates/system/conntrack/modules` can also go away much sooner when that CLI is rewritten.

Since the number of those modules is very small, we can just hardcode it here. The list of modules _supported before the 1.3_ release also can't change in the future, so we don't need to account for modules that weren't supported at that time, since an old config couldn't have possibly relied on their existence.

2021-08-13 10:44 UTC, c-po commented
+1 for hardcoding the modules names.

That specific part is actually already rewritten for the 1.4 developmnet cycle.
https://phabricator.vyos.net/T3579

2021-08-13 10:48 UTC, dmbaturin approved these changes

2021-08-13 11:00 UTC, c-po commented
@erkin I am missing the change for the increased version file. Can you please also submit a PR in vyatta-cfg-system? https://github.com/vyos/vyatta-cfg-system/blob/current/cfg-version/conntrack%402

2021-08-13 11:11 UTC, dmbaturin commented
Also, am I missing the PR where the actual command syntax was changed? Or it's not done yet?

2021-08-14 16:19 UTC, erkin commented
You're right it seems. I went an added it.

2021-08-14 16:20 UTC, dmbaturin approved these changes

2021-08-14 16:22 UTC, erkin commented
See vyos/vyatta-cfg-system#162

2021-08-14 16:32 UTC, c-po commented
If we now have only `enable` wouldn't it make even more sense to simplify the CLI by specifying:
Because an additional `enable` node simply feels redundant to me.
```xml
          <node name="modules">
            <properties>
              <help>Connection tracking modules settings</help>
            </properties>
            <children>
              <leafNodename="ftp">
                <properties>
                  <help>FTP connection tracking settings</help>
                  <valueless/>
                </properties>
              </leafNode>
              <leafNode name="h323">
                <properties>
                  <help>H.323 connection tracking settings</help>
                  <valueless/>
                </properties>
              </leafNode>
```

2021-08-14 16:34 UTC, dmbaturin commented
@c-po That's a good point actually. It will not prevent us from adding module-specific options either: existence of a node will imply that the module is enabled. I think we should not use an extra "enable" command and just check if a node exists.

2021-08-14 16:34 UTC, erkin commented
Good idea. If no one has any complaints, I'm going to update it as such.

2021-08-15 10:10 UTC, merged