wireguard: T3763: Added check for listening port availability
vyos/vyos-1x pull request #980
Opened 2021-08-26 15:56 UTC by zdc

## Change Summary

Added check for listening port availability

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3763

## Component(s) name

wireguard, `vyos.util`

## Proposed changes

Each wireguard interface requires a unique port for in and out connections. This commit adds the new `vyos.util` function -
`check_port_availability`, and uses it to be sure that a port that is planned to be used for wireguard interface is truly available and not used by any other services (not only other wireguard interfaces).

## How to test

Configure two interfaces with the same port value:
```
set interfaces wireguard wg1 peer peer1 allowed-ips '192.0.2.2/32'
set interfaces wireguard wg1 peer peer1 public-key 'l+U1Rz38RW11ClMYYtXqEneRNu3oLn2yvI5B+jBESyY='
set interfaces wireguard wg1 port '4000'
set interfaces wireguard wg1 private-key 'IMAGzmcQOHDTN70fyJ04uiWx0+wc/BKPj4aNKYAZRXA='
set interfaces wireguard wg2 peer peer1 allowed-ips '192.0.2.2/32'
set interfaces wireguard wg2 peer peer1 public-key 'l+U1Rz38RW11ClMYYtXqEneRNu3oLn2yvI5B+jBESyY='
set interfaces wireguard wg2 port '4000'
set interfaces wireguard wg2 private-key 'IMAGzmcQOHDTN70fyJ04uiWx0+wc/BKPj4aNKYAZRXA=
```
The config will not be applied with an error:
```
The udp port 4000 on the 0.0.0.0 is busy or unavailable
The port cannot be used for the interface
```
The same with a port used by another service, for example the 123 port used by NTP:
```
set interfaces wireguard wg1 peer peer1 allowed-ips '192.0.2.2/32'
set interfaces wireguard wg1 peer peer1 public-key 'l+U1Rz38RW11ClMYYtXqEneRNu3oLn2yvI5B+jBESyY='
set interfaces wireguard wg1 port '123'
set interfaces wireguard wg1 private-key 'IMAGzmcQOHDTN70fyJ04uiWx0+wc/BKPj4aNKYAZRXA='
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2021-08-26 16:25 UTC, c-po requested changes

2021-08-26 16:25 UTC, c-po commented on python/vyos/util.py
> +    try:
Why not use `vyos.template.is_ip()` helper for this and spare the try/except?

2021-08-26 16:25 UTC, c-po commented on python/vyos/util.py
> +        print(f'The port number {port} is not in the 1-65535 range')
I'd rather raise `ValueError()` here

2021-08-26 16:25 UTC, c-po commented on python/vyos/util.py
> +        print(
I'd not output a message here, as this is part of the wireguard `verify()` function.

2021-08-26 20:22 UTC, zdc commented on python/vyos/util.py
> +    try:
It is not only checking the type but also normalize the format.

2021-08-26 20:22 UTC, zdc commented on python/vyos/util.py
> +        print(f'The port number {port} is not in the 1-65535 range')
Make sense, replaced to `ValueError()`.

2021-08-26 20:24 UTC, zdc commented on python/vyos/util.py
> +        print(
I thought first to put it here, to avoid adding a warning message in each place where the helper will be used. But, you are right - since it can be used in silent parts of scripts, better to keep it silent too. The output moved to the `verify()` in wireguard.

2021-08-27 07:38 UTC, c-po commented on python/vyos/util.py
> +    try:
Ah okay, understood.

2021-08-27 07:39 UTC, c-po approved these changes

2021-08-27 13:31 UTC, jestabro approved these changes

2021-08-28 08:49 UTC, merged

2021-08-28 11:49 UTC, c-po commented
>  I have run the components SMOKETESTS if applicable

```
11:52:41  DEBUG - OK (skipped=10)
11:52:41  DEBUG - Running Testcase: /usr/libexec/vyos/tests/smoke/cli/test_interfaces_wireguard.py
11:52:44  DEBUG - test_wireguard_add_remove_peer (__main__.WireGuardInterfaceTest) ... ERROR
11:52:47  DEBUG - test_wireguard_peer (__main__.WireGuardInterfaceTest) ... ERROR
11:52:48  DEBUG - 
11:52:48  DEBUG - ======================================================================
11:52:48  DEBUG - ERROR: test_wireguard_add_remove_peer (__main__.WireGuardInterfaceTest)
11:52:48  DEBUG - ----------------------------------------------------------------------
11:52:48  DEBUG - Traceback (most recent call last):
11:52:48  DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/test_interfaces_wireguard.py", line 87, in test_wireguard_add_remove_peer
11:52:48  DEBUG -     self.cli_commit()
11:52:48  DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/base_vyostest_shim.py", line 74, in cli_commit
11:52:48  DEBUG -     self._session.commit()
11:52:48  DEBUG -   File "/usr/lib/python3/dist-packages/vyos/configsession.py", line 163, in commit
11:52:48  DEBUG -     out = self.__run_command([COMMIT])
11:52:48  DEBUG -   File "/usr/lib/python3/dist-packages/vyos/configsession.py", line 135, in __run_command
11:52:48  DEBUG -     raise ConfigSessionError(output)
11:52:48  DEBUG - vyos.configsession.ConfigSessionError: [ interfaces wireguard wg0 ]
11:52:48  DEBUG - VyOS had an issue completing a command.
11:52:48  DEBUG - 
11:52:48  DEBUG - We are sorry that you encountered a problem while using VyOS.
11:52:48  DEBUG - There are a few things you can do to help us (and yourself):
11:52:48  DEBUG - - Contact us using the online help desk if you have a subscription:
11:52:48  DEBUG -   https://support.vyos.io/
11:52:48  DEBUG - - Make sure you are running the latest version of VyOS available at:
11:52:48  DEBUG -   https://vyos.net/get/
11:52:48  DEBUG - - Consult the community forum to see how to handle this issue:
11:52:48  DEBUG -   https://forum.vyos.io
11:52:48  DEBUG - - Join us on Slack where our users exchange help and advice:
11:52:48  DEBUG -   https://vyos.slack.com
11:52:48  DEBUG - 
11:52:48  DEBUG - When reporting problems, please include as much information as possible:
11:52:48  DEBUG - - do not obfuscate any data (feel free to contact us privately if your
11:52:48  DEBUG -   business policy requires it)
11:52:48  DEBUG - - and include all the information presented below
11:52:48  DEBUG - 
11:52:48  DEBUG - Report Time:      2021-08-28 09:52:43
11:52:48  DEBUG - Image Version:    VyOS 1.4-rolling-202108280856
11:52:48  DEBUG - Release Train:    sagitta
11:52:48  DEBUG - 
11:52:48  DEBUG - Built by:         autobuild@vyos.net
11:52:48  DEBUG - Built on:         Sat 28 Aug 2021 08:56 UTC
11:52:48  DEBUG - Build UUID:       b1244d4f-d12d-4a7c-b852-7ff4011cdb80
11:52:48  DEBUG - Build Commit ID:  393ad560653dc2
11:52:48  DEBUG - 
11:52:48  DEBUG - Architecture:     x86_64
11:52:48  DEBUG - Boot via:         installed image
11:52:48  DEBUG - System type:      KVM guest
11:52:48  DEBUG - 
11:52:48  DEBUG - Hardware vendor:  QEMU
11:52:48  DEBUG - Hardware model:   Standard PC (i440FX + PIIX, 1996)
11:52:48  DEBUG - Hardware S/N:
11:52:48  DEBUG - Hardware UUID:    Unknown
11:52:48  DEBUG - 
11:52:48  DEBUG - Traceback (most recent call last):
11:52:48  DEBUG -   File "/usr/libexec/vyos/conf_mode/interfaces-wireguard.py", line 111, in <module>
11:52:48  DEBUG -     verify(c)
11:52:48  DEBUG -   File "/usr/libexec/vyos/conf_mode/interfaces-wireguard.py", line 77, in verify
11:52:48  DEBUG -     listen_port = int(wireguard['port'])
11:52:48  DEBUG - KeyError: 'port'
11:52:48  DEBUG - 
11:52:48  DEBUG - 
11:52:48  DEBUG - 
11:52:48  DEBUG - [[interfaces wireguard wg0]] failed
11:52:48  DEBUG - Commit failed
11:52:48  DEBUG - 
11:52:48  DEBUG - 
11:52:48  DEBUG - ======================================================================
11:52:48  DEBUG - ERROR: test_wireguard_peer (__main__.WireGuardInterfaceTest)
11:52:48  DEBUG - ----------------------------------------------------------------------
11:52:48  DEBUG - Traceback (most recent call last):
11:52:48  DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/test_interfaces_wireguard.py", line 59, in test_wireguard_peer
11:52:48  DEBUG -     self.cli_commit()
11:52:48  DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/base_vyostest_shim.py", line 74, in cli_commit
11:52:48  DEBUG -     self._session.commit()
11:52:48  DEBUG -   File "/usr/lib/python3/dist-packages/vyos/configsession.py", line 163, in commit
11:52:48  DEBUG -     out = self.__run_command([COMMIT])
11:52:48  DEBUG -   File "/usr/lib/python3/dist-packages/vyos/configsession.py", line 135, in __run_command
11:52:48  DEBUG -     raise ConfigSessionError(output)
11:52:48  DEBUG - vyos.configsession.ConfigSessionError: [ interfaces wireguard wg0 ]
11:52:48  DEBUG - VyOS had an issue completing a command.
11:52:48  DEBUG - 
11:52:48  DEBUG - We are sorry that you encountered a problem while using VyOS.
11:52:48  DEBUG - There are a few things you can do to help us (and yourself):
11:52:48  DEBUG - - Contact us using the online help desk if you have a subscription:
11:52:48  DEBUG -   https://support.vyos.io/
11:52:48  DEBUG - - Make sure you are running the latest version of VyOS available at:
11:52:48  DEBUG -   https://vyos.net/get/
11:52:48  DEBUG - - Consult the community forum to see how to handle this issue:
11:52:48  DEBUG -   https://forum.vyos.io
11:52:48  DEBUG - - Join us on Slack where our users exchange help and advice:
11:52:48  DEBUG -   https://vyos.slack.com
11:52:48  DEBUG - 
11:52:48  DEBUG - When reporting problems, please include as much information as possible:
11:52:48  DEBUG - - do not obfuscate any data (feel free to contact us privately if your
11:52:48  DEBUG -   business policy requires it)
11:52:48  DEBUG - - and include all the information presented below
11:52:48  DEBUG - 
11:52:48  DEBUG - Report Time:      2021-08-28 09:52:46
11:52:48  DEBUG - Image Version:    VyOS 1.4-rolling-202108280856
11:52:48  DEBUG - Release Train:    sagitta
11:52:48  DEBUG - 
11:52:48  DEBUG - Built by:         autobuild@vyos.net
11:52:48  DEBUG - Built on:         Sat 28 Aug 2021 08:56 UTC
11:52:48  DEBUG - Build UUID:       b1244d4f-d12d-4a7c-b852-7ff4011cdb80
11:52:48  DEBUG - Build Commit ID:  393ad560653dc2
11:52:48  DEBUG - 
11:52:48  DEBUG - Architecture:     x86_64
11:52:48  DEBUG - Boot via:         installed image
11:52:48  DEBUG - System type:      KVM guest
11:52:48  DEBUG - 
11:52:48  DEBUG - Hardware vendor:  QEMU
11:52:48  DEBUG - Hardware model:   Standard PC (i440FX + PIIX, 1996)
11:52:48  DEBUG - Hardware S/N:
11:52:48  DEBUG - Hardware UUID:    Unknown
11:52:48  DEBUG - 
11:52:48  DEBUG - Traceback (most recent call last):
11:52:48  DEBUG -   File "/usr/libexec/vyos/conf_mode/interfaces-wireguard.py", line 111, in <module>
11:52:48  DEBUG -     verify(c)
11:52:48  DEBUG -   File "/usr/libexec/vyos/conf_mode/interfaces-wireguard.py", line 77, in verify
11:52:48  DEBUG -     listen_port = int(wireguard['port'])
11:52:48  DEBUG - KeyError: 'port'
11:52:48  DEBUG - 
11:52:48  DEBUG - 
11:52:48  DEBUG - 
11:52:48  DEBUG - [[interfaces wireguard wg0]] failed
11:52:48  DEBUG - Commit failed
11:52:48  DEBUG - 
11:52:48  DEBUG - 
11:52:48  DEBUG - ----------------------------------------------------------------------
11:52:48  DEBUG - Ran 2 tests in 7.044s
11:52:48  DEBUG - 
11:52:48  DEBUG - FAILED (errors=2)`
```

2021-08-29 13:20 UTC, zdc commented
Sorry, @c-po , I was not rerun tests after the PR update. The problem was fixed in https://github.com/vyos/vyos-1x/pull/982.